package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"encoding/json"
	"inspection/libs/identity"
	assignroles "inspection/services/inspection/internal/features/access/assign_role_scope"
	disablemembership "inspection/services/inspection/internal/features/access/disable_membership"
	inviteinternal "inspection/services/inspection/internal/features/access/invite_internal_user"
	assetarchive "inspection/services/inspection/internal/features/assets/archive_asset"
	assetcore "inspection/services/inspection/internal/features/assets/core"
	assetget "inspection/services/inspection/internal/features/assets/get_asset"
	assetlist "inspection/services/inspection/internal/features/assets/list_assets"
	assetregister "inspection/services/inspection/internal/features/assets/register_asset"
	assetupdate "inspection/services/inspection/internal/features/assets/update_asset"
	listaudit "inspection/services/inspection/internal/features/audit/list_events"
	capturebootstrap "inspection/services/inspection/internal/features/capture/bootstrap"
	capturecore "inspection/services/inspection/internal/features/capture/core"
	capturedeclare "inspection/services/inspection/internal/features/capture/declare_impossibility"
	capturesave "inspection/services/inspection/internal/features/capture/save_metadata"
	capturesubmit "inspection/services/inspection/internal/features/capture/submit"
	dashboardcore "inspection/services/inspection/internal/features/dashboard/core"
	inspectioncore "inspection/services/inspection/internal/features/inspections/core"
	acceptprocessing "inspection/services/inspection/internal/features/invitations/accept_processing"
	invitationcore "inspection/services/inspection/internal/features/invitations/core"
	requestotp "inspection/services/inspection/internal/features/invitations/request_otp"
	revokeinvitation "inspection/services/inspection/internal/features/invitations/revoke_invitation"
	verifyotp "inspection/services/inspection/internal/features/invitations/verify_otp"
	mediacomplete "inspection/services/inspection/internal/features/media/complete_upload"
	mediacore "inspection/services/inspection/internal/features/media/core"
	mediacreate "inspection/services/inspection/internal/features/media/create_upload"
	mediafalsepositive "inspection/services/inspection/internal/features/media/declare_false_positive"
	mediapresign "inspection/services/inspection/internal/features/media/presign_parts"
	originactivate "inspection/services/inspection/internal/features/origins/activate_version"
	origincore "inspection/services/inspection/internal/features/origins/core"
	origininvalidate "inspection/services/inspection/internal/features/origins/invalidate_version"
	origininvite "inspection/services/inspection/internal/features/origins/invite_capture"
	originlist "inspection/services/inspection/internal/features/origins/list_versions"
	participantcore "inspection/services/inspection/internal/features/participants/core"
	participantget "inspection/services/inspection/internal/features/participants/get_participant"
	participantlist "inspection/services/inspection/internal/features/participants/list_participants"
	participantchannels "inspection/services/inspection/internal/features/participants/set_delivery_channels"
	participantupsert "inspection/services/inspection/internal/features/participants/upsert_participant"
	participantverify "inspection/services/inspection/internal/features/participants/verify_channel"
	projectcore "inspection/services/inspection/internal/features/projects/core"
	recapturecore "inspection/services/inspection/internal/features/recapture/core"
	recapturerequest "inspection/services/inspection/internal/features/recapture/request"
	recapturesubmit "inspection/services/inspection/internal/features/recapture/submit"
	"inspection/services/inspection/internal/features/reports/publication"
	retentioncore "inspection/services/inspection/internal/features/retention/core"
	schedulecore "inspection/services/inspection/internal/features/schedules/core"
	segmentactivate "inspection/services/inspection/internal/features/segments/activate_definition"
	segmentcore "inspection/services/inspection/internal/features/segments/core"
	segmentlist "inspection/services/inspection/internal/features/segments/list_definitions"
	segmentpublish "inspection/services/inspection/internal/features/segments/publish_definition"
	templateactivate "inspection/services/inspection/internal/features/templates/activate_template"
	templatecore "inspection/services/inspection/internal/features/templates/core"
	templatelist "inspection/services/inspection/internal/features/templates/list_templates"
	templateprofile "inspection/services/inspection/internal/features/templates/publish_analysis_profile"
	templatepublish "inspection/services/inspection/internal/features/templates/publish_template"
	archiveunit "inspection/services/inspection/internal/features/tenancy/archive_business_unit"
	createunit "inspection/services/inspection/internal/features/tenancy/create_business_unit"
	createtenant "inspection/services/inspection/internal/features/tenancy/create_tenant"
	updatetenant "inspection/services/inspection/internal/features/tenancy/update_tenant"
	upsertunit "inspection/services/inspection/internal/features/tenancy/upsert_business_unit"
	"inspection/services/inspection/internal/platform/apperror"
	"inspection/services/inspection/internal/platform/auth"
	"inspection/services/inspection/internal/platform/database"
	graphql1 "inspection/services/inspection/internal/platform/graphql"
	"inspection/services/inspection/internal/platform/objectstore"
	"inspection/services/inspection/internal/platform/requestctx"
	"inspection/services/inspection/internal/platform/tenanttx"
	"net/http"
	"time"

	"gorm.io/gorm"
)

// CreateTenant is the resolver for the createTenant field.
func (r *mutationResolver) CreateTenant(ctx context.Context, input graphql1.CreateTenantInput) (*graphql1.CreateTenantPayload, error) {
	meta, _ := requestctx.FromContext(ctx)
	language, timezone := "pt-BR", "America/Sao_Paulo"
	if input.Language != nil {
		language = *input.Language
	}
	if input.Timezone != nil {
		timezone = *input.Timezone
	}
	raw, err := r.Bus.Send(ctx, createtenant.Command{Name: input.Name, Language: language, Timezone: timezone, BusinessUnitCode: input.BusinessUnitCode, BusinessUnitName: input.BusinessUnitName, Issuer: meta.Principal.Issuer, Subject: meta.Principal.Subject, IdempotencyKey: input.ClientMutationID})
	if err != nil {
		return nil, err
	}
	result := raw.(createtenant.Result)
	return &graphql1.CreateTenantPayload{Tenant: &graphql1.Tenant{ID: result.TenantID.String(), Name: input.Name, Language: language, DefaultTimezone: timezone, Status: result.Status, Version: 1}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// UpdateTenant is the resolver for the updateTenant field.
func (r *mutationResolver) UpdateTenant(ctx context.Context, input graphql1.UpdateTenantInput) (*graphql1.TenantPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	raw, err := r.Bus.Send(ctx, updatetenant.Command{TenantID: meta.TenantID, Name: input.Name, Language: input.Language, Timezone: input.Timezone, ExpectedVersion: int64(input.ExpectedVersion)})
	if err != nil {
		return nil, err
	}
	tenant := raw.(database.Tenant)
	return &graphql1.TenantPayload{Tenant: &graphql1.Tenant{ID: tenant.ID.String(), Name: tenant.Name, Language: tenant.Language, DefaultTimezone: tenant.DefaultTimezone, Status: tenant.Status, Version: int(tenant.Version)}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CreateBusinessUnit is the resolver for the createBusinessUnit field.
func (r *mutationResolver) CreateBusinessUnit(ctx context.Context, input graphql1.CreateBusinessUnitInput) (*graphql1.BusinessUnitPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin); err != nil {
		return nil, err
	}
	raw, err := r.Bus.Send(ctx, createunit.Command{TenantID: meta.TenantID, Code: input.Code, Name: input.Name, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID), ExpectedTenantVersion: int64(input.ExpectedTenantVersion)})
	if err != nil {
		return nil, err
	}
	unit := raw.(database.BusinessUnit)
	return &graphql1.BusinessUnitPayload{BusinessUnit: &graphql1.BusinessUnit{ID: unit.ID.String(), Code: unit.Code, Name: unit.Name, Status: unit.Status, Version: int(unit.Version)}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// UpsertBusinessUnit is the resolver for the upsertBusinessUnit field.
func (r *mutationResolver) UpsertBusinessUnit(ctx context.Context, input graphql1.UpsertBusinessUnitInput) (*graphql1.BusinessUnitPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	command := upsertunit.Command{TenantID: meta.TenantID, Code: input.Code, Name: input.Name, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID)}
	if input.BusinessUnitID != nil {
		id, err := identity.ParseID(*input.BusinessUnitID)
		if err != nil {
			return nil, invalidID("businessUnitId")
		}
		command.BusinessUnitID, command.HasBusinessUnitID = id, true
	}
	if input.ExpectedVersion != nil {
		command.ExpectedVersion = int64(*input.ExpectedVersion)
	}
	if input.ExpectedTenantVersion != nil {
		command.ExpectedTenantVersion = int64(*input.ExpectedTenantVersion)
	}
	raw, err := r.Bus.Send(ctx, command)
	if err != nil {
		return nil, err
	}
	unit := raw.(database.BusinessUnit)
	return &graphql1.BusinessUnitPayload{BusinessUnit: &graphql1.BusinessUnit{ID: unit.ID.String(), Code: unit.Code, Name: unit.Name, Status: unit.Status, Version: int(unit.Version)}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// ArchiveBusinessUnit is the resolver for the archiveBusinessUnit field.
func (r *mutationResolver) ArchiveBusinessUnit(ctx context.Context, input graphql1.ArchiveBusinessUnitInput) (*graphql1.BusinessUnitPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.BusinessUnitID)
	if err != nil {
		return nil, invalidID("businessUnitId")
	}
	raw, err := r.Bus.Send(ctx, archiveunit.Command{TenantID: meta.TenantID, BusinessUnitID: id, ExpectedVersion: int64(input.ExpectedVersion)})
	if err != nil {
		return nil, err
	}
	unit := raw.(database.BusinessUnit)
	return &graphql1.BusinessUnitPayload{BusinessUnit: &graphql1.BusinessUnit{ID: unit.ID.String(), Code: unit.Code, Name: unit.Name, Status: unit.Status, Version: int(unit.Version)}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// InviteInternalUser is the resolver for the inviteInternalUser field.
func (r *mutationResolver) InviteInternalUser(ctx context.Context, input graphql1.InviteInternalUserInput) (*graphql1.MembershipPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	scopes := make([]inviteinternal.Scope, 0, len(input.Scopes))
	for _, scope := range input.Scopes {
		if scope == nil {
			return nil, graphql1Error("scopes")
		}
		id, err := identity.ParseID(scope.ResourceID)
		if err != nil {
			return nil, invalidID("scopes")
		}
		scopes = append(scopes, inviteinternal.Scope{Kind: scope.Kind, ResourceID: id})
	}
	raw, err := r.Bus.Send(ctx, inviteinternal.Command{TenantID: meta.TenantID, Issuer: input.Issuer, Subject: input.Subject, Role: input.Role, Scopes: scopes, ClientID: requestctx.IdempotencyKey(ctx, input.ClientMutationID)})
	if err != nil {
		return nil, err
	}
	membership, err := mapMembership(ctx, r.DB, raw.(database.Membership))
	if err != nil {
		return nil, err
	}
	return &graphql1.MembershipPayload{Membership: membership, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// AssignRoleScopes is the resolver for the assignRoleScopes field.
func (r *mutationResolver) AssignRoleScopes(ctx context.Context, input graphql1.AssignRoleScopesInput) (*graphql1.MembershipPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	membershipID, err := identity.ParseID(input.MembershipID)
	if err != nil {
		return nil, invalidID("membershipId")
	}
	assignments := make([]assignroles.Assignment, 0, len(input.Scopes))
	for _, scope := range input.Scopes {
		if scope == nil {
			return nil, graphql1Error("scopes")
		}
		id, parseErr := identity.ParseID(scope.ResourceID)
		if parseErr != nil {
			return nil, invalidID("scopes")
		}
		assignments = append(assignments, assignroles.Assignment{Kind: scope.Kind, ResourceID: id})
	}
	var expected int64
	if input.ExpectedVersion != nil {
		expected = int64(*input.ExpectedVersion)
	}
	if _, err := r.Bus.Send(ctx, assignroles.Command{TenantID: meta.TenantID, MembershipID: membershipID, Role: input.Role, Assignments: assignments, ExpectedVersion: expected}); err != nil {
		return nil, err
	}
	var membership database.Membership
	if err := (tenanttx.Runner{DB: r.DB}).Within(ctx, meta.TenantID, func(tx *gorm.DB) error {
		return tx.Where("tenant_id = ? AND id = ?", meta.TenantID, membershipID).First(&membership).Error
	}); err != nil {
		return nil, err
	}
	mapped, err := mapMembership(ctx, r.DB, membership)
	if err != nil {
		return nil, err
	}
	return &graphql1.MembershipPayload{Membership: mapped, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// DisableMembership is the resolver for the disableMembership field.
func (r *mutationResolver) DisableMembership(ctx context.Context, input graphql1.DisableMembershipInput) (*graphql1.MembershipPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	membershipID, err := identity.ParseID(input.MembershipID)
	if err != nil {
		return nil, invalidID("membershipId")
	}
	raw, err := r.Bus.Send(ctx, disablemembership.Command{TenantID: meta.TenantID, MembershipID: membershipID, ExpectedVersion: int64(input.ExpectedVersion)})
	if err != nil {
		return nil, err
	}
	mapped, err := mapMembership(ctx, r.DB, raw.(database.Membership))
	if err != nil {
		return nil, err
	}
	return &graphql1.MembershipPayload{Membership: mapped, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// UpsertParticipant is the resolver for the upsertParticipant field.
func (r *mutationResolver) UpsertParticipant(ctx context.Context, input graphql1.UpsertParticipantInput) (*graphql1.ParticipantPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	unitID, err := identity.ParseID(input.BusinessUnitID)
	if err != nil {
		return nil, invalidID("businessUnitId")
	}
	contacts := make([]participantcore.ContactInput, 0, len(input.Contacts))
	for _, c := range input.Contacts {
		contacts = append(contacts, participantcore.ContactInput{Channel: c.Channel, Value: c.Value})
	}
	var participantID *identity.ID
	if input.ParticipantID != nil {
		id, e := identity.ParseID(*input.ParticipantID)
		if e != nil {
			return nil, invalidID("participantId")
		}
		participantID = &id
	}
	var expected int64
	if input.ExpectedVersion != nil {
		expected = int64(*input.ExpectedVersion)
	}
	raw, err := r.Bus.Send(ctx, participantupsert.Command{TenantID: meta.TenantID, BusinessUnitID: unitID, ParticipantID: participantID, ExpectedVersion: expected, Name: input.Name, SegmentRole: input.SegmentRole, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID), Contacts: contacts})
	if err != nil {
		return nil, err
	}
	return &graphql1.ParticipantPayload{Participant: mapParticipant(raw.(participantcore.ParticipantView)), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// VerifyContact is the resolver for the verifyContact field.
func (r *mutationResolver) VerifyContact(ctx context.Context, input graphql1.VerifyContactInput) (*graphql1.ParticipantContactPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.ContactID)
	if err != nil {
		return nil, invalidID("contactId")
	}
	raw, err := r.Bus.Send(ctx, participantverify.Command{TenantID: meta.TenantID, ContactID: id, Success: input.Verified, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID)})
	if err != nil {
		return nil, err
	}
	v := raw.(database.ContactVerification)
	return &graphql1.ParticipantContactPayload{Contact: &graphql1.ParticipantContact{ID: v.ContactID.String(), Verified: v.Status == "VERIFIED", Active: true}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// SetDeliveryChannels is the resolver for the setDeliveryChannels field.
func (r *mutationResolver) SetDeliveryChannels(ctx context.Context, input graphql1.SetDeliveryChannelsInput) (*graphql1.ParticipantPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.ParticipantID)
	if err != nil {
		return nil, invalidID("participantId")
	}
	ids := make([]identity.ID, 0, len(input.ContactIds))
	for _, value := range input.ContactIds {
		parsed, e := identity.ParseID(value)
		if e != nil {
			return nil, invalidID("contactIds")
		}
		ids = append(ids, parsed)
	}
	raw, err := r.Bus.Send(ctx, participantchannels.Command{TenantID: meta.TenantID, ParticipantID: id, ContactIDs: ids, ExpectedVersion: int64(input.ExpectedVersion)})
	if err != nil {
		return nil, err
	}
	return &graphql1.ParticipantPayload{Participant: mapParticipant(raw.(participantcore.ParticipantView)), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// PublishSegmentDefinition is the resolver for the publishSegmentDefinition field.
func (r *mutationResolver) PublishSegmentDefinition(ctx context.Context, input graphql1.PublishSegmentDefinitionInput) (*graphql1.SegmentDefinitionPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	schema, _ := json.Marshal(input.Schema)
	ui, _ := json.Marshal(input.UISchema)
	raw, err := r.Bus.Send(ctx, segmentpublish.Command{TenantID: meta.TenantID, Key: input.Key, Name: input.Name, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID), SchemaJSON: schema, UISchemaJSON: ui})
	if err != nil {
		return nil, err
	}
	v := raw.(segmentcore.View)
	return &graphql1.SegmentDefinitionPayload{Definition: mapSegment(v.Definition), Version: mapSegmentVersion(v.Version), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// ActivateSegmentDefinition is the resolver for the activateSegmentDefinition field.
func (r *mutationResolver) ActivateSegmentDefinition(ctx context.Context, input graphql1.ActivateSegmentDefinitionInput) (*graphql1.SegmentDefinitionPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	versionID, err := identity.ParseID(input.VersionID)
	if err != nil {
		return nil, invalidID("versionId")
	}
	raw, err := r.Bus.Send(ctx, segmentactivate.Command{TenantID: meta.TenantID, VersionID: versionID, ExpectedVersion: int64(input.ExpectedVersion)})
	if err != nil {
		return nil, err
	}
	v := raw.(segmentcore.View)
	return &graphql1.SegmentDefinitionPayload{Definition: mapSegment(v.Definition), Version: mapSegmentVersion(v.Version), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// PublishTemplateVersion is the resolver for the publishTemplateVersion field.
func (r *mutationResolver) PublishTemplateVersion(ctx context.Context, input graphql1.PublishTemplateVersionInput) (*graphql1.TemplatePayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	payload, _ := json.Marshal(input.Definition)
	raw, err := r.Bus.Send(ctx, templatepublish.Command{TenantID: meta.TenantID, Key: input.Key, Name: input.Name, DefinitionJSON: payload, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID)})
	if err != nil {
		return nil, err
	}
	return mapTemplatePayload(raw.(templatecore.View), input.ClientMutationID), nil
}

// ActivateTemplateVersion is the resolver for the activateTemplateVersion field.
func (r *mutationResolver) ActivateTemplateVersion(ctx context.Context, input graphql1.ActivateTemplateVersionInput) (*graphql1.TemplatePayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.VersionID)
	if err != nil {
		return nil, invalidID("versionId")
	}
	raw, err := r.Bus.Send(ctx, templateactivate.Command{TenantID: meta.TenantID, VersionID: id, ExpectedVersion: int64(input.ExpectedVersion)})
	if err != nil {
		return nil, err
	}
	return mapTemplatePayload(raw.(templatecore.View), input.ClientMutationID), nil
}

// PublishAnalysisProfile is the resolver for the publishAnalysisProfile field.
func (r *mutationResolver) PublishAnalysisProfile(ctx context.Context, input graphql1.PublishAnalysisProfileInput) (*graphql1.AnalysisProfilePayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	payload, _ := json.Marshal(input.Definition)
	raw, err := r.Bus.Send(ctx, templateprofile.Command{TenantID: meta.TenantID, Key: input.Key, DefinitionJSON: payload, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID)})
	if err != nil {
		return nil, err
	}
	p := raw.(database.AnalysisProfileVersion)
	definition := map[string]any{}
	_ = json.Unmarshal(p.DefinitionJSON, &definition)
	return &graphql1.AnalysisProfilePayload{Profile: &graphql1.AnalysisProfile{ID: p.ID.String(), Key: p.Key, VersionNumber: p.VersionNumber, SchemaVersion: p.SchemaVersion, Definition: definition, CanonicalDigest: p.CanonicalDigest, Status: p.Status, PublishedAt: p.PublishedAt.Format(time.RFC3339Nano)}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// RegisterAsset is the resolver for the registerAsset field.
func (r *mutationResolver) RegisterAsset(ctx context.Context, input graphql1.RegisterAssetInput) (*graphql1.AssetPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if input.Asset == nil {
		return nil, graphql1Error("asset")
	}
	command, err := mapAssetInput(meta.TenantID, *input.Asset, requestctx.IdempotencyKey(ctx, input.ClientMutationID))
	if err != nil {
		return nil, err
	}
	raw, err := r.Bus.Send(ctx, assetregister.Command(command))
	if err != nil {
		return nil, err
	}
	return &graphql1.AssetPayload{Asset: mapAsset(raw.(assetcore.View)), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// UpdateAsset is the resolver for the updateAsset field.
func (r *mutationResolver) UpdateAsset(ctx context.Context, input graphql1.UpdateAssetInput) (*graphql1.AssetPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.AssetID)
	if err != nil {
		return nil, invalidID("assetId")
	}
	if input.Asset == nil {
		return nil, graphql1Error("asset")
	}
	command, err := mapAssetInput(meta.TenantID, *input.Asset, requestctx.IdempotencyKey(ctx, input.ClientMutationID))
	if err != nil {
		return nil, err
	}
	raw, err := r.Bus.Send(ctx, assetupdate.Command{AssetID: id, ExpectedVersion: int64(input.ExpectedVersion), Input: command})
	if err != nil {
		return nil, err
	}
	return &graphql1.AssetPayload{Asset: mapAsset(raw.(assetcore.View)), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// ArchiveAsset is the resolver for the archiveAsset field.
func (r *mutationResolver) ArchiveAsset(ctx context.Context, input graphql1.ArchiveAssetInput) (*graphql1.AssetPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.AssetID)
	if err != nil {
		return nil, invalidID("assetId")
	}
	if _, err := r.Bus.Send(ctx, assetarchive.Command{TenantID: meta.TenantID, AssetID: id, ExpectedVersion: int64(input.ExpectedVersion)}); err != nil {
		return nil, err
	}
	return &graphql1.AssetPayload{UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// RequestInvitationOtp is the resolver for the requestInvitationOtp field.
func (r *mutationResolver) RequestInvitationOtp(ctx context.Context, input graphql1.RequestInvitationOtpInput) (*graphql1.InvitationOtpPayload, error) {
	raw, err := r.Bus.Send(ctx, requestotp.Command{LinkToken: input.LinkToken, ClientMutationID: input.ClientMutationID})
	if err != nil {
		return nil, err
	}
	return &graphql1.InvitationOtpPayload{Status: raw.(requestotp.Result).Status, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// VerifyInvitationOtp is the resolver for the verifyInvitationOtp field.
func (r *mutationResolver) VerifyInvitationOtp(ctx context.Context, input graphql1.VerifyInvitationOtpInput) (*graphql1.ExternalSessionPayload, error) {
	raw, err := r.Bus.Send(ctx, verifyotp.Command{LinkToken: input.LinkToken, Code: input.Code, ClientMutationID: input.ClientMutationID})
	if err != nil {
		return nil, err
	}
	session := raw.(verifyotp.Result)
	writer, ok := requestctx.ResponseWriter(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	http.SetCookie(writer, &http.Cookie{Name: "inspection_external", Value: session.Token, Path: "/", Expires: session.ExpiresAt, MaxAge: int(time.Until(session.ExpiresAt).Seconds()), Secure: requestctx.SecureCookies(ctx), HttpOnly: true, SameSite: http.SameSiteLaxMode})
	return &graphql1.ExternalSessionPayload{Status: "ACTIVE", CsrfToken: session.CSRF, ExpiresAt: session.ExpiresAt.Format(time.RFC3339Nano), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// RevokeInvitation is the resolver for the revokeInvitation field.
func (r *mutationResolver) RevokeInvitation(ctx context.Context, input graphql1.RevokeInvitationInput) (*graphql1.InvitationPayload, error) {
	raw, err := r.Bus.Send(ctx, revokeinvitation.Command{LinkToken: input.LinkToken, ClientMutationID: input.ClientMutationID})
	if err != nil {
		return nil, err
	}
	if writer, ok := requestctx.ResponseWriter(ctx); ok {
		http.SetCookie(writer, &http.Cookie{Name: "inspection_external", Value: "", Path: "/", MaxAge: -1, Secure: requestctx.SecureCookies(ctx), HttpOnly: true, SameSite: http.SameSiteLaxMode})
	}
	return &graphql1.InvitationPayload{Status: raw.(revokeinvitation.Result).Status, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// InviteOriginCapture is the resolver for the inviteOriginCapture field.
func (r *mutationResolver) InviteOriginCapture(ctx context.Context, input graphql1.InviteOriginCaptureInput) (*graphql1.OriginInvitationPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	assetID, err := identity.ParseID(input.AssetID)
	if err != nil {
		return nil, invalidID("assetId")
	}
	participantID, err := identity.ParseID(input.ParticipantID)
	if err != nil {
		return nil, invalidID("participantId")
	}
	expires, err := time.Parse(time.RFC3339, input.ExpiresAt)
	if err != nil {
		return nil, graphql1Error("expiresAt")
	}
	raw, err := r.Bus.Send(ctx, origininvite.Command{TenantID: meta.TenantID, AssetID: assetID, ParticipantID: participantID, ExpiresAt: expires, IdempotencyKey: input.ClientMutationID})
	if err != nil {
		return nil, err
	}
	created := raw.(origincore.Invitation)
	invitationID, versionID := created.InvitationID.String(), created.VersionID.String()
	return &graphql1.OriginInvitationPayload{InvitationID: &invitationID, OriginVersionID: &versionID, Status: "SENT", UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// ActivateOriginVersion is the resolver for the activateOriginVersion field.
func (r *mutationResolver) ActivateOriginVersion(ctx context.Context, input graphql1.OriginVersionInput) (*graphql1.OriginVersionPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.VersionID)
	if err != nil {
		return nil, invalidID("versionId")
	}
	raw, err := r.Bus.Send(ctx, originactivate.Command{TenantID: meta.TenantID, VersionID: id})
	if err != nil {
		return nil, err
	}
	row := raw.(database.OriginVersion)
	return &graphql1.OriginVersionPayload{Version: mapOriginVersion(row), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// InvalidateOriginVersion is the resolver for the invalidateOriginVersion field.
func (r *mutationResolver) InvalidateOriginVersion(ctx context.Context, input graphql1.OriginVersionInput) (*graphql1.OriginVersionPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.VersionID)
	if err != nil {
		return nil, invalidID("versionId")
	}
	raw, err := r.Bus.Send(ctx, origininvalidate.Command{TenantID: meta.TenantID, VersionID: id})
	if err != nil {
		return nil, err
	}
	row := raw.(database.OriginVersion)
	return &graphql1.OriginVersionPayload{Version: mapOriginVersion(row), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CreateSchedule is the resolver for the createSchedule field.
func (r *mutationResolver) CreateSchedule(ctx context.Context, input graphql1.CreateScheduleInput) (*graphql1.SchedulePayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	assetID, err := identity.ParseID(input.AssetID)
	if err != nil {
		return nil, invalidID("assetId")
	}
	participantID, err := identity.ParseID(input.ParticipantID)
	if err != nil {
		return nil, invalidID("participantId")
	}
	templateID, err := identity.ParseID(input.TemplateID)
	if err != nil {
		return nil, invalidID("templateId")
	}
	referenceID, err := parseOptionalID(input.ReferenceVersionID, "referenceVersionId")
	if err != nil {
		return nil, err
	}
	startsAt, err := parseInstant(input.StartsAt, "startsAt")
	if err != nil {
		return nil, err
	}
	row, err := r.ScheduleService.Create(ctx, schedulecore.Input{TenantID: meta.TenantID, AssetID: assetID, ParticipantID: participantID, TemplateID: templateID, ReferenceVersionID: referenceID, RRule: input.Rrule, Timezone: input.Timezone, StartsAt: startsAt, DeadlineMinutes: input.DeadlineMinutes, ReminderOffsetsMinutes: input.ReminderOffsetsMinutes, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID)})
	if err != nil {
		return nil, err
	}
	return &graphql1.SchedulePayload{Schedule: mapSchedule(row), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// UpdateSchedule is the resolver for the updateSchedule field.
func (r *mutationResolver) UpdateSchedule(ctx context.Context, input graphql1.UpdateScheduleInput) (*graphql1.SchedulePayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	scheduleID, err := identity.ParseID(input.ScheduleID)
	if err != nil {
		return nil, invalidID("scheduleId")
	}
	startsAt, err := parseInstant(input.StartsAt, "startsAt")
	if err != nil {
		return nil, err
	}
	row, err := r.ScheduleService.Update(ctx, schedulecore.UpdateInput{TenantID: meta.TenantID, ScheduleID: scheduleID, ExpectedVersion: int64(input.ExpectedVersion), RRule: input.Rrule, Timezone: input.Timezone, StartsAt: startsAt, DeadlineMinutes: input.DeadlineMinutes, ReminderOffsetsMinutes: input.ReminderOffsetsMinutes})
	if err != nil {
		return nil, err
	}
	return &graphql1.SchedulePayload{Schedule: mapSchedule(row), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CancelSchedule is the resolver for the cancelSchedule field.
func (r *mutationResolver) CancelSchedule(ctx context.Context, input graphql1.CancelScheduleInput) (*graphql1.SchedulePayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	scheduleID, err := identity.ParseID(input.ScheduleID)
	if err != nil {
		return nil, invalidID("scheduleId")
	}
	row, err := r.ScheduleService.Cancel(ctx, meta.TenantID, scheduleID, int64(input.ExpectedVersion))
	if err != nil {
		return nil, err
	}
	return &graphql1.SchedulePayload{Schedule: mapSchedule(row), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CreateInspection is the resolver for the createInspection field.
func (r *mutationResolver) CreateInspection(ctx context.Context, input graphql1.CreateInspectionInput) (*graphql1.InspectionPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	assetID, err := identity.ParseID(input.AssetID)
	if err != nil {
		return nil, invalidID("assetId")
	}
	participantID, err := identity.ParseID(input.ParticipantID)
	if err != nil {
		return nil, invalidID("participantId")
	}
	templateID, err := parseOptionalID(input.TemplateID, "templateId")
	if err != nil {
		return nil, err
	}
	referenceID, err := parseOptionalID(input.ReferenceVersionID, "referenceVersionId")
	if err != nil {
		return nil, err
	}
	dueAt, err := parseInstant(input.DueAt, "dueAt")
	if err != nil {
		return nil, err
	}
	deadlineAt, err := parseInstant(input.DeadlineAt, "deadlineAt")
	if err != nil {
		return nil, err
	}
	reminders, err := parseInstants(input.ReminderInstants, "reminderInstants")
	if err != nil {
		return nil, err
	}
	view, err := r.InspectionService.Create(ctx, inspectioncore.CreateInput{TenantID: meta.TenantID, AssetID: assetID, ParticipantID: participantID, TemplateID: templateID, ReferenceVersionID: referenceID, Source: inspectioncore.SourceManual, SourceKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID), Reason: input.Reason, DueAt: dueAt, DeadlineAt: deadlineAt, ReminderInstants: reminders})
	if err != nil {
		return nil, err
	}
	return &graphql1.InspectionPayload{Inspection: mapInspection(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CancelInspection is the resolver for the cancelInspection field.
func (r *mutationResolver) CancelInspection(ctx context.Context, input graphql1.InspectionTransitionInput) (*graphql1.InspectionPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.InspectionID)
	if err != nil {
		return nil, invalidID("inspectionId")
	}
	view, err := r.InspectionService.Cancel(ctx, meta.TenantID, id, int64(input.ExpectedVersion))
	if err != nil {
		return nil, err
	}
	return &graphql1.InspectionPayload{Inspection: mapInspection(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// InvalidateInspection is the resolver for the invalidateInspection field.
func (r *mutationResolver) InvalidateInspection(ctx context.Context, input graphql1.InvalidateInspectionInput) (*graphql1.InspectionPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(input.InspectionID)
	if err != nil {
		return nil, invalidID("inspectionId")
	}
	view, err := r.InspectionService.Invalidate(ctx, meta.TenantID, id, int64(input.ExpectedVersion), input.Reason)
	if err != nil {
		return nil, err
	}
	return &graphql1.InspectionPayload{Inspection: mapInspection(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input graphql1.CreateProjectInput) (*graphql1.ProjectPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	assetID, err := identity.ParseID(input.AssetID)
	if err != nil {
		return nil, invalidID("assetId")
	}
	participantID, err := identity.ParseID(input.ParticipantID)
	if err != nil {
		return nil, invalidID("participantId")
	}
	templateID, err := parseOptionalID(input.TemplateID, "templateId")
	if err != nil {
		return nil, err
	}
	view, err := r.ProjectService.Create(ctx, projectcore.CreateInput{TenantID: meta.TenantID, AssetID: assetID, ParticipantID: participantID, TemplateID: templateID, IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID)})
	if err != nil {
		return nil, err
	}
	return &graphql1.ProjectPayload{Project: mapProject(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// AddExceptionalStage is the resolver for the addExceptionalStage field.
func (r *mutationResolver) AddExceptionalStage(ctx context.Context, input graphql1.AddExceptionalStageInput) (*graphql1.ProjectPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	projectID, err := identity.ParseID(input.ProjectID)
	if err != nil {
		return nil, invalidID("projectId")
	}
	var plannedAt *time.Time
	if input.PlannedAt != nil {
		value, parseErr := parseInstant(*input.PlannedAt, "plannedAt")
		if parseErr != nil {
			return nil, parseErr
		}
		plannedAt = &value
	}
	view, err := r.ProjectService.AddExceptionalStage(ctx, projectcore.ExceptionalStageInput{TenantID: meta.TenantID, ProjectID: projectID, Key: input.Key, Label: input.Label, Reason: input.Reason, PlannedAt: plannedAt, ExpectedVersion: int64(input.ExpectedVersion), IdempotencyKey: requestctx.IdempotencyKey(ctx, input.ClientMutationID)})
	if err != nil {
		return nil, err
	}
	return &graphql1.ProjectPayload{Project: mapProject(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// StartProjectStage is the resolver for the startProjectStage field.
func (r *mutationResolver) StartProjectStage(ctx context.Context, input graphql1.StartProjectStageInput) (*graphql1.ProjectPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	projectID, err := identity.ParseID(input.ProjectID)
	if err != nil {
		return nil, invalidID("projectId")
	}
	stageID, err := identity.ParseID(input.StageID)
	if err != nil {
		return nil, invalidID("stageId")
	}
	referenceID, err := parseOptionalID(input.ReferenceVersionID, "referenceVersionId")
	if err != nil {
		return nil, err
	}
	dueAt, err := parseInstant(input.DueAt, "dueAt")
	if err != nil {
		return nil, err
	}
	deadlineAt, err := parseInstant(input.DeadlineAt, "deadlineAt")
	if err != nil {
		return nil, err
	}
	reminders, err := parseInstants(input.ReminderInstants, "reminderInstants")
	if err != nil {
		return nil, err
	}
	view, err := r.ProjectService.StartStage(ctx, projectcore.StartStageInput{TenantID: meta.TenantID, ProjectID: projectID, StageID: stageID, ExpectedProjectVersion: int64(input.ExpectedProjectVersion), ExpectedStageVersion: int64(input.ExpectedStageVersion), ReferenceVersionID: referenceID, DueAt: dueAt, DeadlineAt: deadlineAt, ReminderInstants: reminders})
	if err != nil {
		return nil, err
	}
	return &graphql1.ProjectPayload{Project: mapProject(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// SkipProjectStage is the resolver for the skipProjectStage field.
func (r *mutationResolver) SkipProjectStage(ctx context.Context, input graphql1.SkipProjectStageInput) (*graphql1.ProjectPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	projectID, err := identity.ParseID(input.ProjectID)
	if err != nil {
		return nil, invalidID("projectId")
	}
	stageID, err := identity.ParseID(input.StageID)
	if err != nil {
		return nil, invalidID("stageId")
	}
	view, err := r.ProjectService.SkipStage(ctx, projectcore.TransitionInput{TenantID: meta.TenantID, ProjectID: projectID, StageID: &stageID, ExpectedVersion: int64(input.ExpectedVersion), Reason: input.Reason})
	if err != nil {
		return nil, err
	}
	return &graphql1.ProjectPayload{Project: mapProject(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CloseProject is the resolver for the closeProject field.
func (r *mutationResolver) CloseProject(ctx context.Context, input graphql1.ProjectTransitionInput) (*graphql1.ProjectPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	projectID, err := identity.ParseID(input.ProjectID)
	if err != nil {
		return nil, invalidID("projectId")
	}
	view, err := r.ProjectService.Close(ctx, projectcore.TransitionInput{TenantID: meta.TenantID, ProjectID: projectID, ExpectedVersion: int64(input.ExpectedVersion)})
	if err != nil {
		return nil, err
	}
	return &graphql1.ProjectPayload{Project: mapProject(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// ReopenProject is the resolver for the reopenProject field.
func (r *mutationResolver) ReopenProject(ctx context.Context, input graphql1.ReopenProjectInput) (*graphql1.ProjectPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	projectID, err := identity.ParseID(input.ProjectID)
	if err != nil {
		return nil, invalidID("projectId")
	}
	view, err := r.ProjectService.Reopen(ctx, projectcore.TransitionInput{TenantID: meta.TenantID, ProjectID: projectID, ExpectedVersion: int64(input.ExpectedVersion), Reason: input.Reason})
	if err != nil {
		return nil, err
	}
	return &graphql1.ProjectPayload{Project: mapProject(view), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// AcceptProcessing is the resolver for the acceptProcessing field.
func (r *mutationResolver) AcceptProcessing(ctx context.Context, input graphql1.AcceptProcessingInput) (*graphql1.CapturePayload, error) {
	credentials, ok := requestctx.ExternalCredentialsFromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	_, err := r.Bus.Send(ctx, acceptprocessing.Command{SessionToken: credentials.SessionToken, CSRFToken: credentials.CSRFToken, Consent: invitationcore.ProcessingConsent{DisclosureVersion: input.DisclosureVersion, PhotoProcessing: input.PhotoProcessing, AIAnalysis: input.AiAnalysis, GPSUse: input.GpsUse}})
	if err != nil {
		return nil, err
	}
	return &graphql1.CapturePayload{Status: "ACCEPTED", UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CreateMediaUpload is the resolver for the createMediaUpload field.
func (r *mutationResolver) CreateMediaUpload(ctx context.Context, input graphql1.CreateMediaUploadInput) (*graphql1.MediaUploadPayload, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	raw, err := r.Bus.Send(ctx, mediacreate.Command{TenantID: tenantID, ResponsibilityID: responsibilityID, ContentType: input.ContentType, SHA256: input.Sha256, SizeBytes: int64(input.SizeBytes), IdempotencyKey: input.ClientMutationID})
	if err != nil {
		return nil, err
	}
	upload := raw.(mediacore.Upload)
	return &graphql1.MediaUploadPayload{Upload: &graphql1.MediaUpload{MediaID: upload.MediaID.String(), UploadID: upload.UploadID, ExpiresAt: upload.ExpiresAt.Format(time.RFC3339Nano), PartSizeBytes: objectstore.PartSizeBytes}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// PresignMediaParts is the resolver for the presignMediaParts field.
func (r *mutationResolver) PresignMediaParts(ctx context.Context, input graphql1.PresignMediaPartsInput) (*graphql1.PresignedPartsPayload, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	mediaID, err := identity.ParseID(input.MediaID)
	if err != nil {
		return nil, invalidID("mediaId")
	}
	raw, err := r.Bus.Send(ctx, mediapresign.Command{TenantID: tenantID, ResponsibilityID: responsibilityID, MediaID: mediaID, Parts: input.PartNumbers})
	if err != nil {
		return nil, err
	}
	parts := raw.([]objectstore.PresignedPart)
	mapped := make([]*graphql1.PresignedPart, 0, len(parts))
	for _, part := range parts {
		mapped = append(mapped, &graphql1.PresignedPart{PartNumber: part.PartNumber, URL: part.URL, ExpiresAt: part.ExpiresAt.Format(time.RFC3339Nano)})
	}
	return &graphql1.PresignedPartsPayload{Parts: mapped, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// CompleteMediaUpload is the resolver for the completeMediaUpload field.
func (r *mutationResolver) CompleteMediaUpload(ctx context.Context, input graphql1.CompleteMediaUploadInput) (*graphql1.MediaPayload, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	mediaID, err := identity.ParseID(input.MediaID)
	if err != nil {
		return nil, invalidID("mediaId")
	}
	parts := make([]objectstore.Part, 0, len(input.Parts))
	for _, part := range input.Parts {
		parts = append(parts, objectstore.Part{Number: part.PartNumber, ETag: part.Etag})
	}
	raw, err := r.Bus.Send(ctx, mediacomplete.Command{TenantID: tenantID, ResponsibilityID: responsibilityID, MediaID: mediaID, Parts: parts})
	if err != nil {
		return nil, err
	}
	media := raw.(database.MediaObject)
	return &graphql1.MediaPayload{Media: mapMedia(media), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// SaveCaptureMetadata is the resolver for the saveCaptureMetadata field.
func (r *mutationResolver) SaveCaptureMetadata(ctx context.Context, input graphql1.SaveCaptureMetadataInput) (*graphql1.MediaPayload, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	mediaID, err := identity.ParseID(input.MediaID)
	if err != nil {
		return nil, invalidID("mediaId")
	}
	bootstrapRaw, err := r.Bus.Ask(ctx, capturebootstrap.Query{TenantID: tenantID, ResponsibilityID: responsibilityID})
	if err != nil {
		return nil, err
	}
	bootstrap := bootstrapRaw.(capturecore.Bootstrap)
	var policyDoc struct {
		GPSRequired                       bool    `json:"gpsRequired"`
		AllowGallery                      bool    `json:"allowGallery"`
		GeofenceMeters                    float64 `json:"geofenceMeters"`
		AssetLatitudeE6, AssetLongitudeE6 *int32
	}
	_ = json.Unmarshal(bootstrap.Draft.PolicyPayload, &policyDoc)
	var lat, lon *float64
	if policyDoc.AssetLatitudeE6 != nil && policyDoc.AssetLongitudeE6 != nil {
		a, b := float64(*policyDoc.AssetLatitudeE6)/1e6, float64(*policyDoc.AssetLongitudeE6)/1e6
		lat, lon = &a, &b
	}
	metadata := capturecore.MetadataInput{TenantID: tenantID, ResponsibilityID: responsibilityID, MediaID: mediaID, RequirementKey: input.RequirementKey, Description: input.Description, CaptureSource: input.CaptureSource, DeviceContext: input.DeviceContext, Policy: capturecore.GPSPolicy{Required: policyDoc.GPSRequired, AllowGallery: policyDoc.AllowGallery, AssetLatitude: lat, AssetLongitude: lon, GeofenceMeters: policyDoc.GeofenceMeters}}
	if input.Gps != nil {
		captured, _ := time.Parse(time.RFC3339, input.Gps.CapturedAt)
		started, _ := time.Parse(time.RFC3339, input.Gps.WindowStartedAt)
		metadata.CapturedAt, metadata.WindowStartedAt = captured, started
		metadata.Latitude, metadata.Longitude, metadata.AccuracyMeters = &input.Gps.Latitude, &input.Gps.Longitude, &input.Gps.AccuracyMeters
	}
	raw, err := r.Bus.Send(ctx, capturesave.Command{Input: metadata})
	if err != nil {
		return nil, err
	}
	media := raw.(database.MediaObject)
	return &graphql1.MediaPayload{Media: mapMedia(media), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// DeclareCaptureImpossibility is the resolver for the declareCaptureImpossibility field.
func (r *mutationResolver) DeclareCaptureImpossibility(ctx context.Context, input graphql1.DeclareCaptureImpossibilityInput) (*graphql1.CapturePayload, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	expected := int64(0)
	if input.ExpectedVersion != nil {
		expected = int64(*input.ExpectedVersion)
	}
	if _, err := r.Bus.Send(ctx, capturedeclare.Command{TenantID: tenantID, ResponsibilityID: responsibilityID, RequirementKey: input.RequirementKey, Reason: input.Reason, ExpectedVersion: expected}); err != nil {
		return nil, err
	}
	return &graphql1.CapturePayload{Status: "SAVED", UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// SubmitCapture is the resolver for the submitCapture field.
func (r *mutationResolver) SubmitCapture(ctx context.Context, input graphql1.SubmitCaptureInput) (*graphql1.SubmissionPayload, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	raw, err := r.Bus.Send(ctx, capturesubmit.Command{TenantID: tenantID, ResponsibilityID: responsibilityID, ConfirmIncomplete: input.ConfirmIncomplete})
	if err != nil {
		return nil, err
	}
	submission := raw.(database.SubmissionVersion)
	if writer, ok := requestctx.ResponseWriter(ctx); ok {
		http.SetCookie(writer, &http.Cookie{Name: "inspection_external", Value: "", Path: "/", MaxAge: -1, Secure: requestctx.SecureCookies(ctx), HttpOnly: true, SameSite: http.SameSiteLaxMode})
	}
	return &graphql1.SubmissionPayload{Submission: &graphql1.Submission{ID: submission.ID.String(), Complete: submission.Complete, RequiresAttention: submission.RequiresAttention, SubmittedAt: submission.SubmittedAt.Format(time.RFC3339Nano)}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// RequestRecapture is the resolver for the requestRecapture field.
func (r *mutationResolver) RequestRecapture(ctx context.Context, input graphql1.RequestRecaptureInput) (*graphql1.RecapturePayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	inspectionID, err := identity.ParseID(input.InspectionID)
	if err != nil {
		return nil, invalidID("inspectionId")
	}
	deadline, err := time.Parse(time.RFC3339, input.DeadlineAt)
	if err != nil {
		return nil, graphql1Error("deadlineAt")
	}
	items := make([]recapturecore.Item, 0, len(input.Items))
	for _, item := range input.Items {
		var original *identity.ID
		if item.OriginalMediaID != nil {
			id, e := identity.ParseID(*item.OriginalMediaID)
			if e != nil {
				return nil, invalidID("originalMediaId")
			}
			original = &id
		}
		items = append(items, recapturecore.Item{RequirementKey: item.RequirementKey, OriginalMediaID: original, Reason: item.Reason})
	}
	raw, err := r.Bus.Send(ctx, recapturerequest.Command{Input: recapturecore.RequestInput{TenantID: meta.TenantID, InspectionID: inspectionID, Items: items, DeadlineAt: deadline, IdempotencyKey: input.ClientMutationID}})
	if err != nil {
		return nil, err
	}
	created := raw.(recapturecore.Result)
	return &graphql1.RecapturePayload{Recapture: &graphql1.Recapture{ID: created.RequestID.String(), ResponsibilityID: created.ResponsibilityID.String(), Status: created.Status, DeadlineAt: &input.DeadlineAt}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// SubmitRecapture is the resolver for the submitRecapture field.
func (r *mutationResolver) SubmitRecapture(ctx context.Context, input graphql1.SubmitRecaptureInput) (*graphql1.RecapturePayload, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	requestID, err := identity.ParseID(input.RequestID)
	if err != nil {
		return nil, invalidID("requestId")
	}
	raw, err := r.Bus.Send(ctx, recapturesubmit.Command{TenantID: tenantID, ResponsibilityID: responsibilityID, RequestID: requestID, ConfirmIncomplete: input.ConfirmIncomplete})
	if err != nil {
		return nil, err
	}
	result := raw.(recapturecore.Result)
	return &graphql1.RecapturePayload{Recapture: &graphql1.Recapture{ID: result.RequestID.String(), ResponsibilityID: result.ResponsibilityID.String(), Status: result.Status}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// DeclareSensitiveDetectionFalsePositive is the resolver for the declareSensitiveDetectionFalsePositive field.
func (r *mutationResolver) DeclareSensitiveDetectionFalsePositive(ctx context.Context, input graphql1.SensitiveFalsePositiveInput) (*graphql1.MediaPayload, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	mediaID, err := identity.ParseID(input.MediaID)
	if err != nil {
		return nil, invalidID("mediaId")
	}
	raw, err := r.Bus.Send(ctx, mediafalsepositive.Command{TenantID: tenantID, ResponsibilityID: responsibilityID, MediaID: mediaID, Reason: input.Reason})
	if err != nil {
		return nil, err
	}
	media := raw.(database.MediaObject)
	return &graphql1.MediaPayload{Media: mapMedia(media), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// ConfigureRetentionPolicy is the resolver for the configureRetentionPolicy field.
func (r *mutationResolver) ConfigureRetentionPolicy(ctx context.Context, input graphql1.ConfigureRetentionPolicyInput) (*graphql1.RetentionPolicyPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager); err != nil {
		return nil, err
	}
	if input.EvidenceDays <= 0 || input.OperationalDays <= 0 || (input.SecurityDays != nil && *input.SecurityDays < 0) {
		field := "evidenceDays"
		if input.OperationalDays <= 0 {
			field = "operationalDays"
		} else if input.SecurityDays != nil && *input.SecurityDays < 0 {
			field = "securityDays"
		}
		return nil, graphql1Error(field)
	}
	securityDays := 0
	if input.SecurityDays != nil {
		securityDays = *input.SecurityDays
	}
	var row database.RetentionPolicy
	err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		var previous database.RetentionPolicy
		version := int64(1)
		if err := tx.Session(&gorm.Session{}).Order("version DESC").First(&previous).Error; err == nil {
			version = previous.Version + 1
		} else if err != gorm.ErrRecordNotFound {
			return err
		}
		now := time.Now().UTC()
		row = database.RetentionPolicy{ID: identity.NewID(), TenantID: meta.TenantID, EvidenceDays: input.EvidenceDays, OperationalDays: input.OperationalDays, SecurityDays: securityDays, Version: version, CreatedAt: now, UpdatedAt: now}
		return tx.Session(&gorm.Session{}).Create(&row).Error
	})
	if err != nil {
		return nil, err
	}
	return &graphql1.RetentionPolicyPayload{Policy: mapRetentionPolicy(row), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// RecordDeletionRequest is the resolver for the recordDeletionRequest field.
func (r *mutationResolver) RecordDeletionRequest(ctx context.Context, input graphql1.RecordDeletionRequestInput) (*graphql1.RetentionMutationPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager); err != nil {
		return nil, err
	}
	inspectionID, err := identity.ParseID(input.InspectionID)
	if err != nil {
		return nil, invalidID("inspectionId")
	}
	var row database.DeletionRequest
	if input.Reason != nil {
		row.Reason = *input.Reason
	}
	err = withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		var inspection database.Inspection
		if err := tx.Session(&gorm.Session{}).Where("id=?", inspectionID).First(&inspection).Error; err != nil {
			return err
		}
		var existing database.DeletionRequest
		if err := tx.Session(&gorm.Session{}).Where("inspection_id=? AND status IN ('REQUESTED','REFUSED')", inspectionID).Order("requested_at DESC").First(&existing).Error; err == nil {
			row = existing
			return nil
		} else if err != gorm.ErrRecordNotFound {
			return err
		}
		now := time.Now().UTC()
		row = database.DeletionRequest{ID: identity.NewID(), TenantID: meta.TenantID, InspectionID: inspectionID, Status: "REQUESTED", RequestedAt: now, Reason: row.Reason}
		return tx.Session(&gorm.Session{}).Create(&row).Error
	})
	if err != nil {
		return nil, err
	}
	id := row.ID.String()
	return &graphql1.RetentionMutationPayload{Status: row.Status, RequestID: &id, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// ApplyLegalHold is the resolver for the applyLegalHold field.
func (r *mutationResolver) ApplyLegalHold(ctx context.Context, input graphql1.LegalHoldInput) (*graphql1.RetentionMutationPayload, error) {
	return r.mutateLegalHold(ctx, input, true)
}

// ReleaseLegalHold is the resolver for the releaseLegalHold field.
func (r *mutationResolver) ReleaseLegalHold(ctx context.Context, input graphql1.LegalHoldInput) (*graphql1.RetentionMutationPayload, error) {
	return r.mutateLegalHold(ctx, input, false)
}

// ConfigurePublicationPolicy is the resolver for the configurePublicationPolicy field.
func (r *mutationResolver) ConfigurePublicationPolicy(ctx context.Context, input graphql1.ConfigurePublicationPolicyInput) (*graphql1.PublicationPolicyPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin); err != nil {
		return nil, err
	}
	mode := input.Mode
	if mode != "MANUAL" && mode != "AUTOMATIC" {
		return nil, graphql1Error("mode")
	}
	var policy database.PublicationPolicy
	err := (tenanttx.Runner{DB: r.DB}).Within(ctx, meta.TenantID, func(tx *gorm.DB) error {
		if err := tx.Where("tenant_id = ?", meta.TenantID).First(&policy).Error; err != nil && err != gorm.ErrRecordNotFound {
			return err
		}
		current := int64(0)
		if policy.ID != (identity.ID{}) {
			current = policy.Version
		}
		if int64(input.ExpectedVersion) != current {
			return apperror.New(apperror.Conflict, "expectedVersion", "stale publication policy version")
		}
		if policy.ID == (identity.ID{}) {
			policy = database.PublicationPolicy{ID: identity.NewID(), TenantID: meta.TenantID, Version: 1}
		} else {
			policy.Version++
		}
		policy.Mode = mode
		return tx.Save(&policy).Error
	})
	if err != nil {
		return nil, err
	}
	return &graphql1.PublicationPolicyPayload{Policy: &graphql1.PublicationPolicy{Mode: policy.Mode, Version: int(policy.Version)}, UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// PublishReport is the resolver for the publishReport field.
func (r *mutationResolver) PublishReport(ctx context.Context, input graphql1.PublishReportInput) (*graphql1.ReportPublicationPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager); err != nil {
		return nil, err
	}
	inspectionID, err := identity.ParseID(input.InspectionID)
	if err != nil {
		return nil, invalidID("inspectionId")
	}
	snapshotID, err := identity.ParseID(input.SnapshotID)
	if err != nil {
		return nil, invalidID("snapshotId")
	}
	publicationRow, err := r.PublicationService.Publish(ctx, publication.PublishInput{TenantID: meta.TenantID, InspectionID: inspectionID, SnapshotID: snapshotID, ActorID: meta.Principal.IdentityID, ClientMutationID: requestctx.IdempotencyKey(ctx, input.ClientMutationID), Final: true})
	if err != nil {
		return nil, err
	}
	return &graphql1.ReportPublicationPayload{Publication: mapReportPublication(publicationRow), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// InvalidateReportPublication is the resolver for the invalidateReportPublication field.
func (r *mutationResolver) InvalidateReportPublication(ctx context.Context, input graphql1.InvalidateReportPublicationInput) (*graphql1.ReportPublicationPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager); err != nil {
		return nil, err
	}
	publicationID, err := identity.ParseID(input.PublicationID)
	if err != nil {
		return nil, invalidID("publicationId")
	}
	publicationRow, err := r.PublicationService.Invalidate(ctx, publication.InvalidateInput{TenantID: meta.TenantID, PublicationID: publicationID, ActorID: meta.Principal.IdentityID, Reason: input.Reason, ExpectedVersion: int64(input.ExpectedVersion)})
	if err != nil {
		return nil, err
	}
	return &graphql1.ReportPublicationPayload{Publication: mapReportPublication(publicationRow), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, input graphql1.MarkNotificationReadInput) (*graphql1.RecipientNotificationPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager, auth.Employee, auth.Viewer, auth.CustomerViewer); err != nil {
		return nil, err
	}
	notificationID, err := identity.ParseID(input.NotificationID)
	if err != nil {
		return nil, invalidID("notificationId")
	}
	var row database.RecipientNotification
	err = withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		if err := tx.Where("tenant_id=? AND id=? AND recipient_membership_id=?", meta.TenantID, notificationID, meta.Principal.MembershipID).First(&row).Error; err != nil {
			return apperror.New(apperror.NotFound, "notificationId", "notification not found")
		}
		now := time.Now().UTC()
		if row.ReadAt == nil {
			row.ReadAt = &now
			if err := tx.Save(&row).Error; err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &graphql1.RecipientNotificationPayload{Notification: mapRecipientNotification(row), UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// ConfigureMyNotificationPreferences is the resolver for the configureMyNotificationPreferences field.
func (r *mutationResolver) ConfigureMyNotificationPreferences(ctx context.Context, input graphql1.ConfigureNotificationPreferencesInput) (*graphql1.NotificationPreferencesPayload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager, auth.Employee, auth.Viewer, auth.CustomerViewer); err != nil {
		return nil, err
	}
	selected := make(map[identity.ID]bool, len(input.Channels))
	for _, value := range input.Channels {
		id, parseErr := identity.ParseID(value)
		if parseErr != nil {
			return nil, invalidID("channels")
		}
		selected[id] = true
	}
	err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		var channels []database.RecipientChannel
		if err := tx.Where("tenant_id=? AND recipient_membership_id=?", meta.TenantID, meta.Principal.MembershipID).Find(&channels).Error; err != nil {
			return err
		}
		for _, channel := range channels {
			if channel.Version != int64(input.ExpectedVersion) && input.ExpectedVersion != 0 {
				return apperror.New(apperror.Conflict, "expectedVersion", "stale notification preferences")
			}
		}
		for _, channel := range channels {
			if err := tx.Model(&database.RecipientChannel{}).Where("tenant_id=? AND id=?", meta.TenantID, channel.ID).Updates(map[string]any{"selected": selected[channel.ID], "version": channel.Version + 1, "updated_at": time.Now().UTC()}).Error; err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &graphql1.NotificationPreferencesPayload{UserErrors: []*graphql1.UserError{}, ClientMutationID: input.ClientMutationID}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*graphql1.Me, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, nil
	}
	principal := meta.Principal
	if r.Authorizer.Store != nil && meta.TenantID != (identity.ID{}) && principal.IdentityID != (identity.ID{}) {
		resolved, err := r.Authorizer.Store.Resolve(ctx, meta.TenantID, principal.IdentityID)
		if err != nil {
			return nil, err
		}
		principal = resolved
	}
	scopes := make([]*graphql1.Scope, 0, len(principal.Scopes))
	for _, scope := range principal.Scopes {
		scopes = append(scopes, &graphql1.Scope{Kind: scope.Kind, ResourceID: scope.ID.String()})
	}
	memberships := []*graphql1.Membership{}
	if principal.MembershipID != (identity.ID{}) {
		memberships = append(memberships, &graphql1.Membership{ID: principal.MembershipID.String(), TenantID: principal.TenantID.String(), Role: firstRole(principal.Roles), Status: membershipStatus(principal.Disabled), Version: int(principal.MembershipVersion), Scopes: scopes})
	}
	return &graphql1.Me{
		IdentityID: principal.IdentityID.String(), TenantID: principal.TenantID.String(), Audience: principal.Audience, Product: principal.Product, ProductEntitlements: principal.ProductEntitlements, Roles: principal.Roles,
		Memberships:     memberships,
		EffectiveScopes: scopes,
	}, nil
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context) (*graphql1.Tenant, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if meta.TenantID == (identity.ID{}) {
		return nil, nil
	}
	var row database.Tenant
	err := (tenanttx.Runner{DB: r.DB}).Within(ctx, meta.TenantID, func(tx *gorm.DB) error { return tx.Where("tenant_id=?", meta.TenantID).First(&row).Error })
	if err != nil {
		return nil, err
	}
	return &graphql1.Tenant{ID: row.ID.String(), Name: row.Name, Language: row.Language, DefaultTimezone: row.DefaultTimezone, Status: row.Status, Version: int(row.Version)}, nil
}

// Memberships is the resolver for the memberships field.
func (r *queryResolver) Memberships(ctx context.Context, first *int, after *string) (*graphql1.MembershipConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager); err != nil {
		return nil, err
	}
	limit := intValue(first)
	if limit <= 0 || limit > 100 {
		limit = 25
	}
	var rows []database.Membership
	err := (tenanttx.Runner{DB: r.DB}).Within(ctx, meta.TenantID, func(tx *gorm.DB) error {
		query := tx.Where("tenant_id = ?", meta.TenantID)
		if after != nil && *after != "" {
			cursor, parseErr := identity.ParseID(*after)
			if parseErr != nil {
				return invalidID("after")
			}
			query = query.Where("id > ?", cursor)
		}
		return query.Order("id ASC").Limit(limit + 1).Find(&rows).Error
	})
	if err != nil {
		return nil, err
	}
	hasNext := len(rows) > limit
	if hasNext {
		rows = rows[:limit]
	}
	nodes := make([]*graphql1.Membership, 0, len(rows))
	for _, row := range rows {
		mapped, mapErr := mapMembership(ctx, r.DB, row)
		if mapErr != nil {
			return nil, mapErr
		}
		nodes = append(nodes, mapped)
	}
	end := ""
	if len(rows) > 0 {
		end = rows[len(rows)-1].ID.String()
	}
	return &graphql1.MembershipConnection{Nodes: nodes, PageInfo: pageInfo(end, hasNext)}, nil
}

// BusinessUnits is the resolver for the businessUnits field.
func (r *queryResolver) BusinessUnits(ctx context.Context, first *int, after *string) (*graphql1.BusinessUnitConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager, auth.Employee, auth.Viewer); err != nil {
		return nil, err
	}
	limit := intValue(first)
	if limit <= 0 || limit > 100 {
		limit = 25
	}
	var rows []database.BusinessUnit
	if err := (tenanttx.Runner{DB: r.DB}).Within(ctx, meta.TenantID, func(tx *gorm.DB) error {
		query := tx.Where("tenant_id=?", meta.TenantID)
		if cursor := stringValue(after); cursor != "" {
			query = query.Where("code > ?", cursor)
		}
		return query.Order("code ASC").Limit(limit + 1).Find(&rows).Error
	}); err != nil {
		return nil, err
	}
	hasNext := len(rows) > limit
	if hasNext {
		rows = rows[:limit]
	}
	nodes := make([]*graphql1.BusinessUnit, 0, len(rows))
	for _, row := range rows {
		nodes = append(nodes, &graphql1.BusinessUnit{ID: row.ID.String(), Code: row.Code, Name: row.Name, Status: row.Status, Version: int(row.Version)})
	}
	endCursor := ""
	if len(rows) > 0 {
		endCursor = rows[len(rows)-1].Code
	}
	return &graphql1.BusinessUnitConnection{Nodes: nodes, PageInfo: pageInfo(endCursor, hasNext)}, nil
}

// AuditEvents is the resolver for the auditEvents field.
func (r *queryResolver) AuditEvents(ctx context.Context, first *int, after *string) (*graphql1.AuditEventConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	raw, err := r.Bus.Ask(ctx, listaudit.Query{TenantID: meta.TenantID, First: intValue(first), After: stringValue(after)})
	if err != nil {
		return nil, err
	}
	result := raw.(listaudit.Result)
	nodes := make([]*graphql1.AuditEvent, 0, len(result.Events))
	for _, event := range result.Events {
		reason := event.Reason
		nodes = append(nodes, &graphql1.AuditEvent{ID: event.ID.String(), Action: event.Action, TargetType: event.TargetType, TargetID: event.TargetID, Outcome: event.Outcome, Reason: &reason, CorrelationID: event.CorrelationID, OccurredAt: event.OccurredAt.Format(time.RFC3339Nano)})
	}
	return &graphql1.AuditEventConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// Participants is the resolver for the participants field.
func (r *queryResolver) Participants(ctx context.Context, search *string, first *int, after *string) (*graphql1.ParticipantConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	raw, err := r.Bus.Ask(ctx, participantlist.Query{TenantID: meta.TenantID, Search: stringValue(search), First: intValue(first), After: stringValue(after)})
	if err != nil {
		return nil, err
	}
	result := raw.(participantlist.Result)
	nodes := make([]*graphql1.Participant, 0, len(result.Participants))
	for _, v := range result.Participants {
		nodes = append(nodes, mapParticipant(v))
	}
	return &graphql1.ParticipantConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// Participant is the resolver for the participant field.
func (r *queryResolver) Participant(ctx context.Context, id string) (*graphql1.Participant, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	parsed, err := identity.ParseID(id)
	if err != nil {
		return nil, invalidID("id")
	}
	raw, err := r.Bus.Ask(ctx, participantget.Query{TenantID: meta.TenantID, ParticipantID: parsed})
	if err != nil {
		return nil, err
	}
	return mapParticipant(raw.(participantcore.ParticipantView)), nil
}

// SegmentDefinitions is the resolver for the segmentDefinitions field.
func (r *queryResolver) SegmentDefinitions(ctx context.Context, search *string, first *int, after *string) (*graphql1.SegmentDefinitionConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	raw, err := r.Bus.Ask(ctx, segmentlist.Query{TenantID: meta.TenantID, Search: stringValue(search), First: intValue(first), After: stringValue(after)})
	if err != nil {
		return nil, err
	}
	result := raw.(segmentlist.Result)
	nodes := make([]*graphql1.SegmentDefinition, 0, len(result.Definitions))
	for _, v := range result.Definitions {
		nodes = append(nodes, mapSegment(v.Definition))
	}
	return &graphql1.SegmentDefinitionConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context, search *string, first *int, after *string) (*graphql1.TemplateConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	raw, err := r.Bus.Ask(ctx, templatelist.Query{TenantID: meta.TenantID, Search: stringValue(search), First: intValue(first), After: stringValue(after)})
	if err != nil {
		return nil, err
	}
	result := raw.(templatelist.Result)
	nodes := make([]*graphql1.Template, 0, len(result.Templates))
	for _, v := range result.Templates {
		nodes = append(nodes, mapTemplate(v.Template))
	}
	return &graphql1.TemplateConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// TemplateVersion is the resolver for the templateVersion field.
func (r *queryResolver) TemplateVersion(ctx context.Context, id string) (*graphql1.TemplateVersion, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	parsed, err := identity.ParseID(id)
	if err != nil {
		return nil, invalidID("id")
	}
	raw, err := r.Bus.Ask(ctx, templatelist.VersionQuery{TenantID: meta.TenantID, VersionID: parsed})
	if err != nil {
		return nil, err
	}
	return mapTemplateVersion(raw.(templatecore.View).Version), nil
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, businessUnitID *string, search *string, first *int, after *string) (*graphql1.AssetConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	var unitID *identity.ID
	if businessUnitID != nil {
		parsed, err := identity.ParseID(*businessUnitID)
		if err != nil {
			return nil, invalidID("businessUnitId")
		}
		unitID = &parsed
	}
	raw, err := r.Bus.Ask(ctx, assetlist.Query{TenantID: meta.TenantID, BusinessUnitID: unitID, Search: stringValue(search), First: intValue(first), After: stringValue(after)})
	if err != nil {
		return nil, err
	}
	result := raw.(assetlist.Result)
	nodes := make([]*graphql1.Asset, 0, len(result.Assets))
	for _, v := range result.Assets {
		nodes = append(nodes, mapAsset(v))
	}
	return &graphql1.AssetConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// Asset is the resolver for the asset field.
func (r *queryResolver) Asset(ctx context.Context, id string) (*graphql1.Asset, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	parsed, err := identity.ParseID(id)
	if err != nil {
		return nil, invalidID("id")
	}
	raw, err := r.Bus.Ask(ctx, assetget.Query{TenantID: meta.TenantID, AssetID: parsed})
	if err != nil {
		return nil, err
	}
	return mapAsset(raw.(assetcore.View)), nil
}

// OriginVersions is the resolver for the originVersions field.
func (r *queryResolver) OriginVersions(ctx context.Context, assetID string, first *int, after *string) (*graphql1.OriginVersionConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(assetID)
	if err != nil {
		return nil, invalidID("assetId")
	}
	if _, err := r.Bus.Ask(ctx, assetget.Query{TenantID: meta.TenantID, AssetID: id}); err != nil {
		return nil, err
	}
	raw, err := r.Bus.Ask(ctx, originlist.Query{TenantID: meta.TenantID, AssetID: id, First: intValue(first), After: stringValue(after)})
	if err != nil {
		return nil, err
	}
	result := raw.(originlist.Result)
	nodes := make([]*graphql1.OriginVersion, 0, len(result.Versions))
	for _, row := range result.Versions {
		nodes = append(nodes, mapOriginVersion(row))
	}
	return &graphql1.OriginVersionConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// Schedules is the resolver for the schedules field.
func (r *queryResolver) Schedules(ctx context.Context, first *int, after *string) (*graphql1.ScheduleConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	result, err := r.ScheduleService.List(ctx, meta.TenantID, intValue(first), stringValue(after))
	if err != nil {
		return nil, err
	}
	nodes := make([]*graphql1.Schedule, 0, len(result.Schedules))
	for _, row := range result.Schedules {
		nodes = append(nodes, mapSchedule(row))
	}
	return &graphql1.ScheduleConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, first *int, after *string) (*graphql1.ProjectConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	result, err := r.ProjectService.List(ctx, meta.TenantID, intValue(first), stringValue(after))
	if err != nil {
		return nil, err
	}
	nodes := make([]*graphql1.Project, 0, len(result.Items))
	for _, row := range result.Items {
		nodes = append(nodes, mapProject(row))
	}
	return &graphql1.ProjectConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*graphql1.Project, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	projectID, err := identity.ParseID(id)
	if err != nil {
		return nil, invalidID("id")
	}
	view, err := r.ProjectService.Get(ctx, meta.TenantID, projectID)
	if err != nil {
		return nil, err
	}
	return mapProject(view), nil
}

// Inspections is the resolver for the inspections field.
func (r *queryResolver) Inspections(ctx context.Context, first *int, after *string, history *bool) (*graphql1.InspectionConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	includeHistory := false
	if history != nil {
		includeHistory = *history
	}
	result, err := r.InspectionService.List(ctx, inspectioncore.ListInput{TenantID: meta.TenantID, First: intValue(first), After: stringValue(after), History: includeHistory})
	if err != nil {
		return nil, err
	}
	nodes := make([]*graphql1.Inspection, 0, len(result.Items))
	for _, row := range result.Items {
		nodes = append(nodes, mapInspection(row))
	}
	return &graphql1.InspectionConnection{Nodes: nodes, PageInfo: pageInfo(result.EndCursor, result.HasNextPage)}, nil
}

// Inspection is the resolver for the inspection field.
func (r *queryResolver) Inspection(ctx context.Context, id string) (*graphql1.Inspection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	inspectionID, err := identity.ParseID(id)
	if err != nil {
		return nil, invalidID("id")
	}
	view, err := r.InspectionService.Get(ctx, meta.TenantID, inspectionID)
	if err != nil {
		return nil, err
	}
	return mapInspection(view), nil
}

// Report is the resolver for the report field.
func (r *queryResolver) Report(ctx context.Context, inspectionID string, version *int) (*graphql1.Report, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(inspectionID)
	if err != nil {
		return nil, invalidID("inspectionId")
	}
	var row database.ReportSnapshot
	if err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		query := tx.Where("inspection_id=?", id).Order("version_number DESC")
		if version != nil {
			query = query.Where("version_number=?", *version)
		}
		return query.First(&row).Error
	}); err != nil {
		return nil, err
	}
	return mapReport(row), nil
}

// ReportDownload is the resolver for the reportDownload field.
func (r *queryResolver) ReportDownload(ctx context.Context, snapshotID string, kind *string) (*graphql1.ReportDownload, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(snapshotID)
	if err != nil {
		return nil, invalidID("snapshotId")
	}
	value := "PDF"
	if kind != nil && *kind != "" {
		value = *kind
	}
	var row database.ReportArtifact
	if err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		return tx.Where("snapshot_id=? AND kind=?", id, value).First(&row).Error
	}); err != nil {
		return nil, err
	}
	url := ""
	if r.Store.Client != nil {
		if signed, signErr := r.Store.PresignGet(ctx, row.ObjectKey, 5*time.Minute); signErr == nil {
			url = signed
		}
	}
	return &graphql1.ReportDownload{SnapshotID: row.SnapshotID.String(), Kind: row.Kind, ObjectKey: "", Status: row.Status, URL: url, Sha256: strptr(row.SHA256)}, nil
}

// DashboardSummary is the resolver for the dashboardSummary field.
func (r *queryResolver) DashboardSummary(ctx context.Context, projectID *string, businessUnitID *string) (*graphql1.DashboardSummary, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	var rows []database.DashboardInspection
	err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		query := tx
		if projectID != nil {
			id, err := identity.ParseID(*projectID)
			if err != nil {
				return invalidID("projectId")
			}
			query = query.Where("project_id=?", id)
		}
		if businessUnitID != nil {
			id, err := identity.ParseID(*businessUnitID)
			if err != nil {
				return invalidID("businessUnitId")
			}
			query = query.Joins("JOIN inspections.inspections i ON i.id=dashboard.inspections.inspection_id AND i.tenant_id=dashboard.inspections.tenant_id").Where("i.business_unit_id=?", id)
		}
		return query.Find(&rows).Error
	})
	if err != nil {
		return nil, err
	}
	result := &graphql1.DashboardSummary{}
	for _, row := range rows {
		result.Total++
		if row.Invalidated {
			result.Invalidated++
			continue
		}
		switch row.Classification {
		case "NORMAL":
			result.Normal++
		case "CRITICAL":
			result.Critical++
		case "ATTENTION":
			result.Attention++
		}
		if row.Status != "COMPLETED" {
			result.Pending++
		}
	}
	return result, nil
}

// TriageInspections is the resolver for the triageInspections field.
func (r *queryResolver) TriageInspections(ctx context.Context, first *int, after *string, classification *string, status *string) (*graphql1.TriageInspectionConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	limit := intValue(first)
	if limit <= 0 {
		limit = 25
	}
	if limit > 100 {
		limit = 100
	}
	if classification != nil && *classification != "" && *classification != "NORMAL" && *classification != "ATTENTION" && *classification != "CRITICAL" {
		return nil, graphql1Error("classification")
	}
	var rows []database.DashboardInspection
	err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		query := tx.Where("invalidated=false")
		if after != nil && *after != "" {
			cursorBucket, cursorTime, cursorID, err := dashboardcore.DecodeTriageCursor(*after)
			if err != nil {
				// Accept the original timestamp/id cursor format for clients that
				// started paging before risk-priority cursors were introduced.
				legacyTime, legacyID, legacyErr := dashboardcore.DecodeCursor(*after)
				if legacyErr != nil {
					return invalidID("after")
				}
				cursorBucket, cursorTime, cursorID = 0, legacyTime, legacyID
			}
			prioritySQL := "CASE classification WHEN 'CRITICAL' THEN 0 WHEN 'ATTENTION' THEN 1 ELSE 2 END"
			query = query.Where("("+prioritySQL+" > ?) OR ("+prioritySQL+" = ? AND ((updated_at < ?) OR (updated_at = ? AND inspection_id < ?)))", cursorBucket, cursorBucket, cursorTime, cursorTime, cursorID)
		}
		if classification != nil && *classification != "" {
			query = query.Where("classification=?", *classification)
		}
		if status != nil && *status != "" {
			query = query.Where("status=?", *status)
		}
		return query.Order("CASE classification WHEN 'CRITICAL' THEN 0 WHEN 'ATTENTION' THEN 1 ELSE 2 END ASC, updated_at DESC, inspection_id DESC").Limit(limit + 1).Find(&rows).Error
	})
	if err != nil {
		return nil, err
	}
	hasNext := len(rows) > limit
	if hasNext {
		rows = rows[:limit]
	}
	nodes := make([]*graphql1.TriageInspection, 0, len(rows))
	for _, row := range rows {
		nodes = append(nodes, mapTriage(row))
	}
	end := ""
	if len(rows) > 0 {
		last := rows[len(rows)-1]
		end = dashboardcore.EncodeTriageCursor(dashboardcore.Projection{InspectionID: last.InspectionID.String(), Classification: last.Classification, UpdatedAt: last.UpdatedAt})
	}
	return &graphql1.TriageInspectionConnection{Nodes: nodes, PageInfo: pageInfo(end, hasNext)}, nil
}

// ProjectTimeline is the resolver for the projectTimeline field.
func (r *queryResolver) ProjectTimeline(ctx context.Context, projectID string) (*graphql1.ProjectTimeline, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	id, err := identity.ParseID(projectID)
	if err != nil {
		return nil, invalidID("projectId")
	}
	var rows []database.ProjectStage
	if err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		return tx.Where("project_id=?", id).Order("position ASC").Find(&rows).Error
	}); err != nil {
		return nil, err
	}
	entries := make([]*graphql1.ProjectTimelineEntry, 0, len(rows))
	for _, row := range rows {
		var inspection *string
		if row.InspectionID != nil {
			value := row.InspectionID.String()
			inspection = &value
		}
		entries = append(entries, &graphql1.ProjectTimelineEntry{StageID: row.ID.String(), Label: row.Label, Status: row.Status, InspectionID: inspection})
	}
	return &graphql1.ProjectTimeline{ProjectID: id.String(), Entries: entries}, nil
}

// NotificationDeliveries is the resolver for the notificationDeliveries field.
func (r *queryResolver) NotificationDeliveries(ctx context.Context, first *int, after *string) (*graphql1.NotificationDeliveryConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	limit := intValue(first)
	if limit <= 0 {
		limit = 25
	}
	if limit > 100 {
		limit = 100
	}
	var rows []database.Delivery
	err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		query := tx
		if after != nil && *after != "" {
			cursorTime, cursorID, err := dashboardcore.DecodeCursor(*after)
			if err != nil {
				return invalidID("after")
			}
			query = query.Where("(created_at < ?) OR (created_at = ? AND id < ?)", cursorTime, cursorTime, cursorID)
		}
		return query.Order("created_at DESC, id DESC").Limit(limit + 1).Find(&rows).Error
	})
	if err != nil {
		return nil, err
	}
	hasNext := len(rows) > limit
	if hasNext {
		rows = rows[:limit]
	}
	nodes := make([]*graphql1.NotificationDelivery, 0, len(rows))
	for _, row := range rows {
		nodes = append(nodes, &graphql1.NotificationDelivery{ID: row.ID.String(), IntentID: row.IntentID.String(), Status: row.Status, CreatedAt: row.CreatedAt.Format(time.RFC3339Nano), UpdatedAt: row.UpdatedAt.Format(time.RFC3339Nano)})
	}
	end := ""
	if len(rows) > 0 {
		last := rows[len(rows)-1]
		end = dashboardcore.EncodeCursor(dashboardcore.Projection{InspectionID: last.ID.String(), UpdatedAt: last.CreatedAt})
	}
	return &graphql1.NotificationDeliveryConnection{Nodes: nodes, PageInfo: pageInfo(end, hasNext)}, nil
}

// PublicationPolicy is the resolver for the publicationPolicy field.
func (r *queryResolver) PublicationPolicy(ctx context.Context) (*graphql1.PublicationPolicy, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager, auth.Employee, auth.Viewer, auth.CustomerViewer); err != nil {
		return nil, err
	}
	var policy database.PublicationPolicy
	err := (tenanttx.Runner{DB: r.DB}).Within(ctx, meta.TenantID, func(tx *gorm.DB) error { return tx.Where("tenant_id = ?", meta.TenantID).First(&policy).Error })
	if err == gorm.ErrRecordNotFound {
		return &graphql1.PublicationPolicy{Mode: "MANUAL", Version: 0}, nil
	}
	if err != nil {
		return nil, err
	}
	return &graphql1.PublicationPolicy{Mode: policy.Mode, Version: int(policy.Version)}, nil
}

// CustomerPortfolio is the resolver for the customerPortfolio field.
func (r *queryResolver) CustomerPortfolio(ctx context.Context, filter *graphql1.CustomerPortfolioFilter, first *int, after *string) (*graphql1.CustomerPortfolioConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.Manager, auth.Employee, auth.Viewer, auth.CustomerViewer); err != nil {
		return nil, err
	}
	return &graphql1.CustomerPortfolioConnection{Nodes: []*graphql1.CustomerPortfolioItem{}, PageInfo: pageInfo("", false)}, nil
}

// CustomerTimeline is the resolver for the customerTimeline field.
func (r *queryResolver) CustomerTimeline(ctx context.Context, assetID *string, projectID *string, first *int, after *string) (*graphql1.CustomerTimelineConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.Manager, auth.Employee, auth.Viewer, auth.CustomerViewer); err != nil {
		return nil, err
	}
	return &graphql1.CustomerTimelineConnection{Nodes: []*graphql1.CustomerTimelineEntry{}, PageInfo: pageInfo("", false)}, nil
}

// CustomerReport is the resolver for the customerReport field.
func (r *queryResolver) CustomerReport(ctx context.Context, inspectionID string, version *int) (*graphql1.CustomerReport, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.Manager, auth.Employee, auth.Viewer, auth.CustomerViewer); err != nil {
		return nil, err
	}
	return nil, nil
}

// CustomerEvidence is the resolver for the customerEvidence field.
func (r *queryResolver) CustomerEvidence(ctx context.Context, inspectionID string, mode *graphql1.EvidenceMode, first *int, after *string) (*graphql1.CustomerEvidenceConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.Manager, auth.Employee, auth.Viewer, auth.CustomerViewer); err != nil {
		return nil, err
	}
	return &graphql1.CustomerEvidenceConnection{Nodes: []*graphql1.CustomerEvidenceItem{}, PageInfo: pageInfo("", false)}, nil
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context, unreadOnly *bool, first *int, after *string) (*graphql1.RecipientNotificationConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager, auth.Employee, auth.Viewer, auth.CustomerViewer); err != nil {
		return nil, err
	}
	if r.DB == nil {
		return &graphql1.RecipientNotificationConnection{Nodes: []*graphql1.RecipientNotification{}, PageInfo: pageInfo("", false), UnreadCount: 0}, nil
	}
	limit := intValue(first)
	if limit <= 0 {
		limit = 25
	}
	if limit > 100 {
		limit = 100
	}
	var rows []database.RecipientNotification
	err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		query := tx.Where("tenant_id=? AND recipient_membership_id=?", meta.TenantID, meta.Principal.MembershipID)
		if unreadOnly != nil && *unreadOnly {
			query = query.Where("read_at IS NULL")
		}
		if after != nil && *after != "" {
			cursorTime, cursorID, err := dashboardcore.DecodeCursor(*after)
			if err != nil {
				return invalidID("after")
			}
			query = query.Where("(created_at < ?) OR (created_at = ? AND id < ?)", cursorTime, cursorTime, cursorID)
		}
		return query.Order("created_at DESC, id DESC").Limit(limit + 1).Find(&rows).Error
	})
	if err != nil {
		return nil, err
	}
	var unread int64
	if err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		return tx.Model(&database.RecipientNotification{}).Where("tenant_id=? AND recipient_membership_id=? AND read_at IS NULL", meta.TenantID, meta.Principal.MembershipID).Count(&unread).Error
	}); err != nil {
		return nil, err
	}
	hasNext := len(rows) > limit
	if hasNext {
		rows = rows[:limit]
	}
	nodes := make([]*graphql1.RecipientNotification, 0, len(rows))
	for _, row := range rows {
		nodes = append(nodes, mapRecipientNotification(row))
	}
	end := ""
	if len(rows) > 0 {
		last := rows[len(rows)-1]
		end = dashboardcore.EncodeCursor(dashboardcore.Projection{InspectionID: last.ID.String(), UpdatedAt: last.CreatedAt})
	}
	return &graphql1.RecipientNotificationConnection{Nodes: nodes, PageInfo: pageInfo(end, hasNext), UnreadCount: int(unread)}, nil
}

// RetentionPolicies is the resolver for the retentionPolicies field.
func (r *queryResolver) RetentionPolicies(ctx context.Context) (*graphql1.RetentionPolicyConnection, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager); err != nil {
		return nil, err
	}
	var rows []database.RetentionPolicy
	if err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		return tx.Order("created_at DESC").Find(&rows).Error
	}); err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		defaults := retentioncore.DefaultPolicy()
		rows = []database.RetentionPolicy{{EvidenceDays: int(defaults.EvidenceReports / (24 * time.Hour)), OperationalDays: int(defaults.Operational / (24 * time.Hour)), SecurityDays: 0, Version: 1}}
	}
	nodes := make([]*graphql1.RetentionPolicy, 0, len(rows))
	for _, row := range rows {
		nodes = append(nodes, mapRetentionPolicy(row))
	}
	return &graphql1.RetentionPolicyConnection{Nodes: nodes, PageInfo: pageInfo("", false)}, nil
}

// UsageSummary is the resolver for the usageSummary field.
func (r *queryResolver) UsageSummary(ctx context.Context, from *string, to *string) (*graphql1.UsageSummary, error) {
	meta, ok := requestctx.FromContext(ctx)
	if !ok {
		return nil, unauthenticated()
	}
	if err := internalRole(meta, auth.TenantAdmin, auth.Manager); err != nil {
		return nil, err
	}
	start := time.Now().UTC().AddDate(0, 0, -30)
	end := time.Now().UTC()
	if from != nil {
		if parsed, err := time.Parse(time.RFC3339, *from); err == nil {
			start = parsed
		} else {
			return nil, graphql1Error("from")
		}
	}
	if to != nil {
		if parsed, err := time.Parse(time.RFC3339, *to); err == nil {
			end = parsed
		} else {
			return nil, graphql1Error("to")
		}
	}
	var row struct {
		Requests     int64
		InputTokens  int64
		OutputTokens int64
		Cost         float64
	}
	if err := withTask06Tenant(ctx, r.DB, meta.TenantID, func(tx *gorm.DB) error {
		return tx.Model(&database.UsageRecord{}).Select("count(*) as requests, coalesce(sum(input_tokens),0) as input_tokens, coalesce(sum(output_tokens),0) as output_tokens, coalesce(sum(cost),0) as cost").Where("created_at>=? AND created_at<?", start, end).Scan(&row).Error
	}); err != nil {
		return nil, err
	}
	return &graphql1.UsageSummary{From: start.Format(time.RFC3339Nano), To: end.Format(time.RFC3339Nano), Requests: int(row.Requests), InputTokens: int(row.InputTokens), OutputTokens: int(row.OutputTokens), Cost: row.Cost}, nil
}

// ExternalCapture is the resolver for the externalCapture field.
func (r *queryResolver) ExternalCapture(ctx context.Context) (*graphql1.ExternalCapture, error) {
	tenantID, responsibilityID, err := r.externalResponsibility(ctx)
	if err != nil {
		return nil, err
	}
	raw, err := r.Bus.Ask(ctx, capturebootstrap.Query{TenantID: tenantID, ResponsibilityID: responsibilityID})
	if err != nil {
		return nil, err
	}
	view := raw.(capturecore.Bootstrap)
	reference, policy := map[string]any{}, map[string]any{}
	_ = json.Unmarshal(view.Draft.ReferencePayload, &reference)
	_ = json.Unmarshal(view.Draft.PolicyPayload, &policy)
	response := &graphql1.ExternalCapture{ResponsibilityID: responsibilityID.String(), Status: view.Draft.Status, ConfirmationOnly: view.ConfirmationOnly, Kind: view.Draft.Kind, TemplateVersionID: view.Draft.TemplateVersionID.String(), Reference: reference, Policy: policy, Requirements: []*graphql1.CaptureRequirement{}, Answers: []*graphql1.CaptureAnswer{}, DisclosureVersion: invitationcore.PrivacyDisclosureVersion}
	if view.Draft.Kind == "RECAPTURE" {
		var request database.RecaptureRequest
		if err := (tenanttx.Runner{DB: r.DB}).Within(ctx, tenantID, func(tx *gorm.DB) error {
			return tx.Where("tenant_id=? AND responsibility_id=?", tenantID, responsibilityID).First(&request).Error
		}); err != nil {
			return nil, err
		}
		requestID := request.ID.String()
		response.RecaptureRequestID = &requestID
	}
	if view.ConfirmationOnly {
		response.Status = "CONFIRMED"
		return response, nil
	}
	accepted, err := r.Invitations.HasProcessingAcceptance(ctx, tenantID, responsibilityID)
	if err != nil {
		return nil, err
	}
	if !accepted {
		response.Status = "ACCEPTANCE_REQUIRED"
		return response, nil
	}
	requirements := make([]*graphql1.CaptureRequirement, 0, len(view.Requirements))
	for _, req := range view.Requirements {
		var instructions *string
		if req.Instructions != "" {
			value := req.Instructions
			instructions = &value
		}
		requirements = append(requirements, &graphql1.CaptureRequirement{
			Key: req.Key, Section: req.Section, Label: req.Label, Instructions: instructions,
			EvidenceKind: req.EvidenceKind, Required: req.Required,
			MinimumMedia: req.MinimumMedia, MaximumMedia: req.MaximumMedia,
			DescriptionRequired:  req.DescriptionRequired,
			CaptureSourcePolicy:  req.CaptureSourcePolicy,
			ComparisonTarget:     req.ComparisonTarget,
			ImpossibilityAllowed: req.ImpossibilityAllowed,
		})
	}
	answers := make([]*graphql1.CaptureAnswer, 0, len(view.Answers))
	for _, row := range view.Answers {
		var ids []identity.ID
		_ = json.Unmarshal(row.MediaIDs, &ids)
		mapped := make([]string, 0, len(ids))
		for _, id := range ids {
			mapped = append(mapped, id.String())
		}
		reason := row.ImpossibilityReason
		answers = append(answers, &graphql1.CaptureAnswer{RequirementKey: row.RequirementKey, MediaIds: mapped, ImpossibilityReason: &reason, Version: int(row.Version)})
	}
	status := view.Draft.Status
	if view.ConfirmationOnly {
		status = "CONFIRMED"
	}
	response.Status, response.Requirements, response.Answers = status, requirements, answers
	return response, nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
