# deploy/litellm/config.yaml
model_list:
  - model_name: inspection-vision
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key: os.environ/LLM_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

#gemini-3-flash-preview
#gemini/gemini-3.6-flash

