"use client";

import { type ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { clearCaptureCsrfToken, clearCaptureLinkToken, getCaptureLinkToken, setCaptureCsrfToken, setCaptureLinkToken } from "@/auth/capture-session";
import { RegisterServiceWorker } from "@/components/register-service-worker";
import { Icon } from "@inspection/design-system";
import { captureOperations, graphql, isCaptureSessionFailure } from "@/graphql/client";
import type { ExternalCaptureBootstrapQuery } from "@/graphql/generated";
import { type CaptureDraft, digest, hasDuplicateDraft, loadDraftsForResponsibility, mediaCountForRequirement, persistDraftMediaStatus, readyForSubmission, removeDraft, removeDraftsForResponsibility, saveDraft } from "@/pwa/drafts";
import { prepareCaptureImage } from "@/pwa/prepare-image";
import { type UploadProgress, uploadDraft } from "@/pwa/uploads";
import { throwOnUserErrors } from "@/pwa/mutation-errors";
import { buildImpossibilityInput, isBlockedMediaStatus, isFalsePositiveActionable, isTerminalBootstrapStatus, mergeUploadedAnswer, requirementsSatisfied, updateImpossibleAnswer } from "@/pwa/capture-policy";
import { guidedProgress, guidedRequirements, nextGuidedRequirement, requirementState } from "@/pwa/guided-flow";
import { presentMediaFeedback, presentMediaStatus, presentRequirementLabel, presentRequirementSection, presentSubmissionBlock, presentUploadFailure } from "./presentation";

type Props = { params: Promise<{ linkToken: string }> };
type Stage = "otp" | "consent" | "capture" | "review" | "confirmation" | "unavailable";
type ConsentChoices = { photoProcessing: boolean; aiAnalysis: boolean; gpsUse: boolean };
type ReferenceItem = ExternalCaptureBootstrapQuery["externalCapture"]["referenceItems"][number];
type PhotoPreview = { file: File; url: string; requirementKey: string; capturedAt: string; sourceSha256: string; imageProfile: string };
const mutationID = (): string => crypto.randomUUID();
const booleanValue = (value: unknown): boolean | undefined => typeof value === "boolean" ? value : undefined;


export default function CapturePage({ params }: Props) {
  const [stage, setStage] = useState<Stage>("otp"); const [token, setToken] = useState(""); const [code, setCode] = useState(""); const [notice, setNotice] = useState("");
  const [responsibilityId, setResponsibilityId] = useState(""); const [recaptureRequestId, setRecaptureRequestId] = useState<string>(); const [kind, setKind] = useState(""); const [confirmationOnly, setConfirmationOnly] = useState(false); const [disclosureVersion, setDisclosureVersion] = useState(""); const [policy, setPolicy] = useState<ExternalCaptureBootstrapQuery["externalCapture"]["policy"]>({}); const [requirements, setRequirements] = useState<ExternalCaptureBootstrapQuery["externalCapture"]["requirements"]>([]); const [answers, setAnswers] = useState<ExternalCaptureBootstrapQuery["externalCapture"]["answers"]>([]); const [selected, setSelected] = useState(""); const [drafts, setDrafts] = useState<CaptureDraft[]>([]); const [uploadingDraftId, setUploadingDraftId] = useState<string>(); const [description, setDescription] = useState(""); const [descriptionOpen, setDescriptionOpen] = useState(false); const [reason, setReason] = useState(""); const [reasonOpen, setReasonOpen] = useState(false); const [falsePositiveMediaId, setFalsePositiveMediaId] = useState(""); const [falsePositiveReason, setFalsePositiveReason] = useState(""); const [consentChoices, setConsentChoices] = useState<ConsentChoices>({ photoProcessing: false, aiAnalysis: false, gpsUse: false }); const [online, setOnline] = useState(true); const [busy, setBusy] = useState(false);
  const [comparisonMode, setComparisonMode] = useState(""); const [referenceItems, setReferenceItems] = useState<ReferenceItem[]>([]); const [failedReferences, setFailedReferences] = useState<string[]>([]); const [referenceAttempts, setReferenceAttempts] = useState<Record<string, number>>({}); const [referenceLoading, setReferenceLoading] = useState(false); const [expandedReference, setExpandedReference] = useState(false); const [preview, setPreview] = useState<PhotoPreview>();
  const cameraInputRef = useRef<HTMLInputElement>(null);
  const [uploadProgress, setUploadProgress] = useState<Record<string, UploadProgress>>({});
  const refresh = async (scope = responsibilityId): Promise<CaptureDraft[]> => { if (!scope) return []; const loaded = await loadDraftsForResponsibility(scope); setDrafts(loaded); return loaded; };
  const pending = useMemo(() => drafts.filter((draft) => draft.metadataSaved !== true || !draft.parts.every((part) => part.complete)).length, [drafts]);
  const applyBootstrap = (external: ExternalCaptureBootstrapQuery["externalCapture"]) => { setResponsibilityId(external.responsibilityId); setRecaptureRequestId(external.recaptureRequestId ?? undefined); setKind(external.kind); setConfirmationOnly(external.confirmationOnly); setDisclosureVersion(external.disclosureVersion); setPolicy(external.policy); setRequirements(external.requirements); setAnswers(external.answers ?? []); setReferenceItems(external.referenceItems ?? []); setComparisonMode(typeof external.reference === "object" && external.reference !== null && "comparisonMode" in external.reference ? String(external.reference.comparisonMode) : ""); return external; };
  const loadBootstrap = async () => { const bootstrap = await graphql(captureOperations.bootstrap); return applyBootstrap(bootstrap.externalCapture); };
  const returnToReauthentication = (error: unknown): boolean => {
    if (!isCaptureSessionFailure(error)) return false;
    clearCaptureCsrfToken(); setCode(""); setStage("otp"); setNotice("Sua sessão expirou. Solicite um novo código para retomar a captura; as fotos salvas neste dispositivo foram preservadas."); void requestOtp();
    return true;
  };

  const requestOtp = async (linkToken = token): Promise<void> => { if (!linkToken) throw new Error("unavailable"); const result = await graphql(captureOperations.exchange, { input: { linkToken, clientMutationId: mutationID() } }); throwOnUserErrors(result.requestInvitationOtp); };
  useEffect(() => { void params.then(async ({ linkToken: routeToken }) => { const linkToken = routeToken === "acesso" ? getCaptureLinkToken() : routeToken; if (!linkToken) throw new Error("unavailable"); setToken(linkToken); setCaptureLinkToken(linkToken); history.replaceState(null, "", "/capture/acesso"); await requestOtp(linkToken); }).catch(() => { clearCaptureLinkToken(); setStage("unavailable"); setNotice("Este convite não está disponível. Solicite um novo link."); }); }, [params]);
  useEffect(() => { setOnline(navigator.onLine); const sync = () => setOnline(navigator.onLine); addEventListener("online", sync); addEventListener("offline", sync); return () => { removeEventListener("online", sync); removeEventListener("offline", sync); }; }, []);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview.url); }, [preview]);

  const selectRequirement = (key: string, afterConfirmation = false) => { if (preview && !afterConfirmation) return setNotice("Confirme a prévia ou tire a foto novamente antes de mudar de etapa."); setSelected(key); setDescription(""); setDescriptionOpen(false); setReason(""); setReasonOpen(false); setExpandedReference(false); setNotice(""); };
  const retryReference = async (key: string, previousURL?: string) => { setReferenceLoading(true); setFailedReferences((current) => current.filter((item) => item !== key)); try { const external = await loadBootstrap(); const refreshed = external.referenceItems.find((item) => item.requirementKey === key); if (!refreshed?.imageUrl || refreshed.imageUrl === previousURL) setFailedReferences((current) => [...current, key]); } catch (error) { if (!returnToReauthentication(error)) setFailedReferences((current) => [...current, key]); } finally { setReferenceLoading(false); } };
  const onReferenceError = (key: string, url: string) => { if (referenceAttempts[key]) return setFailedReferences((current) => current.includes(key) ? current : [...current, key]); setReferenceAttempts((current) => ({ ...current, [key]: 1 })); void retryReference(key, url); };

  const verify = async () => { if (!code.trim()) return setNotice("Informe o código recebido."); try { const result = await graphql(captureOperations.verifyOtp, { input: { linkToken: token, code, clientMutationId: mutationID() } }); throwOnUserErrors(result.verifyInvitationOtp); setCaptureCsrfToken(result.verifyInvitationOtp.csrfToken); const external = await loadBootstrap(); if (isTerminalBootstrapStatus(external.status)) { clearCaptureCsrfToken(); clearCaptureLinkToken(); setStage("unavailable"); setNotice("Este convite não está mais disponível. As fotos salvas neste dispositivo serão preservadas para uma eventual reautenticação."); } else { setStage("consent"); setNotice(""); } } catch (error) { if (!returnToReauthentication(error)) setNotice("Código inválido ou expirado. Confira o código recebido."); } };
  const accept = async () => { if (!disclosureVersion || !consentChoices.photoProcessing || !consentChoices.aiAnalysis || !consentChoices.gpsUse) return setNotice("Confirme todas as opções da divulgação para continuar."); try { const consent = await graphql(captureOperations.accept, { input: { disclosureVersion, ...consentChoices, clientMutationId: mutationID() } }); throwOnUserErrors(consent.acceptProcessing); if (confirmationOnly) { await removeDraftsForResponsibility(responsibilityId); setStage("confirmation"); return; } const external = await loadBootstrap(); const loaded = await refresh(external.responsibilityId); const references = guidedRequirements(external.requirements); const firstOpen = references.find((item) => requirementState(item, external.answers ?? [], loaded) !== "complete"); setSelected(firstOpen?.key ?? references[0]?.key ?? external.requirements[0]?.key ?? ""); setStage("capture"); } catch (error) { if (!returnToReauthentication(error)) setNotice(error instanceof Error ? error.message : "Não foi possível liberar esta responsabilidade."); } };
  const decline = async () => { setBusy(true); try { const result = await graphql(captureOperations.revoke, { input: { linkToken: token, clientMutationId: mutationID() } }); if (result.revokeInvitation.userErrors[0]) throw new Error(result.revokeInvitation.userErrors[0].message); setNotice("Este convite foi recusado e não está mais disponível."); } catch { setNotice("Este convite não está disponível. Solicite um novo link."); } finally { clearCaptureCsrfToken(); clearCaptureLinkToken(); setStage("unavailable"); setBusy(false); } };
  const resume = async (draft: CaptureDraft, advance = false) => { if (!online) return setNotice("Conecte-se para retomar o envio."); setBusy(true); setUploadingDraftId(draft.id); try { const uploaded = await uploadDraft(draft, (progress) => setUploadProgress((current) => ({ ...current, [draft.id]: progress }))); if (!uploaded.mediaId) throw new Error("A API não retornou a mídia de upload."); const mediaId = uploaded.mediaId; const blocked = isBlockedMediaStatus(uploaded.mediaStatus); if (uploaded.replacesMediaId) { const local = await loadDraftsForResponsibility(uploaded.responsibilityId); await Promise.all(local.filter((item) => item.mediaId === uploaded.replacesMediaId).map((item) => removeDraft(item.id))); } const updatedAnswers = mergeUploadedAnswer(answers, uploaded.metadata.requirementKey, mediaId, blocked, uploaded.replacesMediaId); setAnswers(updatedAnswers); const loaded = await refresh(); if (advance && !blocked) { const next = nextGuidedRequirement(guidedRequirements(requirements), uploaded.metadata.requirementKey, updatedAnswers, loaded); if (next) selectRequirement(next, true); } setNotice(blocked ? "A imagem foi enviada, mas a análise automática a bloqueou. Revise a foto; se a decisão estiver incorreta, declare um falso positivo." : "Foto salva. Continue com a próxima referência."); } catch (error) { if (!returnToReauthentication(error)) setNotice(presentUploadFailure(error)); } finally { setUploadingDraftId(undefined); setBusy(false); } };
  const commitFile = async (file: File, requirementKey: string, capturedAt: string, sourceSha256: string, imageProfile: string): Promise<boolean> => { const requirement = requirements.find((item) => item.key === requirementKey); if (!requirement || !responsibilityId) return false; if (mediaCountForRequirement(requirementKey, answers, drafts) >= requirement.maximumMedia) { setNotice(`Este requisito permite no máximo ${requirement.maximumMedia} mídia(s).`); return false; } setBusy(true); try { const sha256 = await digest(file); if (hasDuplicateDraft(requirementKey, sourceSha256, drafts) || hasDuplicateDraft(requirementKey, sha256, drafts)) { setNotice("Esta é a mesma imagem já enviada para este requisito. Tire ou selecione uma foto diferente."); return false; } const gps = consentChoices.gpsUse ? await new Promise<CaptureDraft["metadata"]["gps"]>((resolve) => { if (!navigator.geolocation) return resolve(undefined); navigator.geolocation.getCurrentPosition((position) => resolve({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracyMeters: position.coords.accuracy, capturedAt, windowStartedAt: capturedAt }), () => resolve(undefined), { enableHighAccuracy: true, maximumAge: 0, timeout: 5000 }); }) : undefined; if (policy.gpsRequired === true && !gps) { setNotice("A localização é obrigatória para este requisito. Permita o acesso ao GPS e tente capturar a foto novamente."); return false; } const deviceContext = { userAgent: navigator.userAgent, platform: navigator.platform, language: navigator.language }; const draft: CaptureDraft = { id: mutationID(), responsibilityId, blob: file, sha256, sourceSha256, imageProfile, parts: [], metadataSaved: false, metadata: { requirementKey, description, source: "camera", capturedAt, gps, deviceContext } }; await saveDraft(draft); const loaded = await refresh(); setDescription(""); setDescriptionOpen(false); if (online) await resume(draft, comparisonMode === "FIXED_ORIGIN"); else { const next = nextGuidedRequirement(guidedRequirements(requirements), requirementKey, answers, loaded); if (next) selectRequirement(next, true); setNotice("Foto salva neste dispositivo. Envio pendente até voltar a conexão."); } return true; } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível salvar esta foto."); return false; } finally { setBusy(false); } };
  const addFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!/^image\/(jpeg|png|webp|heic|heif)$/.test(file.type) || file.size > 20 * 1024 * 1024) return setNotice("Use JPEG, PNG, WebP, HEIC ou HEIF de até 20 MB."); setBusy(true); try { const sourceSha256 = await digest(file); const prepared = process.env.NEXT_PUBLIC_CAPTURE_IMAGE_OPTIMIZATION === "true" ? await prepareCaptureImage(file) : { file, profile: "capture-optimization-disabled-v1" }; if (preview) URL.revokeObjectURL(preview.url); setPreview({ file: prepared.file, url: URL.createObjectURL(prepared.file), requirementKey: selected, capturedAt: new Date().toISOString(), sourceSha256, imageProfile: prepared.profile }); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível preparar a foto."); } finally { setBusy(false); } };
  const confirmPreview = async () => { if (!preview) return; const current = preview; if (await commitFile(current.file, current.requirementKey, current.capturedAt, current.sourceSha256, current.imageProfile)) setPreview(undefined); };
  const allRequirementsSatisfied = requirementsSatisfied(requirements, answers, drafts);
  const mediaState = (draft: CaptureDraft): string => { if (isBlockedMediaStatus(draft.mediaStatus)) return `${presentMediaStatus(draft.mediaStatus ?? "REJECTED")}; requer atenção`; if (uploadingDraftId === draft.id) return "Enviando"; if (!draft.mediaId) return "Rascunho salvo neste dispositivo; aguardando envio"; if (draft.parts.some((part) => !part.complete)) return "Erro recuperável: envio interrompido"; if (draft.metadataSaved !== true) return "Recebida; aguardando verificação"; return "Recebida e verificada pelo servidor"; };
  const uploadProgressLabel = (progress: UploadProgress): string => { if (progress.phase === "preparing") return "Preparando upload"; if (progress.phase === "uploading") return progress.totalParts > 0 ? `Enviando partes (${progress.completedParts}/${progress.totalParts})` : "Enviando foto"; if (progress.phase === "verifying") return "Aguardando verificação da foto"; if (progress.phase === "saving") return "Salvando metadados"; if (progress.phase === "complete") return "Upload concluído"; return "Não foi possível concluir; retome o envio"; };
  const selectedRequirement = requirements.find((requirement) => requirement.key === selected);
  const selectedState = selectedRequirement ? requirementState(selectedRequirement, answers, drafts) : "missing";
  const referenceRequirements = guidedRequirements(requirements);
  const guided = comparisonMode === "FIXED_ORIGIN" && referenceRequirements.length > 0;
  const selectedReference = referenceItems.find((item) => item.requirementKey === selected);
  const selectedIndex = referenceRequirements.findIndex((item) => item.key === selected);
  const completedReferences = guidedProgress(referenceRequirements, answers, drafts);
  const referenceUnavailable = guided && (!selectedReference?.imageUrl || selectedReference.availability !== "AVAILABLE" || failedReferences.includes(selected));
  const selectedAnswer = answers.find((answer) => answer.requirementKey === selected);
  const selectedDraft = useMemo(() => {
    const answeredMediaIds = new Set(selectedAnswer?.mediaIds ?? []);
    return drafts.filter((draft) => draft.metadata.requirementKey === selected && !isBlockedMediaStatus(draft.mediaStatus)).sort((left, right) => {
      const leftAnswered = left.mediaId !== undefined && answeredMediaIds.has(left.mediaId) ? 1 : 0;
      const rightAnswered = right.mediaId !== undefined && answeredMediaIds.has(right.mediaId) ? 1 : 0;
      if (leftAnswered !== rightAnswered) return rightAnswered - leftAnswered;
      return Date.parse(right.metadata.capturedAt) - Date.parse(left.metadata.capturedAt);
    })[0];
  }, [drafts, selected, selectedAnswer]);
  const [savedPhotoURL, setSavedPhotoURL] = useState<string>();
  useEffect(() => {
    if (!selectedDraft) {
      setSavedPhotoURL(undefined);
      return;
    }
    const url = URL.createObjectURL(selectedDraft.blob);
    setSavedPhotoURL(url);
    return () => URL.revokeObjectURL(url);
  }, [selectedDraft]);
  const cameraDisabled = busy || referenceUnavailable || (guided && selectedState === "complete");
  const openCamera = () => { if (!cameraDisabled) cameraInputRef.current?.click(); };
  const savedPhotoPending = selectedDraft !== undefined && (selectedDraft.metadataSaved !== true || !selectedDraft.mediaId || selectedDraft.parts.some((part) => !part.complete));
  const savedReason = selectedAnswer?.impossibilityReason?.trim() ?? "";
  const impossible = async () => { if (!reason.trim()) return setNotice("Explique por que esta evidência não pode ser registrada."); const currentAnswer = answers.find((answer) => answer.requirementKey === selected); try { const result = await graphql(captureOperations.impossibility, { input: buildImpossibilityInput(selected, reason, currentAnswer, mutationID()) }); throwOnUserErrors(result.declareCaptureImpossibility); setAnswers((current) => updateImpossibleAnswer(current, selected, reason)); setReason(""); setReasonOpen(false); setNotice("Justificativa registrada."); } catch (error) { if (!returnToReauthentication(error)) setNotice(error instanceof Error ? error.message : "Não foi possível registrar a justificativa."); } };
  const declareFalsePositive = async () => { if (!falsePositiveMediaId) return setNotice("Selecione uma mídia bloqueada."); if (!falsePositiveReason.trim()) return setNotice("Explique por que a detecção é um falso positivo."); setBusy(true); try { const result = await graphql(captureOperations.falsePositive, { input: { mediaId: falsePositiveMediaId, reason: falsePositiveReason, clientMutationId: mutationID() } }); throwOnUserErrors(result.declareSensitiveDetectionFalsePositive); const mediaStatus = result.declareSensitiveDetectionFalsePositive.media?.status ?? "READY"; const updated = await Promise.all(drafts.map(async (draft) => draft.mediaId === falsePositiveMediaId ? persistDraftMediaStatus(draft, mediaStatus) : draft)); setDrafts(updated); setFalsePositiveMediaId(""); setFalsePositiveReason(""); await refresh(); setNotice("Falso positivo registrado para revisão."); } catch (error) { if (!returnToReauthentication(error)) setNotice(error instanceof Error ? error.message : "Não foi possível registrar o falso positivo."); } finally { setBusy(false); } };
  const submit = async (incomplete: boolean) => { if (!readyForSubmission(drafts, online, allRequirementsSatisfied, incomplete)) return setNotice(presentSubmissionBlock({ online, pending, blocked: blockedDrafts, allRequirementsSatisfied })); setBusy(true); try { if (kind === "RECAPTURE") { if (!recaptureRequestId) throw new Error("A solicitação de complemento não está disponível."); const result = await graphql(captureOperations.submitRecapture, { input: { requestId: recaptureRequestId, confirmIncomplete: incomplete, clientMutationId: mutationID() } }); throwOnUserErrors(result.submitRecapture); } else { const result = await graphql(captureOperations.submit, { input: { confirmIncomplete: incomplete, clientMutationId: mutationID() } }); throwOnUserErrors(result.submitCapture); } await Promise.all(drafts.map((draft) => removeDraft(draft.id))); clearCaptureCsrfToken(); clearCaptureLinkToken(); setStage("confirmation"); } catch (error) { if (!returnToReauthentication(error)) setNotice(error instanceof Error ? error.message : "Não foi possível confirmar o envio. Tente novamente."); } finally { setBusy(false); } };

  const currentStep = stage === "consent" ? 0 : stage === "capture" ? 1 : stage === "review" ? 2 : undefined;
  const readyDrafts = drafts.filter((draft) => !isBlockedMediaStatus(draft.mediaStatus) && draft.metadataSaved === true && Boolean(draft.mediaId) && draft.parts.length > 0 && draft.parts.every((part) => part.complete)).length;
  const readyEvidenceCount = new Set([...answers.flatMap((answer) => answer.mediaIds), ...drafts.filter((draft) => !isBlockedMediaStatus(draft.mediaStatus) && draft.metadataSaved === true).flatMap((draft) => draft.mediaId ? [draft.mediaId] : [])]).size;
  const blockedDrafts = drafts.filter((draft) => isBlockedMediaStatus(draft.mediaStatus)).length;
  const reviewBlock = presentSubmissionBlock({ online, pending, blocked: blockedDrafts, allRequirementsSatisfied });

  return <main className="capture-shell"><RegisterServiceWorker /><div className="capture-workspace">
    <header className="capture-intro"><p>Inspection / Captura</p><h1>Registrar vistoria</h1></header>
    {currentStep !== undefined && <CaptureSteps current={currentStep} />}
    {!online && <p className="capture-notice" role="status">Você está sem conexão. Fotos pendentes ficam apenas neste dispositivo; a confirmação final permanece indisponível.</p>}
    {stage === "otp" && <section className="capture-card"><h2>Confirme seu acesso</h2><p>Use o código de seis dígitos enviado para liberar esta responsabilidade.</p><label>Código de seis dígitos<input aria-label="Código de seis dígitos" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(event) => setCode(event.target.value)} /></label><div className="capture-actions"><button onClick={() => void verify()}>Confirmar código</button></div></section>}
    {stage === "consent" && <section className="capture-card"><h2>Uso dos seus dados</h2><p>Suas fotos e localização são usadas nesta vistoria. Não há decisão automática sobre você.</p><p className="status">Divulgação {disclosureVersion}</p><fieldset className="capture-check-options"><legend>Para continuar, autorize os três usos</legend><label className="capture-check-row"><input type="checkbox" checked={consentChoices.photoProcessing} onChange={(event) => setConsentChoices((current) => ({ ...current, photoProcessing: event.target.checked }))} /><span>Processamento das fotos<small>Para registrar as evidências desta vistoria.</small></span></label><label className="capture-check-row"><input type="checkbox" checked={consentChoices.aiAnalysis} onChange={(event) => setConsentChoices((current) => ({ ...current, aiAnalysis: event.target.checked }))} /><span>Análise por inteligência artificial<small>Para analisar as evidências enviadas.</small></span></label><label className="capture-check-row"><input type="checkbox" checked={consentChoices.gpsUse} onChange={(event) => setConsentChoices((current) => ({ ...current, gpsUse: event.target.checked }))} /><span>Localização quando necessária<small>Conforme os requisitos da vistoria.</small></span></label></fieldset><div className="capture-actions"><button disabled={busy} onClick={() => void accept()}>Aceitar e continuar</button><button className="secondary" disabled={busy} onClick={() => void decline()}>Não aceito</button></div></section>}
    {stage === "capture" && <section className={`capture-card capture-card--wide capture-evidence-card${guided ? " capture-evidence-card--guided" : ""}`}>
      <div className="capture-evidence-header"><div><p className="eyebrow">Evidências</p><h2>{guided ? "Compare cada ambiente" : "Adicione as evidências"}</h2></div><span className="capture-progress-count" aria-label="Resumo da captura">{guided ? completedReferences : readyEvidenceCount}/{guided ? referenceRequirements.length : requirements.length}</span></div>
      <p className="capture-evidence-lead">{guided ? "Veja a foto original, fotografe o mesmo local e confira sua imagem antes de enviar." : "Registre uma foto de cada requisito. Você pode adicionar uma descrição quando ela ajudar a contextualizar a imagem."}</p>
      {guided ? <>
        <div className="capture-guide-progress"><strong>Foto {selectedIndex + 1} de {referenceRequirements.length}</strong><progress value={completedReferences} max={referenceRequirements.length} aria-label="Progresso das fotos de comparação" /><span>{completedReferences} concluída(s)</span></div>
        <nav className="capture-reference-nav" aria-label="Fotos de referência"><ol>{referenceRequirements.map((requirement, index) => { const state = requirementState(requirement, answers, drafts); const item = referenceItems.find((reference) => reference.requirementKey === requirement.key); return <li key={requirement.key}><button type="button" aria-current={requirement.key === selected ? "step" : undefined} disabled={busy || Boolean(preview)} onClick={() => selectRequirement(requirement.key)}><span className="capture-reference-nav__number">{index + 1}</span><span className="capture-reference-nav__name">{item?.description || requirement.instructions || `Foto ${index + 1}`}</span><small>{state === "complete" ? "Concluída" : state === "pending" ? "Envio pendente" : state === "blocked" ? "Requer atenção" : "Pendente"}</small></button></li>; })}</ol></nav>
        <div className="capture-comparison-grid"><div className="capture-comparison-panel"><div className="capture-section-heading"><h3>Foto de referência</h3><span>Original</span></div>{referenceUnavailable ? <div className="capture-reference-empty" role="status"><strong>Foto de referência indisponível</strong><p>Não fotografe sem ver o original. Tente carregar novamente ou siga para outra foto.</p><button className="secondary" type="button" disabled={referenceLoading || !online} onClick={() => void retryReference(selected)}>{referenceLoading ? "Carregando…" : "Tentar novamente"}</button></div> : <><button type="button" className="capture-reference-image" onClick={() => setExpandedReference(true)} aria-label="Ampliar foto de referência"><img src={selectedReference?.imageUrl ?? ""} alt={`Foto de referência: ${selectedReference?.description || selectedRequirement?.instructions || "ambiente"}`} onError={() => onReferenceError(selected, selectedReference?.imageUrl ?? "")} /></button><p>{selectedReference?.description || selectedRequirement?.instructions}</p><button className="text-action" type="button" onClick={() => setExpandedReference(true)}>Ampliar referência</button></>}</div>
        <div className="capture-comparison-panel capture-photo-panel"><div className="capture-section-heading"><h3>Sua foto</h3><span>{preview ? "Prévia antes do envio" : savedPhotoURL ? (savedPhotoPending ? "Envio pendente" : "Foto registrada") : "Comparação"}</span></div>{preview ? <><img className="capture-photo-preview" src={preview.url} alt="Prévia da sua foto de comparação" /><div className="capture-preview-actions"><button type="button" disabled={busy} onClick={() => setPreview(undefined)}>Tirar novamente</button><button type="button" disabled={busy} onClick={() => void confirmPreview()}>{busy ? "Salvando…" : "Usar esta foto"}</button></div></> : savedPhotoURL ? <div className="capture-photo-saved"><img className="capture-photo-preview" src={savedPhotoURL} alt={`Sua foto: ${selectedReference?.description || selectedRequirement?.instructions || "ambiente"}`} /><p className="capture-photo-status" role="status">{savedPhotoPending ? "Foto salva neste dispositivo; envio pendente." : "Foto registrada neste dispositivo."}</p></div> : selectedState === "complete" ? <div className="capture-photo-empty" role="status"><p>Esta comparação está concluída.</p>{selectedRequirement && <p className="capture-requirement-meta">{selectedRequirement.minimumMedia} foto · GPS {booleanValue(policy.gpsRequired) ? "obrigatório" : "conforme a política"}</p>}</div> : <><button className="capture-camera-button" type="button" disabled={cameraDisabled} onClick={openCamera}><Icon name="camera" aria-hidden="true" />Tirar foto</button><button className="capture-photo-empty capture-photo-trigger" type="button" disabled={cameraDisabled} onClick={openCamera}><Icon name="camera" aria-hidden="true" /><span className="capture-photo-trigger__label">Toque ou clique aqui para tirar a foto.</span>{selectedRequirement && <span className="capture-requirement-meta">{selectedRequirement.minimumMedia} foto · GPS {booleanValue(policy.gpsRequired) ? "obrigatório" : "conforme a política"}</span>}</button></>}<input ref={cameraInputRef} className="capture-camera-input" aria-label="Tirar foto" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" disabled={cameraDisabled} onChange={(event) => void addFile(event)} /></div></div>
        {expandedReference && selectedReference?.imageUrl && <div className="capture-image-overlay" role="dialog" aria-modal="true" aria-label="Foto de referência ampliada"><button type="button" onClick={() => setExpandedReference(false)}>Fechar imagem</button><img src={selectedReference.imageUrl} alt={`Foto de referência ampliada: ${selectedReference.description || "ambiente"}`} /><p>{selectedReference.description}</p></div>}
        <div className="capture-guide-navigation"><button className="secondary" type="button" disabled={selectedIndex <= 0 || busy || Boolean(preview)} onClick={() => selectRequirement(referenceRequirements[selectedIndex - 1].key)}>Anterior</button><button className="secondary" type="button" disabled={selectedIndex >= referenceRequirements.length - 1 || busy || Boolean(preview)} onClick={() => selectRequirement(referenceRequirements[selectedIndex + 1].key)}>Próxima foto</button></div>
      </> : <><div className="capture-requirement-picker"><label>Requisito<select aria-label="Requisito" value={selected} onChange={(event) => selectRequirement(event.target.value)}>{requirements.map((requirement) => <option key={requirement.key} value={requirement.key}>{presentRequirementSection(requirement.section)}: {presentRequirementLabel(requirement.label)}</option>)}</select></label></div>{selectedRequirement && <div className="capture-requirement-context"><h3>{presentRequirementLabel(selectedRequirement.label)}</h3>{selectedRequirement.instructions && <p>{selectedRequirement.instructions}</p>}<p className="capture-requirement-meta">{selectedRequirement.minimumMedia}–{selectedRequirement.maximumMedia} foto(s) · GPS {booleanValue(policy.gpsRequired) ? "obrigatório" : "conforme a política"}</p></div>}</>}
      <div className="capture-description-control"><button className="capture-disclosure" type="button" aria-expanded={descriptionOpen} onClick={() => setDescriptionOpen((open) => !open)}><span>{descriptionOpen ? "Ocultar descrição" : "Adicionar descrição"}</span><small>Opcional · ajuda a contextualizar a foto</small></button>{descriptionOpen && <label>Descrição da foto<span className="field-hint">Escreva apenas se houver algo importante para registrar.</span><textarea aria-label="Descrição da foto" value={description} onChange={(event) => setDescription(event.target.value)} /></label>}</div>
      {!guided && !preview && <label className="capture-camera-action"><span className="capture-camera-action__button">Tirar foto</span><small>Use a câmera do dispositivo para registrar este requisito.</small><input aria-label="Tirar foto" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" disabled={busy} onChange={(event) => void addFile(event)} /></label>}
      {!guided && preview && <div className="capture-photo-preview-card"><img className="capture-photo-preview" src={preview.url} alt="Prévia da sua foto de comparação" /><div className="capture-preview-actions"><button type="button" disabled={busy} onClick={() => setPreview(undefined)}>Tirar novamente</button><button type="button" disabled={busy} onClick={() => void confirmPreview()}>{busy ? "Salvando…" : "Usar esta foto"}</button></div></div>}
      {selectedRequirement?.impossibilityAllowed && <div className="capture-impossibility-control"><button className="capture-disclosure capture-disclosure--quiet" type="button" aria-expanded={reasonOpen} onClick={() => { setReasonOpen((open) => !open); if (!reasonOpen && savedReason) setReason(savedReason); }}><span>{savedReason ? "Editar justificativa" : "Não consegue fotografar?"}</span><small>Explique rapidamente a impossibilidade</small></button>{savedReason && !reasonOpen && <p className="capture-saved-reason">Justificativa registrada: {savedReason}</p>}{reasonOpen && <div className="capture-reason-editor"><label>Justificativa<span className="field-hint">Informe por que este requisito não pode ser fotografado.</span><textarea aria-label="Justificativa da impossibilidade" value={reason} onChange={(event) => setReason(event.target.value)} /></label><button type="button" disabled={busy} onClick={() => void impossible()}>{savedReason ? "Atualizar justificativa" : "Registrar impossibilidade"}</button></div>}</div>}
      {(drafts.length > 0 || blockedDrafts > 0) && <div className="capture-media-status"><div className="capture-section-heading"><h3>Envios</h3><span>{readyDrafts} pronta(s) · {pending} pendente(s)</span></div>{drafts.length > 0 ? <ul>{drafts.map((draft) => { const progress = uploadProgress[draft.id]; const requirementLabel = presentRequirementLabel(requirements.find((requirement) => requirement.key === draft.metadata.requirementKey)?.label ?? draft.metadata.requirementKey); const mediaFeedback = isBlockedMediaStatus(draft.mediaStatus) ? presentMediaFeedback(draft.mediaStatus ?? "REJECTED") : undefined; return <li className="capture-media-item" key={draft.id}><span>{requirementLabel}: {mediaState(draft)}</span>{mediaFeedback && <div className={`capture-media-feedback capture-media-feedback--${mediaFeedback.tone}`} role="status"><strong>{mediaFeedback.title}</strong><p>{mediaFeedback.message}</p><p>{mediaFeedback.guidance}</p></div>}{progress && <div className="capture-media-progress"><progress value={progress.percent} max="100" aria-label={`Progresso do envio de ${requirementLabel}`} /><span className="capture-media-progress__status" role="status">{uploadProgressLabel(progress)}</span></div>}{isFalsePositiveActionable(draft.mediaStatus) && draft.mediaId && <button disabled={!online || busy} onClick={() => setFalsePositiveMediaId(draft.mediaId ?? "")}>Declarar falso positivo</button>}{(draft.metadataSaved === false || !draft.parts.every((part) => part.complete)) && <button disabled={!online || busy} onClick={() => void resume(draft)}>Retomar envio</button>}</li>; })}</ul> : <p>Os envios aparecerão aqui após a primeira foto.</p>}</div>}
      {falsePositiveMediaId && <div className="capture-reason-editor"><label>Motivo do falso positivo<textarea aria-label="Motivo do falso positivo" value={falsePositiveReason} onChange={(event) => setFalsePositiveReason(event.target.value)} /></label><button disabled={!online || busy} onClick={() => void declareFalsePositive()}>Enviar declaração de falso positivo</button></div>}
      <div className="capture-actions"><button disabled={busy} onClick={() => setStage("review")}>Revisar vistoria</button></div>
    </section>}
    {stage === "review" && <section className="capture-card"><h2>Revise antes de enviar</h2><dl className="capture-review"><div><dt>Autorizações</dt><dd>Três usos autorizados</dd></div><div><dt>Evidências prontas</dt><dd>{readyEvidenceCount}</dd></div><div><dt>Envios pendentes</dt><dd>{pending}</dd></div><div><dt>Imagens bloqueadas</dt><dd>{blockedDrafts}</dd></div><div><dt>Requisitos</dt><dd>{requirements.length}</dd></div></dl>{guided && <div className="capture-review-references"><h3>Comparações</h3><ol>{referenceRequirements.map((requirement, index) => { const state = requirementState(requirement, answers, drafts); const reference = referenceItems.find((item) => item.requirementKey === requirement.key); return <li key={requirement.key}><span>{reference?.description || requirement.instructions || `Foto ${index + 1}`}</span><strong>{state === "complete" ? "Concluída" : state === "pending" ? "Envio pendente" : state === "blocked" ? "Requer atenção" : "Não fotografada"}</strong><button type="button" className="text-action" onClick={() => { selectRequirement(requirement.key); setStage("capture"); }}>Ver etapa</button></li>; })}</ol></div>}<p>A confirmação encerra esta responsabilidade. Qualquer correção posterior exigirá um novo complemento.</p>{reviewBlock && <p className="capture-notice" role="status">{reviewBlock}</p>}<div className="capture-actions"><button disabled={!online || busy} onClick={() => void submit(false)}>Enviar vistoria completa</button><button className="secondary" disabled={!online || busy} onClick={() => void submit(true)}>Confirmar envio incompleto</button><button className="text-action" disabled={busy} onClick={() => setStage("capture")}>Voltar às evidências</button></div></section>}
    {stage === "confirmation" && <section className="capture-card capture-finish"><p className="status">Confirmação concluída</p><h2>Recebemos sua confirmação</h2><p>Esta responsabilidade foi encerrada. Esta área não exibe fotos enviadas, resultados, classificações ou laudos.</p></section>}
    {stage === "unavailable" && <section className="capture-card capture-finish"><p className="status">Acesso encerrado</p><h2>Acesso indisponível</h2><p>{notice || "O aceite é necessário para continuar."}</p></section>}
    {notice && stage !== "unavailable" && <p className="capture-feedback" role="status">{notice}</p>}
    <p className="capture-privacy-note">Acesso pessoal vinculado ao convite. Não compartilhe este link.</p>
  </div></main>;
}

function CaptureSteps({ current }: { current: number }) {
  return <ol className="capture-steps" aria-label="Etapas da captura">{["Autorizações", "Evidências", "Revisão"].map((label, index) => <li key={label} className={index === current ? "active" : undefined} aria-current={index === current ? "step" : undefined}><span>{index < current ? "✓" : index + 1}</span>{label}</li>)}</ol>;
}
