FROM quay.io/keycloak/keycloak:26.2.5 AS builder
COPY deploy/keycloak/themes/inspection /opt/keycloak/themes/inspection
RUN /opt/keycloak/bin/kc.sh build --db=postgres --health-enabled=true

FROM quay.io/keycloak/keycloak:26.2.5
COPY --from=builder /opt/keycloak/ /opt/keycloak/
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--optimized", "--http-enabled=true", "--health-enabled=true", "--proxy-headers=xforwarded"]
