ARG KEYCLOAK_IMAGE=quay.io/keycloak/keycloak:26.2.5
FROM ${KEYCLOAK_IMAGE} AS builder
COPY deploy/keycloak/themes/inspection /opt/keycloak/themes/inspection
RUN /opt/keycloak/bin/kc.sh build --db=postgres --health-enabled=true

FROM ${KEYCLOAK_IMAGE}
COPY --from=builder /opt/keycloak/ /opt/keycloak/
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--optimized", "--http-enabled=true", "--proxy-headers=xforwarded"]
