"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { beginPKCE } from "@/auth/pkce";
import { clearSession, getMembershipId, selectMembership, setIdentity, type DashboardIdentity } from "@/auth/session";
import { composeCapabilities, type Capability } from "@/features/dashboard/capabilities";
import { useNotifications } from "@/features/notifications/use-notifications";
import {
  AddExceptionalStageDocument, CancelInspectionDocument, CancelScheduleDocument, CloseProjectDocument, CreateInspectionDocument, CreateProjectDocument, CreateScheduleDocument, CustomerEvidenceDocument, CustomerPortfolioDocument, CustomerReportDocument,
  CustomerTimelineDocument, DashboardGateDocument, DashboardMembershipsDocument, InvalidateInspectionDocument, OperationalOverviewDocument, ProjectDetailDocument,
  InvalidateReportPublicationDocument, ProjectsDocument, ProjectTimelineDocument, PublishReportDocument, ReopenProjectDocument, ReportDownloadDocument, ReportWorkspaceDocument, RequestRecaptureDocument, SchedulesDocument, InspectionsDocument, SkipProjectStageDocument, StartProjectStageDocument, UpdateScheduleDocument,
  type CustomerPortfolioQuery, type DashboardGateQuery, type DashboardMembershipsQuery, type InspectionsQuery, type OperationalOverviewQuery, type ProjectsQuery, type ReportDownloadQuery, type ReportWorkspaceQuery, type SchedulesQuery,
} from "@/graphql/generated";
import { graphql, type GraphQLFailure } from "@/graphql/client";

type Page = "Início" | "Agendas" | "Inspeções" | "Projetos e etapas" | "Triagem" | "Relatórios" | "Portfólio" | "Notificações";

export function DashboardShell({ section }: { section: Page }) {
  const pathname = usePathname();
  const router = useRouter();
  const [identity, setCurrentIdentity] = useState<DashboardIdentity>();
  const [capability, setCapability] = useState<Capability>();
  const [memberships, setMemberships] = useState<DashboardMembershipsQuery["memberships"]["nodes"]>([]);
  const [message, setMessage] = useState("Verificando acesso…");

  const loadGate = useCallback(async () => {
    try {
      if (!getMembershipId()) {
        const membershipData = await graphql<DashboardMembershipsQuery, { after: string | null }>(DashboardMembershipsDocument, { after: null });
        const activeMemberships = membershipData.memberships.nodes.filter((membership) => membership.status === "ACTIVE");
        setMemberships(activeMemberships);
        if (activeMemberships.length === 1) { selectMembership(activeMemberships[0].id); setMessage("Contexto de acesso selecionado. Carregando dados protegidos…"); void loadGate(); return; }
        setCurrentIdentity(undefined); setCapability(undefined); setMessage("Selecione o contexto de acesso antes de carregar dados protegidos."); return;
      }
      const data = await graphql<DashboardGateQuery, {}>(DashboardGateDocument, {});
      const current = { tenantId: data.me.tenantId, tenantName: data.tenant?.name ?? "Tenant", tenantStatus: data.tenant?.status ?? "INACTIVE", entitlements: data.me.productEntitlements, roles: data.me.roles, scopes: data.me.effectiveScopes };
      if (!current.entitlements.includes("DASHBOARD") || !current.roles.length || current.tenantStatus !== "ACTIVE") {
        clearSession(); setCurrentIdentity(undefined); setCapability(undefined); setMessage("Acesso ao Dashboard não autorizado. Nenhum dado operacional foi carregado."); return;
      }
      setIdentity(current); setCurrentIdentity(current); setCapability(composeCapabilities(current)); setMessage(data.tenant?.name ?? "Contexto operacional ativo");
    } catch (error) {
      setCurrentIdentity(undefined); setCapability(undefined);
      const failure = error as GraphQLFailure;
      setMessage(["FORBIDDEN", "UNAUTHENTICATED", "TENANT_INACTIVE"].includes(failure.code ?? "") ? "Acesso ao Dashboard não autorizado. Nenhum dado operacional foi carregado." : failure.message);
    }
  }, []);
  useEffect(() => { void loadGate(); }, [loadGate]);
  const notifications = useNotifications(Boolean(identity));
  const signIn = () => void beginPKCE(process.env.NEXT_PUBLIC_OIDC_AUTHORIZE_URL ?? "http://localhost:8081/realms/inspection/protocol/openid-connect/auth", pathname);
  const switchMembership = (membershipId: string) => { selectMembership(membershipId); setCurrentIdentity(undefined); setCapability(undefined); setMessage("Trocando o contexto de acesso. Dados protegidos anteriores foram removidos."); void loadGate(); };

  if (!identity || !capability) return <main className="denial"><h1>Dashboard</h1><p role="status">{message}</p>{memberships.length > 0 && <MembershipPicker memberships={memberships} selected={getMembershipId()} onChange={switchMembership} />}{memberships.length === 0 && <button onClick={signIn}>Entrar no Dashboard</button>}</main>;
  return <main><header><strong>Inspeção · Dashboard</strong><span>{message}</span><div className="actions">{memberships.length > 1 && <MembershipPicker memberships={memberships} selected={getMembershipId()} onChange={switchMembership} />}{capability.canUseAdmin && <a href={process.env.NEXT_PUBLIC_ADMIN_URL ?? "http://localhost:3000"}>Abrir Administração</a>}<Link href="/notifications">Notificações ({notifications.unreadCount})</Link></div></header><nav aria-label="Dashboard">{capability.links.map(([label, href]) => <Link key={href} aria-current={pathname === href ? "page" : undefined} href={href}>{label}</Link>)}</nav><section><div className="actions"><h1>{section}</h1><button className="secondary" onClick={() => { void loadGate(); void notifications.refresh(); router.refresh(); }}>Atualizar</button></div>{notifications.error && <p className="warning" role="status">Dados já exibidos podem estar desatualizados. {notifications.error}</p>}{capability.audience === "customer" ? <CustomerPortal section={section} /> : <OperationsDashboard section={section} capability={capability} />}{section === "Notificações" && <NotificationCenter notifications={notifications} />}</section></main>;
}

function MembershipPicker({ memberships, selected, onChange }: { memberships: DashboardMembershipsQuery["memberships"]["nodes"]; selected?: string; onChange: (id: string) => void }) {
  return <label className="membership">Contexto de acesso<select aria-label="Contexto de acesso" value={selected ?? ""} onChange={(event) => onChange(event.target.value)}><option value="" disabled>Selecione</option>{memberships.map((membership) => <option key={membership.id} value={membership.id}>{membership.role} · {membership.tenantId}</option>)}</select></label>;
}

function OperationsDashboard({ section, capability }: { section: Page; capability: Capability }) {
  if (section === "Agendas") return <SchedulesJourney canMutate={capability.canMutate} />;
  if (section === "Inspeções") return <InspectionsJourney canMutate={capability.canMutate} />;
  if (section === "Projetos e etapas") return <ProjectsJourney canMutate={capability.canMutate} />;
  if (section === "Relatórios") return <ReportsJourney canPublish={capability.canPublish} />;
  if (section === "Notificações") return null;
  return <OverviewJourney />;
}

function OverviewJourney() {
  const [classification, setClassification] = useState(""); const [status, setStatus] = useState(""); const [data, setData] = useState<OperationalOverviewQuery>(); const [message, setMessage] = useState("Carregue o resumo e a fila no contexto autorizado.");
  async function loadOverview(): Promise<OperationalOverviewQuery> { return graphql<OperationalOverviewQuery, { after: string | null; classification: string | null; status: string | null }>(OperationalOverviewDocument, { after: null, classification: classification || null, status: status || null }); }
  const load = async () => { try { const next = await loadOverview(); setData(next); setMessage(next.triageInspections.nodes.length ? "Resumo e fila atualizados com o mesmo filtro." : "Não há itens para os filtros selecionados."); } catch (error) { setMessage(`Dados exibidos podem estar desatualizados. ${(error as Error).message}`); } };
  return <div className="feature"><p>Resumo e triagem usam o mesmo filtro e contexto de servidor. A fila é somente leitura para VIEWER; a autorização é sempre revalidada no servidor.</p><div className="filters"><label>Classificação<select value={classification} onChange={(event) => setClassification(event.target.value)}><option value="">Todas</option><option value="CRITICAL">Crítica</option><option value="ATTENTION">Atenção</option></select></label><label>Status<input value={status} onChange={(event) => setStatus(event.target.value)} placeholder="Ex.: PENDING" /></label><button onClick={() => void load()}>Atualizar prioridades</button></div><p role="status">{message}</p>{data && <><div className="cards">{Object.entries(data.dashboardSummary).map(([name, value]) => <article className="card" key={name}><strong>{name}</strong><div>{value}</div></article>)}</div><Collection items={data.triageInspections.nodes.map((item) => ({ id: item.inspectionId, title: `${item.classification} · ${item.status}`, detail: `Atualizado em ${item.updatedAt}` }))} /></>}</div>;
}

function SchedulesJourney({ canMutate }: { canMutate: boolean }) {
  const [data, setData] = useState<SchedulesQuery>(); const [message, setMessage] = useState("Agendas futuras preservam inspeções históricas após cancelamento.");
  const load = async () => { try { const next = await graphql<SchedulesQuery, { after: string | null }>(SchedulesDocument, { after: null }); setData(next); setMessage(next.schedules.nodes.length ? "Agendas atualizadas." : "Nenhuma agenda encontrada. Crie uma agenda após configurar dependências elegíveis."); } catch (error) { setMessage((error as Error).message); } };
  const mutate = async (document: typeof CreateScheduleDocument | typeof UpdateScheduleDocument | typeof CancelScheduleDocument, input: Record<string, unknown>) => { try { const result = await graphql(document as never, { input } as never); const payload = Object.values(result as Record<string, unknown>)[0] as { userErrors?: Array<{ message: string; code: string }> }; setMessage(payload.userErrors?.length ? formatMutationErrors(payload.userErrors) : "Agenda salva. Atualizando dados…"); if (!payload.userErrors?.length) await load(); } catch (error) { setMessage(formatFailure(error)); } };
  return <div className="feature"><p>Criação e atualização mostram recorrência, prazo, lembretes, próxima ocorrência e versão. Conflitos preservam os valores enviados para recuperação.</p>{canMutate && <ScheduleForm onSubmit={(input) => void mutate(CreateScheduleDocument, input)} /> }<button onClick={() => void load()}>Carregar agendas</button><p role="status">{message}</p>{data && <ul className="collection">{data.schedules.nodes.map((item) => <li key={item.id}><strong>{item.status} · próxima: {item.nextDueAt}</strong><span>{item.rrule} · {item.timezone} · v{item.version}</span>{canMutate && <div className="actions"><button onClick={() => void mutate(UpdateScheduleDocument, { scheduleId: item.id, expectedVersion: item.version, clientMutationId: mutationId(), rrule: item.rrule, timezone: item.timezone, startsAt: item.startsAt, deadlineMinutes: item.deadlineMinutes, reminderOffsetsMinutes: item.reminderOffsetsMinutes })}>Salvar configuração atual</button><button className="secondary" onClick={() => { if (window.confirm("Cancelar esta agenda? As inspeções históricas serão preservadas.")) void mutate(CancelScheduleDocument, { scheduleId: item.id, expectedVersion: item.version, clientMutationId: mutationId() }); }}>Cancelar agenda</button></div>}</li>)}</ul>}</div>;
}

function ScheduleForm({ onSubmit }: { onSubmit: (input: Record<string, unknown>) => void }) { const [assetId, setAssetId] = useState(""); const [participantId, setParticipantId] = useState(""); const [templateId, setTemplateId] = useState(""); const [rrule, setRrule] = useState("FREQ=MONTHLY"); const [startsAt, setStartsAt] = useState(""); const [timezone, setTimezone] = useState("UTC"); const [deadlineMinutes, setDeadlineMinutes] = useState("60"); const [reminders, setReminders] = useState("30"); return <form onSubmit={(event) => { event.preventDefault(); onSubmit({ assetId, participantId, templateId, rrule, startsAt, timezone, deadlineMinutes: Number(deadlineMinutes), reminderOffsetsMinutes: parseNumbers(reminders), referenceVersionId: null, clientMutationId: mutationId() }); }}><h2>Nova agenda</h2><Field label="Ativo" value={assetId} onChange={setAssetId} required /><Field label="Participante" value={participantId} onChange={setParticipantId} required /><Field label="Template" value={templateId} onChange={setTemplateId} required /><Field label="Início" value={startsAt} onChange={setStartsAt} type="datetime-local" required /><Field label="Fuso horário" value={timezone} onChange={setTimezone} required /><Field label="RRULE" value={rrule} onChange={setRrule} required /><Field label="Prazo (minutos)" value={deadlineMinutes} onChange={setDeadlineMinutes} type="number" required /><Field label="Lembretes (minutos, separados por vírgula)" value={reminders} onChange={setReminders} required /><button type="submit">Criar agenda</button></form>; }

function InspectionsJourney({ canMutate }: { canMutate: boolean }) {
  const params = useSearchParams(); const [data, setData] = useState<InspectionsQuery>(); const [message, setMessage] = useState("Coleção, histórico e detalhe conservam cursores no servidor."); const selected = params.get("inspectionId");
  const load = async () => { try { const next = await graphql<InspectionsQuery, { after: string | null; history: boolean }>(InspectionsDocument, { after: null, history: true }); setData(next); setMessage(next.inspections.nodes.length ? "Inspeções atualizadas." : "Nenhuma inspeção encontrada neste escopo."); } catch (error) { setMessage((error as Error).message); } };
  const mutate = async (document: typeof CreateInspectionDocument | typeof CancelInspectionDocument | typeof InvalidateInspectionDocument, input: Record<string, unknown>) => { try { const result = await graphql(document as never, { input } as never); const payload = Object.values(result as Record<string, unknown>)[0] as { userErrors?: Array<{ message: string; code: string }> }; setMessage(payload.userErrors?.length ? formatMutationErrors(payload.userErrors) : "Inspeção salva. Atualizando dados…"); if (!payload.userErrors?.length) await load(); } catch (error) { setMessage(formatFailure(error)); } };
  return <div className="feature">{canMutate && <InspectionForm onSubmit={(input) => void mutate(CreateInspectionDocument, input)} />}<button onClick={() => void load()}>Carregar inspeções</button><p role="status">{message}</p>{data && <ul className="collection">{data.inspections.nodes.map((item) => <li key={item.id}><strong>{item.status} · {item.source}</strong><span>{item.evidenceCount} evidência(s) · prazo {item.deadlineAt} · v{item.version}</span>{canMutate && <div className="actions"><button onClick={() => void mutate(CancelInspectionDocument, { inspectionId: item.id, expectedVersion: item.version, clientMutationId: mutationId() })}>Cancelar</button><button className="secondary" onClick={() => { const reason = window.prompt("Motivo da invalidação"); if (reason) void mutate(InvalidateInspectionDocument, { inspectionId: item.id, expectedVersion: item.version, reason, clientMutationId: mutationId() }); }}>Invalidar</button><button className="secondary" onClick={() => void requestRecapture(item.id, item.version, setMessage)}>Solicitar recaptura</button></div>}</li>)}</ul>}{selected && <InspectionWorkspace id={selected} canMutate={canMutate} />}</div>;
}

function InspectionForm({ onSubmit }: { onSubmit: (input: Record<string, unknown>) => void }) { const [assetId, setAssetId] = useState(""); const [participantId, setParticipantId] = useState(""); const [dueAt, setDueAt] = useState(""); const [deadlineAt, setDeadlineAt] = useState(""); return <form onSubmit={(event) => { event.preventDefault(); onSubmit({ assetId, participantId, dueAt, deadlineAt, reason: "Criada pelo Dashboard", templateId: null, referenceVersionId: null, reminderInstants: [], clientMutationId: mutationId() }); }}><h2>Nova inspeção</h2><Field label="Ativo" value={assetId} onChange={setAssetId} required /><Field label="Participante" value={participantId} onChange={setParticipantId} required /><Field label="Vencimento" value={dueAt} onChange={setDueAt} type="datetime-local" required /><Field label="Prazo final" value={deadlineAt} onChange={setDeadlineAt} type="datetime-local" required /><button type="submit">Criar inspeção</button></form>; }

function InspectionWorkspace({ id, canMutate }: { id: string; canMutate: boolean }) {
  const [message, setMessage] = useState("Carregando estado atual da inspeção…"); const [detail, setDetail] = useState<InspectionsQuery["inspections"]["nodes"][number]>();
  async function loadDetail(): Promise<InspectionsQuery> { return graphql<InspectionsQuery, { after: string | null; history: boolean }>(InspectionsDocument, { after: null, history: true }); }
  useEffect(() => { void loadDetail().then((data) => { const inspection = data.inspections.nodes.find((item) => item.id === id); setDetail(inspection); setMessage(inspection ? "Estado atual carregado." : "A inspeção não está disponível neste contexto."); }).catch((error) => setMessage((error as Error).message)); }, [id]);
  return <article className="card"><h2>Detalhe da inspeção</h2><p role="status">{message}</p>{detail && <dl><dt>Status</dt><dd>{detail.status}</dd><dt>Evidências</dt><dd>{detail.evidenceCount}</dd><dt>Motivo</dt><dd>{detail.stateReason ?? "—"}</dd><dt>Versão</dt><dd>{detail.version}</dd></dl>}{canMutate && <p>Cancelamento e invalidação exigem versão atual, identidade de mutação e, na invalidação, motivo. Após interrupção, recarregue este detalhe para confirmar o resultado.</p>}</article>;
}

function ProjectsJourney({ canMutate }: { canMutate: boolean }) {
  const [data, setData] = useState<ProjectsQuery>(); const [message, setMessage] = useState("Projetos preservam estágios e histórico ordenado.");
  const load = async () => { try { const next = await graphql<ProjectsQuery, { after: string | null }>(ProjectsDocument, { after: null }); setData(next); setMessage(next.projects.nodes.length ? "Projetos atualizados." : "Não há projetos neste escopo."); } catch (error) { setMessage((error as Error).message); } };
  const mutate = async (document: typeof CreateProjectDocument | typeof StartProjectStageDocument | typeof SkipProjectStageDocument | typeof CloseProjectDocument | typeof ReopenProjectDocument | typeof AddExceptionalStageDocument, input: Record<string, unknown>) => { try { const result = await graphql(document as never, { input } as never); const payload = Object.values(result as Record<string, unknown>)[0] as { userErrors?: Array<{ message: string; code: string }> }; setMessage(payload.userErrors?.length ? formatMutationErrors(payload.userErrors) : "Projeto salvo. Atualizando dados…"); if (!payload.userErrors?.length) await load(); } catch (error) { setMessage(formatFailure(error)); } };
  return <div className="feature"><p>Crie projetos com ativo, participante e template. Etapas excepcionais, início, salto, encerramento e reabertura usam versões esperadas e razões quando exigidas.</p>{canMutate && <ProjectForm onSubmit={(input) => void mutate(CreateProjectDocument, input)} />}<button onClick={() => void load()}>Carregar projetos</button><p role="status">{message}</p>{data && <ul className="collection">{data.projects.nodes.map((item) => <li key={item.id}><strong>{item.status} · {item.stages.length} etapa(s)</strong><span>{item.reportMode} · v{item.version}</span>{canMutate && <div className="actions"><button onClick={() => void mutate(CloseProjectDocument, { projectId: item.id, expectedVersion: item.version, clientMutationId: mutationId() })}>Encerrar</button><button className="secondary" onClick={() => { const reason = window.prompt("Motivo da reabertura"); if (reason) void mutate(ReopenProjectDocument, { projectId: item.id, expectedVersion: item.version, reason, clientMutationId: mutationId() }); }}>Reabrir</button>{item.stages.map((stage) => <span key={stage.id} className="actions"><button onClick={() => void mutate(StartProjectStageDocument, { projectId: item.id, stageId: stage.id, expectedProjectVersion: item.version, expectedStageVersion: stage.version, dueAt: stage.plannedAt ?? new Date().toISOString(), deadlineAt: stage.plannedAt ?? new Date().toISOString(), reminderInstants: [], referenceVersionId: null, clientMutationId: mutationId() })}>Iniciar {stage.label}</button><button className="secondary" onClick={() => { const reason = window.prompt("Motivo do salto"); if (reason) void mutate(SkipProjectStageDocument, { projectId: item.id, stageId: stage.id, expectedVersion: item.version, reason, clientMutationId: mutationId() }); }}>Pular</button></span>)}</div>}</li>)}</ul>}</div>;
}

function ProjectForm({ onSubmit }: { onSubmit: (input: Record<string, unknown>) => void }) { const [assetId, setAssetId] = useState(""); const [participantId, setParticipantId] = useState(""); const [templateId, setTemplateId] = useState(""); return <form onSubmit={(event) => { event.preventDefault(); onSubmit({ assetId, participantId, templateId: templateId || null, clientMutationId: mutationId() }); }}><h2>Novo projeto</h2><Field label="Ativo" value={assetId} onChange={setAssetId} required /><Field label="Participante" value={participantId} onChange={setParticipantId} required /><Field label="Template (opcional)" value={templateId} onChange={setTemplateId} /><button type="submit">Criar projeto</button></form>; }

function ReportsJourney({ canPublish }: { canPublish: boolean }) {
  const params = useSearchParams(); const inspectionId = params.get("inspectionId"); const [message, setMessage] = useState("Selecione uma inspeção para abrir o relatório versionado."); const [data, setData] = useState<ReportWorkspaceQuery | null>(); const [download, setDownload] = useState<ReportDownloadQuery["reportDownload"]>();
  async function load(): Promise<ReportWorkspaceQuery | null> { return inspectionId ? graphql<ReportWorkspaceQuery, { inspectionId: string; version: number | null }>(ReportWorkspaceDocument, { inspectionId, version: null }) : null; }
  const open = async () => { try { const next = await load(); setData(next); setMessage(next?.report ? "Versão legível, conteúdo canônico e renderização carregados." : "Relatório ainda não está pronto ou não está disponível."); } catch (error) { setMessage((error as Error).message); } };
  const prepareDownload = async () => { if (!report) return; setDownload(undefined); setMessage("Preparando o download PDF…"); try { const next = await graphql<ReportDownloadQuery, { snapshotId: string }> (ReportDownloadDocument, { snapshotId: report.id }); setDownload(next.reportDownload); setMessage(next.reportDownload ? `Download PDF: ${next.reportDownload.status}.` : "O PDF ainda não está disponível."); } catch (error) { setMessage((error as Error).message); } };
  const mutate = async (document: typeof PublishReportDocument | typeof InvalidateReportPublicationDocument, input: Record<string, unknown>) => { try { const result = await graphql(document as never, { input } as never); const payload = Object.values(result as Record<string, unknown>)[0] as { userErrors?: Array<{ message: string; code: string }> }; setMessage(payload.userErrors?.length ? formatMutationErrors(payload.userErrors) : "Publicação atualizada. Recarregue para confirmar o estado atual."); if (!payload.userErrors?.length) await open(); } catch (error) { setMessage(formatFailure(error)); } };
  const report = data?.report;
  return <div className="feature"><p>Downloads são somente PDF, com status observável, digest e expiração. Publicação e invalidação são versões separadas e a invalidação remove o acesso do cliente imediatamente.</p><button disabled={!inspectionId} onClick={() => void open()}>Abrir relatório</button><p role="status">{message}</p>{report && <article className="card"><strong>{report.classification} · versão {report.version}</strong><p>Digest canônico: {report.jsonDigest}</p><p>Digest renderizado: {report.htmlDigest}</p><button onClick={() => void prepareDownload()}>Preparar download PDF</button>{download && <div className="download-status"><p>PDF: {download.status}</p><p>Digest de integridade: {download.sha256 ?? "indisponível"}</p><p>Link autorizado expira 5 minutos após a emissão.</p>{download.url && <a href={download.url} target="_blank" rel="noreferrer">Baixar PDF</a>}</div>}<details><summary>Conteúdo canônico</summary><pre>{JSON.stringify(report.canonicalJSON, null, 2)}</pre></details>{canPublish && <div className="actions"><button onClick={() => void mutate(PublishReportDocument, { inspectionId: report.inspectionId, snapshotId: report.id, clientMutationId: mutationId() })}>Publicar relatório</button><button className="secondary" onClick={() => { const reason = window.prompt("Motivo da invalidação"); if (reason) void mutate(InvalidateReportPublicationDocument, { publicationId: report.id, expectedVersion: report.version, reason, clientMutationId: mutationId() }); }}>Invalidar publicação</button></div>}</article>}</div>;
}

function CustomerPortal({ section }: { section: Page }) {
  const params = useSearchParams(); const [message, setMessage] = useState("Esta experiência usa somente projeções de cliente aprovadas pelo servidor."); const [portfolio, setPortfolio] = useState<CustomerPortfolioQuery>();
  async function loadPortfolio(): Promise<CustomerPortfolioQuery> { return graphql<CustomerPortfolioQuery, { after: string | null }>(CustomerPortfolioDocument, { after: null }); }
  const load = async () => { try { const data = await loadPortfolio(); setPortfolio(data); setMessage(data.customerPortfolio.nodes.length ? "Portfólio autorizado atualizado." : "Ainda não há itens publicados para sua organização."); } catch { setMessage("Este conteúdo não está disponível no momento."); } };
  if (section === "Notificações") return null;
  if (section === "Relatórios") return <CustomerReportJourney inspectionId={params.get("inspectionId")} />;
  return <div className="feature"><p>Ativos, projetos e linha do tempo não são derivados de objetos internos no navegador. Estados indisponíveis não revelam recursos não autorizados.</p><button onClick={() => void load()}>Carregar portfólio</button><p role="status">{message}</p>{portfolio && <Collection items={portfolio.customerPortfolio.nodes.map((item) => ({ id: `${item.assetId}:${item.projectId ?? ""}`, title: `${item.status} · ${item.progress}%`, detail: item.publishedClassification ?? "Resultado ainda não publicado" }))} />}</div>;
}

function CustomerReportJourney({ inspectionId }: { inspectionId: string | null }) {
  const [message, setMessage] = useState("Selecione uma inspeção publicada para consultar resultado e evidências compartilhadas.");
  const load = async () => { if (!inspectionId) return; try { const [report, evidence] = await Promise.all([graphql(CustomerReportDocument, { inspectionId, version: null }), graphql(CustomerEvidenceDocument, { inspectionId, mode: "SIMPLE", after: null })]); setMessage(report.customerReport ? `${report.customerReport.classification}. ${evidence.customerEvidence.nodes.length} evidência(s) explicitamente compartilhada(s).` : "Este resultado não está disponível no momento."); } catch { setMessage("Este resultado não está disponível no momento."); } };
  return <div className="feature"><button disabled={!inspectionId} onClick={() => void load()}>Abrir resultado publicado</button><p role="status">{message}</p><p className="warning">URLs de mídia têm acesso temporário e são reautorizadas. Conteúdo invalidado, substituído ou indisponível não reaparece por uma versão anterior.</p></div>;
}

function NotificationCenter({ notifications }: { notifications: ReturnType<typeof useNotifications> }) {
  const [unreadOnly, setUnreadOnly] = useState(false);
  const visible = notifications.items.filter((item) => !unreadOnly || !item.readAt);
  return <div className="feature"><label><input type="checkbox" checked={unreadOnly} onChange={(event) => setUnreadOnly(event.target.checked)} /> Mostrar apenas não lidas</label>{visible.length ? <ul>{visible.map((notice) => <li key={notice.id}><strong>{notice.title}</strong><p>{notice.body}</p>{notice.readAt ? "Lida" : <button onClick={() => void notifications.markRead(notice.id)}>Marcar como lida</button>}</li>)}</ul> : <p role="status">Não há notificações neste filtro.</p>}<p>Links são autorizados novamente ao abrir. Preferências externas aceitam somente destinos verificados; avisos obrigatórios no produto permanecem ativos.</p></div>;
}

function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label>{label}<input type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} /></label>; }
function parseNumbers(value: string) { return value.split(",").map((part) => Number(part.trim())).filter((number) => Number.isFinite(number)); }
function mutationId() { return globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`; }
function formatMutationErrors(errors: Array<{ message: string; code: string }>) { const conflict = errors.find((error) => error.code === "CONFLICT" || error.code === "VERSION_CONFLICT"); return conflict ? `Conflito de versão: ${conflict.message} Recarregue os dados e tente novamente.` : errors.map((error) => error.message).join(" "); }
function formatFailure(error: unknown) { const failure = error as GraphQLFailure; return failure.code === "CONFLICT" || failure.code === "VERSION_CONFLICT" ? `Conflito de versão: ${failure.message} Recarregue os dados e tente novamente.` : failure.message ?? "Não foi possível concluir a operação."; }
async function requestRecapture(inspectionId: string, _version: number, setMessage: (message: string) => void) { const reason = window.prompt("Motivo da recaptura"); if (!reason) return; const deadlineAt = window.prompt("Prazo final (ISO 8601)", new Date(Date.now() + 86_400_000).toISOString()); if (!deadlineAt) return; const requirementKey = window.prompt("Requisito a recapturar"); if (!requirementKey) return; try { const result = await graphql(RequestRecaptureDocument, { input: { inspectionId, deadlineAt, items: [{ requirementKey, reason, originalMediaId: null }], clientMutationId: mutationId() } }); const errors = result.requestRecapture.userErrors; setMessage(errors.length ? formatMutationErrors(errors) : "Recaptura solicitada; o participante verá o novo requisito após a atualização."); } catch (error) { setMessage(formatFailure(error)); } }

function Collection({ items }: { items: Array<{ id: string; title: string; detail: string }> }) { return items.length ? <ul className="collection">{items.map((item) => <li key={item.id}><strong>{item.title}</strong><span>{item.detail}</span></li>)}</ul> : <p role="status">Nenhum resultado encontrado.</p>; }
