"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { beginPKCE } from "@/auth/pkce";
import { safeDashboardPath } from "@/auth/return-path";
import { hasDashboardAccess, setIdentity, type DashboardIdentity } from "@/auth/session";
import { composeCapabilities, type Capability } from "@/features/dashboard/capabilities";
import { useNotifications } from "@/features/notifications/use-notifications";
import { graphql, type GraphQLFailure } from "@/graphql/client";

type Gate = { me: { tenantId: string; productEntitlements: string[]; roles: string[]; effectiveScopes: Array<{ kind: string; resourceId: string }> }; tenant: { id: string; name: string; status: string } | null };
type InternalHome = { dashboardSummary: { total: number; normal: number; attention: number; critical: number; pending: number; invalidated: number }; triageInspections: { nodes: Array<{ inspectionId: string; projectId: string | null; assetId: string | null; classification: string; status: string; updatedAt: string }> } };
type CustomerHome = { customerPortfolio: { nodes: Array<{ assetId: string; projectId: string | null; publishedClassification: string | null; status: string; progress: number; updatedAt: string }> } };
const gateQuery = "query DashboardGate { me { tenantId productEntitlements roles effectiveScopes { kind resourceId } } tenant { id name status } }";

export function DashboardShell({ section }: { section: string }) {
  const pathname = usePathname(); const router = useRouter();
  const [identity, setCurrentIdentity] = useState<DashboardIdentity>(); const [capability, setCapability] = useState<Capability>(); const [status, setStatus] = useState("Verificando acesso…");
  const loadGate = async () => { try { const { me, tenant } = await graphql<Gate>(gateQuery); const current = { tenantId: me.tenantId, tenantName: tenant?.name ?? "Tenant", tenantStatus: tenant?.status ?? "INACTIVE", entitlements: me.productEntitlements, roles: me.roles, scopes: me.effectiveScopes }; setIdentity(current); if (!hasDashboardAccess(current)) { setCurrentIdentity(undefined); setCapability(undefined); setStatus("Acesso ao Dashboard não autorizado. Nenhum dado operacional foi carregado."); return; } setCurrentIdentity(current); setCapability(composeCapabilities(current)); setStatus(tenant?.name ?? "Tenant"); } catch (error) { setCurrentIdentity(undefined); setCapability(undefined); const failure = error as GraphQLFailure; setStatus(["FORBIDDEN", "UNAUTHENTICATED", "TENANT_INACTIVE"].includes(failure.code ?? "") ? "Acesso ao Dashboard não autorizado. Nenhum dado operacional foi carregado." : failure.message); } };
  useEffect(() => { void loadGate(); }, []); // every route entry obtains current membership state
  const notifications = useNotifications(Boolean(identity));
  const signIn = () => void beginPKCE(process.env.NEXT_PUBLIC_OIDC_AUTHORIZE_URL ?? "http://localhost:8081/realms/inspection/protocol/openid-connect/auth", pathname);
  if (!identity || !capability) return <main className="denial"><h1>Dashboard</h1><p role="status">{status}</p><button onClick={signIn}>Entrar no Dashboard</button></main>;
  return <main><header><strong>Inspeção · Dashboard</strong><span>{status}</span><div className="actions">{capability.canUseAdmin && <a href={process.env.NEXT_PUBLIC_ADMIN_URL ?? "http://localhost:3000"}>Abrir Administração</a>}<Link href="/notifications">Notificações ({notifications.unreadCount})</Link></div></header><nav aria-label="Dashboard">{capability.links.map(([label, href]) => <Link key={href} aria-current={pathname === href ? "page" : undefined} href={href}>{label}</Link>)}</nav><section><div className="actions"><h1>{section}</h1><button className="secondary" onClick={() => { void loadGate(); void notifications.refresh(); router.refresh(); }}>Atualizar</button></div>{notifications.error && <p className="warning" role="status">Dados já exibidos podem estar desatualizados. {notifications.error}</p>}{capability.audience === "customer" ? <CustomerContent section={section} notificationItems={notifications.items} markRead={notifications.markRead} /> : <InternalContent section={section} capability={capability} />}</section></main>;
}

function InternalContent({ section, capability }: { section: string; capability: Capability }) {
  const [result, setResult] = useState<InternalHome>(); const [message, setMessage] = useState("Carregue o resumo atual para este escopo."); const [classification, setClassification] = useState("");
  const load = async () => { try { const data = await graphql<InternalHome>("query InternalHome($classification:String){ dashboardSummary { total normal attention critical pending invalidated } triageInspections(first:25,classification:$classification){ nodes { inspectionId projectId assetId classification status updatedAt } } }", { classification: classification || null }); setResult(data); setMessage(data.triageInspections.nodes.length ? "Prioridades atualizadas." : "Não há trabalho correspondente neste escopo."); } catch (error) { setMessage(`Dados exibidos podem estar desatualizados. ${(error as Error).message}`); } };
  return <div className="feature"><p>{capability.home}. Filtros e destinos mantêm apenas o contexto já autorizado pelo servidor.</p><label>Classificação <select value={classification} onChange={(event) => setClassification(event.target.value)}><option value="">Todas</option><option value="CRITICAL">Crítica</option><option value="ATTENTION">Atenção</option></select></label><button onClick={() => void load()}>Atualizar prioridades</button><p role="status">{message}</p>{result && <><div className="cards">{Object.entries(result.dashboardSummary).map(([name, value]) => <div className="card" key={name}><strong>{name}</strong><div>{value}</div></div>)}</div><ol>{result.triageInspections.nodes.map((item) => <li key={item.inspectionId}><Link href={safeDashboardPath(`/inspections?inspectionId=${encodeURIComponent(item.inspectionId)}`)}>{item.classification} · {item.status}</Link> — atualizado em {item.updatedAt}</li>)}</ol></>}{capability.canMutate && <OperationActions canPublish={capability.canPublish} section={section} />}</div>;
}

function OperationActions({ canPublish, section }: { canPublish: boolean; section: string }) {
  const [message, setMessage] = useState("");
  return <div className="feature"><h2>Ações operacionais</h2><p>Criação, cancelamento, etapas e recaptura exigem o recurso, versão atual, motivo quando necessário e identificador idempotente. O servidor confirma escopo e estado antes de alterar dados.</p><div className="actions"><button onClick={() => setMessage("Selecione uma inspeção ou projeto para iniciar uma ação autorizada.")}>Nova ação</button>{canPublish && <button onClick={() => setMessage("Selecione um relatório final para publicar ou invalidar com motivo e versão atual.")}>Publicar relatório</button>}</div>{message && <p role="status">{message}</p>}<p>Se uma ação assíncrona for aceita, o resultado exibirá: aceito, pendente, concluído ou falhou.</p><p className="warning">{section === "Relatórios" ? "Versões históricas permanecem identificadas como históricas; a publicação atual não é confundida com versões anteriores." : "Ações destrutivas mostram alvo, consequência e motivo antes da confirmação."}</p></div>;
}

function CustomerContent({ section, notificationItems, markRead }: { section: string; notificationItems: Array<{ id: string; title: string; body: string; resourceKind: string; resourceId: string | null; readAt: string | null }>; markRead: (id: string) => Promise<void> }) {
  const [portfolio, setPortfolio] = useState<CustomerHome>(); const [message, setMessage] = useState("Selecione um ativo ou projeto compartilhado para acompanhar o progresso."); const [advanced, setAdvanced] = useState(false);
  const load = async () => { try { const data = await graphql<CustomerHome>("query CustomerHome { customerPortfolio(first:25){ nodes { assetId projectId publishedClassification status progress updatedAt } } }"); setPortfolio(data); setMessage(data.customerPortfolio.nodes.length ? "Portfólio atualizado." : "Ainda não há inspeções para os ativos compartilhados."); } catch (error) { setMessage((error as Error).message); } };
  if (section === "Notificações") return <div className="feature"><p>Notificações mostram apenas status e destinos que continuam autorizados. A leitura é idempotente e as entregas anteriores não são alteradas.</p>{notificationItems.length ? <ul>{notificationItems.map((notice) => <li key={notice.id}><strong>{notice.title}</strong><p>{notice.body}</p>{notice.readAt ? "Lida" : <button onClick={() => void markRead(notice.id)}>Marcar como lida</button>}</li>)}</ul> : <p role="status">Não há notificações no momento.</p>}<NotificationPreferences /></div>;
  if (section === "Relatórios") return <div className="feature"><p>Resultados publicados são exibidos em modo simples por padrão. Relatórios não publicados, notas internas e campos internos não são consultados nesta experiência.</p><label><input type="checkbox" checked={advanced} onChange={(event) => setAdvanced(event.target.checked)} /> Ver histórico avançado de evidências</label><p>{advanced ? "O histórico avançado agrupa linhagem por requisito, etapa e versão; evidência sensível bloqueada mostra apenas estado e motivo seguro, sem visual." : "O modo simples destaca resultado atual, contexto, aviso consultivo e versão publicada atual."}</p><p className="warning">Uma versão solicitada explicitamente é identificada como histórica e não substitui o resultado publicado atual.</p></div>;
  return <div className="feature"><p>Ativos e projetos compartilhados são a porta de entrada. O progresso é cronológico e não inclui notas internas ou resultado não publicado.</p><button onClick={() => void load()}>Carregar portfólio</button><p role="status">{message}</p>{portfolio && <div className="cards">{portfolio.customerPortfolio.nodes.map((item) => <article className="card" key={`${item.assetId}:${item.projectId ?? ""}`}><strong>Ativo {item.assetId}</strong><p>Progresso: {item.progress}%</p><p>Status: {item.status}</p><p>{item.publishedClassification ? `Resultado publicado: ${item.publishedClassification}` : "Resultado ainda não publicado"}</p><Link href={safeDashboardPath(`/portfolio?assetId=${encodeURIComponent(item.assetId)}`)}>Ver linha do tempo</Link></article>)}</div>}</div>;
}

function NotificationPreferences() {
  const [channels, setChannels] = useState(""); const [version, setVersion] = useState(""); const [message, setMessage] = useState("");
  const save = async () => { const clientMutationId = crypto.randomUUID(); try { await graphql("mutation ConfigureNotificationPreferences($input:ConfigureNotificationPreferencesInput!){ configureMyNotificationPreferences(input:$input){ userErrors { field message } } }", { input: { channels: channels.split(",").map((value) => value.trim()).filter(Boolean), expectedVersion: Number(version), clientMutationId } }, clientMutationId); setMessage("Preferências enviadas. Apenas canais verificados podem ser selecionados; notificações no produto continuam ativas."); } catch (error) { setMessage((error as Error).message); } };
  return <fieldset><legend>Preferências de canais externos verificados</legend><label>IDs dos canais separados por vírgula <input value={channels} onChange={(event) => setChannels(event.target.value)} /></label><label>Versão atual <input inputMode="numeric" value={version} onChange={(event) => setVersion(event.target.value)} /></label><button disabled={!version} onClick={() => void save()}>Salvar preferências</button>{message && <p role="status">{message}</p>}</fieldset>;
}
