"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { beginPKCE } from "@/auth/pkce";
import { safeDashboardPath } from "@/auth/return-path";
import { hasDashboardAccess, setIdentity, type DashboardIdentity } from "@/auth/session";
import { composeCapabilities, type Capability } from "@/features/dashboard/capabilities";
import { useNotifications } from "@/features/notifications/use-notifications";
import { graphql, type GraphQLFailure } from "@/graphql/client";

type Gate = { me: { tenantId: string; productEntitlements: string[]; roles: string[]; effectiveScopes: Array<{ kind: string; resourceId: string }> }; tenant: { id: string; name: string; status: string } | null };
type InternalHome = { dashboardSummary: { total: number; normal: number; attention: number; critical: number; pending: number; invalidated: number }; triageInspections: { nodes: Array<{ inspectionId: string; projectId: string | null; assetId: string | null; classification: string; status: string; updatedAt: string }> } };
type CustomerHome = { customerPortfolio: { nodes: Array<{ assetId: string; projectId: string | null; publishedClassification: string | null; status: string; progress: number; updatedAt: string }> } };
type InspectionDetail = { inspection: { id: string; assetId: string; participantId: string; projectId: string | null; status: string; evidenceCount: number; dueAt: string; deadlineAt: string; stateReason: string | null; version: number } | null };
type ProjectDetail = { project: { id: string; assetId: string; participantId: string; status: string; version: number; stages: Array<{ id: string; label: string; status: string; inspectionId: string | null }> } | null };
const gateQuery = "query DashboardGate { me { tenantId productEntitlements roles effectiveScopes { kind resourceId } } tenant { id name status } }";

export function DashboardShell({ section }: { section: string }) {
  const pathname = usePathname(); const router = useRouter();
  const [identity, setCurrentIdentity] = useState<DashboardIdentity>(); const [capability, setCapability] = useState<Capability>(); const [status, setStatus] = useState("Verificando acesso…");
  const loadGate = async () => { try { const { me, tenant } = await graphql<Gate>(gateQuery); const current = { tenantId: me.tenantId, tenantName: tenant?.name ?? "Tenant", tenantStatus: tenant?.status ?? "INACTIVE", entitlements: me.productEntitlements, roles: me.roles, scopes: me.effectiveScopes }; setIdentity(current); if (!hasDashboardAccess(current)) { setCurrentIdentity(undefined); setCapability(undefined); setStatus("Acesso ao Dashboard não autorizado. Nenhum dado operacional foi carregado."); return; } setCurrentIdentity(current); setCapability(composeCapabilities(current)); setStatus(tenant?.name ?? "Tenant"); } catch (error) { setCurrentIdentity(undefined); setCapability(undefined); const failure = error as GraphQLFailure; setStatus(["FORBIDDEN", "UNAUTHENTICATED", "TENANT_INACTIVE"].includes(failure.code ?? "") ? "Acesso ao Dashboard não autorizado. Nenhum dado operacional foi carregado." : failure.message); } };
  useEffect(() => { void loadGate(); }, []); // every route entry obtains current membership state
  const notifications = useNotifications(Boolean(identity));
  const signIn = () => void beginPKCE(process.env.NEXT_PUBLIC_OIDC_AUTHORIZE_URL ?? "http://localhost:8081/realms/inspection/protocol/openid-connect/auth", pathname);
  if (!identity || !capability) return <main className="denial"><h1>Dashboard</h1><p role="status">{status}</p><button onClick={signIn}>Entrar no Dashboard</button></main>;
  return <main><header><strong>Inspeção · Dashboard</strong><span>{status}</span><div className="actions">{capability.canUseAdmin && <a href={process.env.NEXT_PUBLIC_ADMIN_URL ?? "http://localhost:3000"}>Abrir Administração</a>}<Link href="/notifications">Notificações ({notifications.unreadCount})</Link></div></header><nav aria-label="Dashboard">{capability.links.map(([label, href]) => <Link key={href} aria-current={pathname === href ? "page" : undefined} href={href}>{label}</Link>)}</nav><section><div className="actions"><h1>{section}</h1><button className="secondary" onClick={() => { void loadGate(); void notifications.refresh(); router.refresh(); }}>Atualizar</button></div>{notifications.error && <p className="warning" role="status">Dados já exibidos podem estar desatualizados. {notifications.error}</p>}{capability.audience === "customer" ? <CustomerContent section={section} notificationItems={notifications.items} markRead={notifications.markRead} /> : <InternalContent section={section} capability={capability} notificationItems={notifications.items} markRead={notifications.markRead} />}</section></main>;
}

function InternalContent({ section, capability, notificationItems, markRead }: { section: string; capability: Capability; notificationItems: Array<{ id: string; title: string; body: string; readAt: string | null }>; markRead: (id: string) => Promise<void> }) {
  const searchParams = useSearchParams(); const selectedInspectionId = searchParams.get("inspectionId");
  const [result, setResult] = useState<InternalHome>(); const [message, setMessage] = useState("Carregue o resumo atual para este escopo."); const [classification, setClassification] = useState(""); const [detail, setDetail] = useState<InspectionDetail["inspection"]>(); const [project, setProject] = useState<ProjectDetail["project"]>(); const [detailMessage, setDetailMessage] = useState("");
  const load = async () => { try { const data = await graphql<InternalHome>("query InternalHome($classification:String){ dashboardSummary { total normal attention critical pending invalidated } triageInspections(first:25,classification:$classification){ nodes { inspectionId projectId assetId classification status updatedAt } } }", { classification: classification || null }); setResult(data); setMessage(data.triageInspections.nodes.length ? "Prioridades atualizadas." : "Não há trabalho correspondente neste escopo."); } catch (error) { setMessage(`Dados exibidos podem estar desatualizados. ${(error as Error).message}`); } };
  useEffect(() => { if (!selectedInspectionId) { setDetail(undefined); setProject(undefined); return; } void (async () => { try { const data = await graphql<InspectionDetail>("query InspectionDetail($id:ID!){ inspection(id:$id){ id assetId participantId projectId status evidenceCount dueAt deadlineAt stateReason version } }", { id: selectedInspectionId }); setDetail(data.inspection); if (data.inspection?.projectId) { const projectData = await graphql<ProjectDetail>("query ProjectDetail($id:ID!){ project(id:$id){ id assetId participantId status version stages { id label status inspectionId } } }", { id: data.inspection.projectId }); setProject(projectData.project); } setDetailMessage(data.inspection ? "Detalhes atualizados." : "A inspeção selecionada não foi encontrada."); } catch (error) { setDetailMessage((error as GraphQLFailure).message ?? "Não foi possível carregar os detalhes."); } })(); }, [selectedInspectionId]);
  if (section === "Notificações") return <div className="feature"><h2>Notificações</h2>{notificationItems.length ? <ul>{notificationItems.map((notice) => <li key={notice.id}><strong>{notice.title}</strong><p>{notice.body}</p>{notice.readAt ? "Lida" : <button onClick={() => void markRead(notice.id)}>Marcar como lida</button>}</li>)}</ul> : <p role="status">Não há notificações no momento.</p>}<NotificationPreferences /></div>;
  return <div className="feature"><p>{capability.home}. Filtros e destinos mantêm apenas o contexto já autorizado pelo servidor.</p><label>Classificação <select value={classification} onChange={(event) => setClassification(event.target.value)}><option value="">Todas</option><option value="CRITICAL">Crítica</option><option value="ATTENTION">Atenção</option></select></label><button onClick={() => void load()}>Atualizar prioridades</button><p role="status">{message}</p>{result && <><div className="cards">{Object.entries(result.dashboardSummary).map(([name, value]) => <div className="card" key={name}><strong>{name}</strong><div>{value}</div></div>)}</div><ol>{result.triageInspections.nodes.map((item) => <li key={item.inspectionId}><Link href={safeDashboardPath(`/inspections?inspectionId=${encodeURIComponent(item.inspectionId)}`)}>{item.classification} · {item.status}</Link> — atualizado em {item.updatedAt}</li>)}</ol></>}{selectedInspectionId && <section className="card"><h2>Detalhes da inspeção</h2><p role="status">{detailMessage}</p>{detail && <><dl><dt>Status</dt><dd>{detail.status}</dd><dt>Evidências</dt><dd>{detail.evidenceCount}</dd><dt>Prazo</dt><dd>{detail.deadlineAt}</dd><dt>Motivo</dt><dd>{detail.stateReason ?? "—"}</dd></dl>{project && <><h3>Projeto</h3><p>{project.status} · {project.stages.length} etapa(s)</p><ul>{project.stages.map((stage) => <li key={stage.id}>{stage.label}: {stage.status}</li>)}</ul></>}</>}</section>}{capability.canMutate && <OperationActions canPublish={capability.canPublish} section={section} inspection={detail} />}</div>;
}

function OperationActions({ canPublish, section, inspection }: { canPublish: boolean; section: string; inspection?: InspectionDetail["inspection"] }) {
  const [action, setAction] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const execute = async () => {
    if (!inspection) { setMessage("Abra uma inspeção para escolher uma ação operacional."); return; }
    setBusy(true);
    try {
      if (action === "cancel") {
        const result = await graphql<{ cancelInspection: { userErrors: Array<{ message: string }> } }>("mutation CancelInspection($input:InspectionTransitionInput!){ cancelInspection(input:$input){ userErrors { message } } }", { input: { inspectionId: inspection.id, expectedVersion: inspection.version, clientMutationId: crypto.randomUUID() } });
        if (result.cancelInspection.userErrors[0]) throw new Error(result.cancelInspection.userErrors[0].message);
        setMessage("Inspeção cancelada com sucesso.");
      } else if (action === "publish") {
        const report = await graphql<{ report: { id: string; inspectionId: string } | null }>("query ReportForPublication($id:ID!){ report(inspectionId:$id){ id inspectionId } }", { id: inspection.id });
        if (!report.report) throw new Error("Não há relatório final disponível para publicação.");
        const result = await graphql<{ publishReport: { publication: { status: string } | null; userErrors: Array<{ message: string }> } }>("mutation PublishReport($input:PublishReportInput!){ publishReport(input:$input){ publication { status } userErrors { message } } }", { input: { inspectionId: inspection.id, snapshotId: report.report.id, clientMutationId: crypto.randomUUID() } });
        if (result.publishReport.userErrors[0]) throw new Error(result.publishReport.userErrors[0].message);
        setMessage(`Relatório ${result.publishReport.publication?.status ?? "aceito"}.`);
      } else setMessage("Escolha uma ação e confirme para executar a operação.");
    } catch (error) { setMessage((error as GraphQLFailure).message ?? "Não foi possível executar a ação."); } finally { setBusy(false); }
  };
  return <div className="feature"><h2>Ações operacionais</h2><p>As operações usam o recurso selecionado, a versão atual e uma chave idempotente.</p><label>Ação <select value={action} onChange={(event) => setAction(event.target.value)}><option value="">Selecione</option><option value="cancel">Cancelar inspeção</option>{canPublish && <option value="publish">Publicar relatório</option>}</select></label><button disabled={busy} onClick={() => void execute()}>{busy ? "Executando…" : "Nova ação"}</button>{message && <p role="status">{message}</p>}<p className="warning">{section === "Relatórios" ? "Publicações e invalidações mantêm versões históricas identificadas." : "Ações destrutivas confirmam o alvo e a versão antes da alteração."}</p></div>;
}

function CustomerContent({ section, notificationItems, markRead }: { section: string; notificationItems: Array<{ id: string; title: string; body: string; resourceKind: string; resourceId: string | null; readAt: string | null }>; markRead: (id: string) => Promise<void> }) {
  const [portfolio, setPortfolio] = useState<CustomerHome>(); const [message, setMessage] = useState("Selecione um ativo ou projeto compartilhado para acompanhar o progresso."); const [advanced, setAdvanced] = useState(false);
  const load = async () => { try { const data = await graphql<CustomerHome>("query CustomerHome { customerPortfolio(first:25){ nodes { assetId projectId publishedClassification status progress updatedAt } } }"); setPortfolio(data); setMessage(data.customerPortfolio.nodes.length ? "Portfólio atualizado." : "Ainda não há inspeções para os ativos compartilhados."); } catch (error) { setMessage((error as Error).message); } };
  if (section === "Notificações") return <div className="feature"><p>Notificações mostram apenas status e destinos que continuam autorizados. A leitura é idempotente e as entregas anteriores não são alteradas.</p>{notificationItems.length ? <ul>{notificationItems.map((notice) => <li key={notice.id}><strong>{notice.title}</strong><p>{notice.body}</p>{notice.readAt ? "Lida" : <button onClick={() => void markRead(notice.id)}>Marcar como lida</button>}</li>)}</ul> : <p role="status">Não há notificações no momento.</p>}<NotificationPreferences /></div>;
  if (section === "Relatórios") return <div className="feature"><p>Resultados publicados são exibidos em modo simples por padrão. Relatórios não publicados, notas internas e campos internos não são consultados nesta experiência.</p><label><input type="checkbox" checked={advanced} onChange={(event) => setAdvanced(event.target.checked)} /> Ver histórico avançado de evidências</label><p>{advanced ? "O histórico avançado agrupa linhagem por requisito, etapa e versão; evidência sensível bloqueada mostra apenas estado e motivo seguro, sem visual." : "O modo simples destaca resultado atual, contexto, aviso consultivo e versão publicada atual."}</p><p className="warning">Uma versão solicitada explicitamente é identificada como histórica e não substitui o resultado publicado atual.</p></div>;
  return <div className="feature"><p>Ativos e projetos compartilhados são a porta de entrada. O progresso é cronológico e não inclui notas internas ou resultado não publicado.</p><button onClick={() => void load()}>Carregar portfólio</button><p role="status">{message}</p>{portfolio && <div className="cards">{portfolio.customerPortfolio.nodes.map((item) => <article className="card" key={`${item.assetId}:${item.projectId ?? ""}`}><strong>Ativo {item.assetId}</strong><p>Progresso: {item.progress}%</p><p>Status: {item.status}</p><p>{item.publishedClassification ? `Resultado publicado: ${item.publishedClassification}` : "Resultado ainda não publicado"}</p><Link href={safeDashboardPath(`/portfolio?assetId=${encodeURIComponent(item.assetId)}`)}>Ver linha do tempo</Link></article>)}</div>}</div>;
}

function NotificationPreferences() {
  const [channels, setChannels] = useState(""); const [version, setVersion] = useState(""); const [message, setMessage] = useState("");
  const save = async () => { const clientMutationId = crypto.randomUUID(); try { await graphql("mutation ConfigureNotificationPreferences($input:ConfigureNotificationPreferencesInput!){ configureMyNotificationPreferences(input:$input){ userErrors { field message } } }", { input: { channels: channels.split(",").map((value) => value.trim()).filter(Boolean), expectedVersion: Number(version), clientMutationId } }, clientMutationId); setMessage("Preferências enviadas. Apenas canais verificados podem ser selecionados; notificações no produto continuam ativas."); } catch (error) { setMessage((error as Error).message); } };
  return <fieldset><legend>Preferências de canais externos verificados</legend><label>IDs dos canais separados por vírgula <input value={channels} onChange={(event) => setChannels(event.target.value)} /></label><label>Versão atual <input inputMode="numeric" value={version} onChange={(event) => setVersion(event.target.value)} /></label><button disabled={!version} onClick={() => void save()}>Salvar preferências</button>{message && <p role="status">{message}</p>}</fieldset>;
}
