// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AcceptProcessingInput struct {
	DisclosureVersion string `json:"disclosureVersion"`
	PhotoProcessing   bool   `json:"photoProcessing"`
	AiAnalysis        bool   `json:"aiAnalysis"`
	GpsUse            bool   `json:"gpsUse"`
	ClientMutationID  string `json:"clientMutationId"`
}

type ActivateSegmentDefinitionInput struct {
	VersionID        string `json:"versionId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type ActivateTemplateVersionInput struct {
	VersionID        string `json:"versionId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type AddExceptionalStageInput struct {
	ProjectID        string  `json:"projectId"`
	ExpectedVersion  int     `json:"expectedVersion"`
	Key              string  `json:"key"`
	Label            string  `json:"label"`
	Reason           string  `json:"reason"`
	PlannedAt        *string `json:"plannedAt,omitempty"`
	ClientMutationID string  `json:"clientMutationId"`
}

type AnalysisProfile struct {
	ID              string         `json:"id"`
	Key             string         `json:"key"`
	VersionNumber   int            `json:"versionNumber"`
	SchemaVersion   int            `json:"schemaVersion"`
	Definition      map[string]any `json:"definition"`
	CanonicalDigest string         `json:"canonicalDigest"`
	Status          string         `json:"status"`
	PublishedAt     string         `json:"publishedAt"`
}

type AnalysisProfilePayload struct {
	Profile          *AnalysisProfile `json:"profile,omitempty"`
	UserErrors       []*UserError     `json:"userErrors"`
	ClientMutationID string           `json:"clientMutationId"`
}

type ArchiveAssetInput struct {
	AssetID          string `json:"assetId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type ArchiveBusinessUnitInput struct {
	BusinessUnitID   string `json:"businessUnitId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type Asset struct {
	ID               string             `json:"id"`
	BusinessUnitID   string             `json:"businessUnitId"`
	SegmentVersionID string             `json:"segmentVersionId"`
	TemplateID       *string            `json:"templateId,omitempty"`
	Name             string             `json:"name"`
	ExternalKey      string             `json:"externalKey"`
	Address          string             `json:"address"`
	LatitudeE6       *int               `json:"latitudeE6,omitempty"`
	LongitudeE6      *int               `json:"longitudeE6,omitempty"`
	GeofenceMeters   int                `json:"geofenceMeters"`
	Attributes       map[string]any     `json:"attributes"`
	PolicyOverrides  map[string]any     `json:"policyOverrides"`
	Status           string             `json:"status"`
	Version          int                `json:"version"`
	Assignments      []*AssetAssignment `json:"assignments"`
}

type AssetAssignment struct {
	ParticipantID string `json:"participantId"`
	Role          string `json:"role"`
	Active        bool   `json:"active"`
}

type AssetAssignmentInput struct {
	ParticipantID string `json:"participantId"`
	Role          string `json:"role"`
}

type AssetConnection struct {
	Nodes    []*Asset  `json:"nodes"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type AssetInput struct {
	BusinessUnitID   string                  `json:"businessUnitId"`
	SegmentVersionID string                  `json:"segmentVersionId"`
	TemplateID       *string                 `json:"templateId,omitempty"`
	Name             string                  `json:"name"`
	ExternalKey      string                  `json:"externalKey"`
	Address          string                  `json:"address"`
	LatitudeE6       *int                    `json:"latitudeE6,omitempty"`
	LongitudeE6      *int                    `json:"longitudeE6,omitempty"`
	GeofenceMeters   *int                    `json:"geofenceMeters,omitempty"`
	Attributes       map[string]any          `json:"attributes"`
	PolicyOverrides  map[string]any          `json:"policyOverrides,omitempty"`
	Assignments      []*AssetAssignmentInput `json:"assignments"`
}

type AssetPayload struct {
	Asset            *Asset       `json:"asset,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type AssignRoleScopesInput struct {
	MembershipID     string                  `json:"membershipId"`
	Role             string                  `json:"role"`
	Scopes           []*ScopeAssignmentInput `json:"scopes"`
	ExpectedVersion  *int                    `json:"expectedVersion,omitempty"`
	ClientMutationID string                  `json:"clientMutationId"`
}

type AuditEvent struct {
	ID            string  `json:"id"`
	Action        string  `json:"action"`
	TargetType    string  `json:"targetType"`
	TargetID      string  `json:"targetId"`
	Outcome       string  `json:"outcome"`
	Reason        *string `json:"reason,omitempty"`
	CorrelationID string  `json:"correlationId"`
	OccurredAt    string  `json:"occurredAt"`
}

type AuditEventConnection struct {
	Nodes    []*AuditEvent `json:"nodes"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type BusinessUnit struct {
	ID      string `json:"id"`
	Code    string `json:"code"`
	Name    string `json:"name"`
	Status  string `json:"status"`
	Version int    `json:"version"`
}

type BusinessUnitConnection struct {
	Nodes    []*BusinessUnit `json:"nodes"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type BusinessUnitPayload struct {
	BusinessUnit     *BusinessUnit `json:"businessUnit,omitempty"`
	UserErrors       []*UserError  `json:"userErrors"`
	ClientMutationID string        `json:"clientMutationId"`
}

type CancelScheduleInput struct {
	ScheduleID       string `json:"scheduleId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type CaptureAnswer struct {
	RequirementKey      string   `json:"requirementKey"`
	MediaIds            []string `json:"mediaIds"`
	ImpossibilityReason *string  `json:"impossibilityReason,omitempty"`
	Version             int      `json:"version"`
}

type CaptureGPSInput struct {
	Latitude        float64 `json:"latitude"`
	Longitude       float64 `json:"longitude"`
	AccuracyMeters  float64 `json:"accuracyMeters"`
	CapturedAt      string  `json:"capturedAt"`
	WindowStartedAt string  `json:"windowStartedAt"`
}

type CapturePayload struct {
	Status           string       `json:"status"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type CaptureRequirement struct {
	Key                  string  `json:"key"`
	Section              string  `json:"section"`
	Label                string  `json:"label"`
	Instructions         *string `json:"instructions,omitempty"`
	EvidenceKind         string  `json:"evidenceKind"`
	Required             bool    `json:"required"`
	MinimumMedia         int     `json:"minimumMedia"`
	MaximumMedia         int     `json:"maximumMedia"`
	DescriptionRequired  bool    `json:"descriptionRequired"`
	CaptureSourcePolicy  string  `json:"captureSourcePolicy"`
	ComparisonTarget     string  `json:"comparisonTarget"`
	ImpossibilityAllowed bool    `json:"impossibilityAllowed"`
}

type CompleteMediaUploadInput struct {
	MediaID          string                `json:"mediaId"`
	Parts            []*CompletedPartInput `json:"parts"`
	ClientMutationID string                `json:"clientMutationId"`
}

type CompletedPartInput struct {
	PartNumber int    `json:"partNumber"`
	Etag       string `json:"etag"`
}

type ConfigureNotificationPreferencesInput struct {
	Channels         []string `json:"channels"`
	ExpectedVersion  int      `json:"expectedVersion"`
	ClientMutationID string   `json:"clientMutationId"`
}

type ConfigurePublicationPolicyInput struct {
	Mode             string `json:"mode"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type ConfigureRetentionPolicyInput struct {
	EvidenceDays     int    `json:"evidenceDays"`
	OperationalDays  int    `json:"operationalDays"`
	SecurityDays     *int   `json:"securityDays,omitempty"`
	ClientMutationID string `json:"clientMutationId"`
}

type ContactInput struct {
	Channel string `json:"channel"`
	Value   string `json:"value"`
}

type CreateBusinessUnitInput struct {
	Code                  string `json:"code"`
	Name                  string `json:"name"`
	ExpectedTenantVersion int    `json:"expectedTenantVersion"`
	ClientMutationID      string `json:"clientMutationId"`
}

type CreateInspectionInput struct {
	AssetID            string   `json:"assetId"`
	ParticipantID      string   `json:"participantId"`
	TemplateID         *string  `json:"templateId,omitempty"`
	ReferenceVersionID *string  `json:"referenceVersionId,omitempty"`
	DueAt              string   `json:"dueAt"`
	DeadlineAt         string   `json:"deadlineAt"`
	ReminderInstants   []string `json:"reminderInstants"`
	Reason             string   `json:"reason"`
	ClientMutationID   string   `json:"clientMutationId"`
}

type CreateMediaUploadInput struct {
	ContentType      string `json:"contentType"`
	SizeBytes        int    `json:"sizeBytes"`
	Sha256           string `json:"sha256"`
	ClientMutationID string `json:"clientMutationId"`
}

type CreateProjectInput struct {
	AssetID          string  `json:"assetId"`
	ParticipantID    string  `json:"participantId"`
	TemplateID       *string `json:"templateId,omitempty"`
	ClientMutationID string  `json:"clientMutationId"`
}

type CreateScheduleInput struct {
	AssetID                string  `json:"assetId"`
	ParticipantID          string  `json:"participantId"`
	TemplateID             string  `json:"templateId"`
	ReferenceVersionID     *string `json:"referenceVersionId,omitempty"`
	Rrule                  string  `json:"rrule"`
	Timezone               string  `json:"timezone"`
	StartsAt               string  `json:"startsAt"`
	DeadlineMinutes        int     `json:"deadlineMinutes"`
	ReminderOffsetsMinutes []int   `json:"reminderOffsetsMinutes"`
	ClientMutationID       string  `json:"clientMutationId"`
}

type CreateTenantInput struct {
	Name             string  `json:"name"`
	Language         *string `json:"language,omitempty"`
	Timezone         *string `json:"timezone,omitempty"`
	BusinessUnitCode string  `json:"businessUnitCode"`
	BusinessUnitName string  `json:"businessUnitName"`
	ClientMutationID string  `json:"clientMutationId"`
}

type CreateTenantPayload struct {
	Tenant           *Tenant      `json:"tenant,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type CustomerEvidenceConnection struct {
	Nodes    []*CustomerEvidenceItem `json:"nodes"`
	PageInfo *PageInfo               `json:"pageInfo"`
}

type CustomerEvidenceItem struct {
	ID                string  `json:"id"`
	RequirementKey    string  `json:"requirementKey"`
	Description       *string `json:"description,omitempty"`
	CaptureSource     *string `json:"captureSource,omitempty"`
	State             string  `json:"state"`
	LineageID         string  `json:"lineageId"`
	ReplacedBy        *string `json:"replacedBy,omitempty"`
	MediaAvailability string  `json:"mediaAvailability"`
	URL               *string `json:"url,omitempty"`
}

type CustomerPortfolioConnection struct {
	Nodes    []*CustomerPortfolioItem `json:"nodes"`
	PageInfo *PageInfo                `json:"pageInfo"`
}

type CustomerPortfolioFilter struct {
	AssetID   *string `json:"assetId,omitempty"`
	ProjectID *string `json:"projectId,omitempty"`
	Search    *string `json:"search,omitempty"`
}

type CustomerPortfolioItem struct {
	AssetID                 string  `json:"assetId"`
	ProjectID               *string `json:"projectId,omitempty"`
	PublishedClassification *string `json:"publishedClassification,omitempty"`
	Status                  string  `json:"status"`
	Progress                int     `json:"progress"`
	UpdatedAt               string  `json:"updatedAt"`
}

type CustomerReport struct {
	InspectionID   string `json:"inspectionId"`
	SnapshotID     string `json:"snapshotId"`
	Version        int    `json:"version"`
	Classification string `json:"classification"`
	Advisory       string `json:"advisory"`
	Status         string `json:"status"`
	Historical     bool   `json:"historical"`
}

type CustomerTimelineConnection struct {
	Nodes    []*CustomerTimelineEntry `json:"nodes"`
	PageInfo *PageInfo                `json:"pageInfo"`
}

type CustomerTimelineEntry struct {
	ID         string `json:"id"`
	Kind       string `json:"kind"`
	Status     string `json:"status"`
	OccurredAt string `json:"occurredAt"`
	Historical bool   `json:"historical"`
}

type DashboardSummary struct {
	Total       int `json:"total"`
	Normal      int `json:"normal"`
	Attention   int `json:"attention"`
	Critical    int `json:"critical"`
	Pending     int `json:"pending"`
	Invalidated int `json:"invalidated"`
}

type DeclareCaptureImpossibilityInput struct {
	RequirementKey   string `json:"requirementKey"`
	Reason           string `json:"reason"`
	ExpectedVersion  *int   `json:"expectedVersion,omitempty"`
	ClientMutationID string `json:"clientMutationId"`
}

type DisableMembershipInput struct {
	MembershipID     string `json:"membershipId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type ExternalCapture struct {
	ResponsibilityID   string                `json:"responsibilityId"`
	RecaptureRequestID *string               `json:"recaptureRequestId,omitempty"`
	Status             string                `json:"status"`
	ConfirmationOnly   bool                  `json:"confirmationOnly"`
	Kind               string                `json:"kind"`
	TemplateVersionID  string                `json:"templateVersionId"`
	Reference          map[string]any        `json:"reference"`
	Policy             map[string]any        `json:"policy"`
	Requirements       []*CaptureRequirement `json:"requirements"`
	Answers            []*CaptureAnswer      `json:"answers"`
	DisclosureVersion  string                `json:"disclosureVersion"`
}

type ExternalSessionPayload struct {
	Status           string       `json:"status"`
	CsrfToken        string       `json:"csrfToken"`
	ExpiresAt        string       `json:"expiresAt"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type Inspection struct {
	ID                       string   `json:"id"`
	BusinessUnitID           string   `json:"businessUnitId"`
	AssetID                  string   `json:"assetId"`
	ParticipantID            string   `json:"participantId"`
	TemplateID               string   `json:"templateId"`
	TemplateVersionID        string   `json:"templateVersionId"`
	AnalysisProfileVersionID string   `json:"analysisProfileVersionId"`
	ProjectID                *string  `json:"projectId,omitempty"`
	StageID                  *string  `json:"stageId,omitempty"`
	Source                   string   `json:"source"`
	SourceReason             *string  `json:"sourceReason,omitempty"`
	StateReason              *string  `json:"stateReason,omitempty"`
	Status                   string   `json:"status"`
	EvidenceCount            int      `json:"evidenceCount"`
	DueAt                    string   `json:"dueAt"`
	DeadlineAt               string   `json:"deadlineAt"`
	ReminderInstants         []string `json:"reminderInstants"`
	Version                  int      `json:"version"`
}

type InspectionConnection struct {
	Nodes    []*Inspection `json:"nodes"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type InspectionPayload struct {
	Inspection       *Inspection  `json:"inspection,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type InspectionTransitionInput struct {
	InspectionID     string `json:"inspectionId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type InvalidateInspectionInput struct {
	InspectionID     string `json:"inspectionId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	Reason           string `json:"reason"`
	ClientMutationID string `json:"clientMutationId"`
}

type InvalidateReportPublicationInput struct {
	PublicationID    string `json:"publicationId"`
	Reason           string `json:"reason"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type InvitationOtpPayload struct {
	Status           string       `json:"status"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type InvitationPayload struct {
	Status           string       `json:"status"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type InviteInternalUserInput struct {
	Issuer           string                  `json:"issuer"`
	Subject          string                  `json:"subject"`
	Role             string                  `json:"role"`
	Scopes           []*ScopeAssignmentInput `json:"scopes"`
	ClientMutationID string                  `json:"clientMutationId"`
}

type InviteOriginCaptureInput struct {
	AssetID          string `json:"assetId"`
	ParticipantID    string `json:"participantId"`
	ExpiresAt        string `json:"expiresAt"`
	ClientMutationID string `json:"clientMutationId"`
}

type LegalHoldInput struct {
	InspectionID     string `json:"inspectionId"`
	Reason           string `json:"reason"`
	ClientMutationID string `json:"clientMutationId"`
}

type MarkNotificationReadInput struct {
	NotificationID   string `json:"notificationId"`
	ClientMutationID string `json:"clientMutationId"`
}

type Me struct {
	IdentityID          string        `json:"identityId"`
	TenantID            string        `json:"tenantId"`
	Audience            string        `json:"audience"`
	Product             string        `json:"product"`
	ProductEntitlements []string      `json:"productEntitlements"`
	Roles               []string      `json:"roles"`
	Memberships         []*Membership `json:"memberships"`
	EffectiveScopes     []*Scope      `json:"effectiveScopes"`
}

type Media struct {
	ID              string   `json:"id"`
	Status          string   `json:"status"`
	RequirementKey  *string  `json:"requirementKey,omitempty"`
	Description     *string  `json:"description,omitempty"`
	CaptureSource   *string  `json:"captureSource,omitempty"`
	Flags           []string `json:"flags"`
	ReplacesMediaID *string  `json:"replacesMediaId,omitempty"`
}

type MediaPayload struct {
	Media            *Media       `json:"media,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type MediaUpload struct {
	MediaID       string `json:"mediaId"`
	UploadID      string `json:"uploadId"`
	ExpiresAt     string `json:"expiresAt"`
	PartSizeBytes int    `json:"partSizeBytes"`
}

type MediaUploadPayload struct {
	Upload           *MediaUpload `json:"upload,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type Membership struct {
	ID       string   `json:"id"`
	TenantID string   `json:"tenantId"`
	Role     string   `json:"role"`
	Status   string   `json:"status"`
	Version  int      `json:"version"`
	Scopes   []*Scope `json:"scopes"`
}

type MembershipConnection struct {
	Nodes    []*Membership `json:"nodes"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type MembershipPayload struct {
	Membership       *Membership  `json:"membership,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type Mutation struct {
}

type NotificationDelivery struct {
	ID        string `json:"id"`
	IntentID  string `json:"intentId"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type NotificationDeliveryConnection struct {
	Nodes    []*NotificationDelivery `json:"nodes"`
	PageInfo *PageInfo               `json:"pageInfo"`
}

type NotificationPreferencesPayload struct {
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type OriginInvitationPayload struct {
	InvitationID     *string      `json:"invitationId,omitempty"`
	OriginVersionID  *string      `json:"originVersionId,omitempty"`
	Status           string       `json:"status"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type OriginVersion struct {
	ID            string  `json:"id"`
	OriginID      string  `json:"originId"`
	VersionNumber int     `json:"versionNumber"`
	Status        string  `json:"status"`
	SupersedesID  *string `json:"supersedesId,omitempty"`
	ActivatedAt   *string `json:"activatedAt,omitempty"`
}

type OriginVersionConnection struct {
	Nodes    []*OriginVersion `json:"nodes"`
	PageInfo *PageInfo        `json:"pageInfo"`
}

type OriginVersionInput struct {
	VersionID        string `json:"versionId"`
	ClientMutationID string `json:"clientMutationId"`
}

type OriginVersionPayload struct {
	Version          *OriginVersion `json:"version,omitempty"`
	UserErrors       []*UserError   `json:"userErrors"`
	ClientMutationID string         `json:"clientMutationId"`
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Participant struct {
	ID                 string                `json:"id"`
	BusinessUnitID     string                `json:"businessUnitId"`
	Name               string                `json:"name"`
	SegmentRole        string                `json:"segmentRole"`
	Status             string                `json:"status"`
	Version            int                   `json:"version"`
	Contacts           []*ParticipantContact `json:"contacts"`
	SelectedContactIds []string              `json:"selectedContactIds"`
}

type ParticipantConnection struct {
	Nodes    []*Participant `json:"nodes"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ParticipantContact struct {
	ID       string `json:"id"`
	Channel  string `json:"channel"`
	Value    string `json:"value"`
	Active   bool   `json:"active"`
	Verified bool   `json:"verified"`
}

type ParticipantContactPayload struct {
	Contact          *ParticipantContact `json:"contact,omitempty"`
	UserErrors       []*UserError        `json:"userErrors"`
	ClientMutationID string              `json:"clientMutationId"`
}

type ParticipantPayload struct {
	Participant      *Participant `json:"participant,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type PresignMediaPartsInput struct {
	MediaID          string `json:"mediaId"`
	PartNumbers      []int  `json:"partNumbers"`
	ClientMutationID string `json:"clientMutationId"`
}

type PresignedPart struct {
	PartNumber int    `json:"partNumber"`
	URL        string `json:"url"`
	ExpiresAt  string `json:"expiresAt"`
}

type PresignedPartsPayload struct {
	Parts            []*PresignedPart `json:"parts"`
	UserErrors       []*UserError     `json:"userErrors"`
	ClientMutationID string           `json:"clientMutationId"`
}

type Project struct {
	ID                string             `json:"id"`
	BusinessUnitID    string             `json:"businessUnitId"`
	AssetID           string             `json:"assetId"`
	ParticipantID     string             `json:"participantId"`
	TemplateID        string             `json:"templateId"`
	TemplateVersionID string             `json:"templateVersionId"`
	ReportMode        string             `json:"reportMode"`
	Status            string             `json:"status"`
	Version           int                `json:"version"`
	Stages            []*ProjectStage    `json:"stages"`
	Transitions       []*StageTransition `json:"transitions"`
}

type ProjectConnection struct {
	Nodes    []*Project `json:"nodes"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type ProjectPayload struct {
	Project          *Project     `json:"project,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type ProjectStage struct {
	ID           string  `json:"id"`
	Key          string  `json:"key"`
	Label        string  `json:"label"`
	Kind         string  `json:"kind"`
	Position     int     `json:"position"`
	Status       string  `json:"status"`
	PlannedAt    *string `json:"plannedAt,omitempty"`
	Reason       *string `json:"reason,omitempty"`
	InspectionID *string `json:"inspectionId,omitempty"`
	Version      int     `json:"version"`
}

type ProjectTimeline struct {
	ProjectID string                  `json:"projectId"`
	Entries   []*ProjectTimelineEntry `json:"entries"`
}

type ProjectTimelineEntry struct {
	StageID      string  `json:"stageId"`
	Label        string  `json:"label"`
	Status       string  `json:"status"`
	InspectionID *string `json:"inspectionId,omitempty"`
	OccurredAt   *string `json:"occurredAt,omitempty"`
}

type ProjectTransitionInput struct {
	ProjectID        string `json:"projectId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type PublicationPolicy struct {
	Mode    string `json:"mode"`
	Version int    `json:"version"`
}

type PublicationPolicyPayload struct {
	Policy           *PublicationPolicy `json:"policy,omitempty"`
	UserErrors       []*UserError       `json:"userErrors"`
	ClientMutationID string             `json:"clientMutationId"`
}

type PublishAnalysisProfileInput struct {
	Key              string         `json:"key"`
	Definition       map[string]any `json:"definition"`
	ClientMutationID string         `json:"clientMutationId"`
}

type PublishReportInput struct {
	InspectionID     string `json:"inspectionId"`
	SnapshotID       string `json:"snapshotId"`
	ClientMutationID string `json:"clientMutationId"`
}

type PublishSegmentDefinitionInput struct {
	Key              string         `json:"key"`
	Name             string         `json:"name"`
	Schema           map[string]any `json:"schema"`
	UISchema         map[string]any `json:"uiSchema"`
	ClientMutationID string         `json:"clientMutationId"`
}

type PublishTemplateVersionInput struct {
	Key              string         `json:"key"`
	Name             string         `json:"name"`
	Definition       map[string]any `json:"definition"`
	ClientMutationID string         `json:"clientMutationId"`
}

type Query struct {
}

type Recapture struct {
	ID               string  `json:"id"`
	ResponsibilityID string  `json:"responsibilityId"`
	Status           string  `json:"status"`
	DeadlineAt       *string `json:"deadlineAt,omitempty"`
}

type RecaptureItemInput struct {
	RequirementKey  string  `json:"requirementKey"`
	OriginalMediaID *string `json:"originalMediaId,omitempty"`
	Reason          string  `json:"reason"`
}

type RecapturePayload struct {
	Recapture        *Recapture   `json:"recapture,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type RecipientNotification struct {
	ID           string  `json:"id"`
	Kind         string  `json:"kind"`
	Title        string  `json:"title"`
	Body         string  `json:"body"`
	ResourceKind string  `json:"resourceKind"`
	ResourceID   *string `json:"resourceId,omitempty"`
	CreatedAt    string  `json:"createdAt"`
	ReadAt       *string `json:"readAt,omitempty"`
}

type RecipientNotificationConnection struct {
	Nodes       []*RecipientNotification `json:"nodes"`
	PageInfo    *PageInfo                `json:"pageInfo"`
	UnreadCount int                      `json:"unreadCount"`
}

type RecipientNotificationPayload struct {
	Notification     *RecipientNotification `json:"notification,omitempty"`
	UserErrors       []*UserError           `json:"userErrors"`
	ClientMutationID string                 `json:"clientMutationId"`
}

type RecordDeletionRequestInput struct {
	InspectionID     string  `json:"inspectionId"`
	Reason           *string `json:"reason,omitempty"`
	ClientMutationID string  `json:"clientMutationId"`
}

type RegisterAssetInput struct {
	Asset            *AssetInput `json:"asset"`
	ClientMutationID string      `json:"clientMutationId"`
}

type ReopenProjectInput struct {
	ProjectID        string `json:"projectId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	Reason           string `json:"reason"`
	ClientMutationID string `json:"clientMutationId"`
}

type Report struct {
	ID             string         `json:"id"`
	InspectionID   string         `json:"inspectionId"`
	ProjectID      *string        `json:"projectId,omitempty"`
	Version        int            `json:"version"`
	Mode           string         `json:"mode"`
	Classification string         `json:"classification"`
	JSONDigest     string         `json:"jsonDigest"`
	HTMLDigest     string         `json:"htmlDigest"`
	CanonicalJSON  map[string]any `json:"canonicalJSON"`
	HTML           string         `json:"html"`
	CreatedAt      string         `json:"createdAt"`
}

type ReportDownload struct {
	SnapshotID string  `json:"snapshotId"`
	Kind       string  `json:"kind"`
	ObjectKey  string  `json:"objectKey"`
	URL        string  `json:"url"`
	Status     string  `json:"status"`
	Sha256     *string `json:"sha256,omitempty"`
}

type ReportPublication struct {
	ID            string  `json:"id"`
	SnapshotID    string  `json:"snapshotId"`
	InspectionID  string  `json:"inspectionId"`
	Status        string  `json:"status"`
	Version       int     `json:"version"`
	PublishedAt   *string `json:"publishedAt,omitempty"`
	InvalidatedAt *string `json:"invalidatedAt,omitempty"`
}

type ReportPublicationPayload struct {
	Publication      *ReportPublication `json:"publication,omitempty"`
	UserErrors       []*UserError       `json:"userErrors"`
	ClientMutationID string             `json:"clientMutationId"`
}

type RequestInvitationOtpInput struct {
	LinkToken        string `json:"linkToken"`
	ClientMutationID string `json:"clientMutationId"`
}

type RequestRecaptureInput struct {
	InspectionID     string                `json:"inspectionId"`
	Items            []*RecaptureItemInput `json:"items"`
	DeadlineAt       string                `json:"deadlineAt"`
	ClientMutationID string                `json:"clientMutationId"`
}

type RetentionMutationPayload struct {
	Status           string       `json:"status"`
	RequestID        *string      `json:"requestId,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type RetentionPolicy struct {
	ID              string `json:"id"`
	EvidenceDays    int    `json:"evidenceDays"`
	OperationalDays int    `json:"operationalDays"`
	SecurityDays    int    `json:"securityDays"`
	Version         int    `json:"version"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}

type RetentionPolicyConnection struct {
	Nodes    []*RetentionPolicy `json:"nodes"`
	PageInfo *PageInfo          `json:"pageInfo"`
}

type RetentionPolicyPayload struct {
	Policy           *RetentionPolicy `json:"policy,omitempty"`
	UserErrors       []*UserError     `json:"userErrors"`
	ClientMutationID string           `json:"clientMutationId"`
}

type RevokeInvitationInput struct {
	LinkToken        string `json:"linkToken"`
	ClientMutationID string `json:"clientMutationId"`
}

type SaveCaptureMetadataInput struct {
	MediaID          string           `json:"mediaId"`
	RequirementKey   string           `json:"requirementKey"`
	Description      string           `json:"description"`
	CaptureSource    string           `json:"captureSource"`
	Gps              *CaptureGPSInput `json:"gps,omitempty"`
	DeviceContext    map[string]any   `json:"deviceContext,omitempty"`
	ClientMutationID string           `json:"clientMutationId"`
}

type Schedule struct {
	ID                     string  `json:"id"`
	BusinessUnitID         string  `json:"businessUnitId"`
	AssetID                string  `json:"assetId"`
	ParticipantID          string  `json:"participantId"`
	TemplateID             string  `json:"templateId"`
	ReferenceVersionID     *string `json:"referenceVersionId,omitempty"`
	Rrule                  string  `json:"rrule"`
	Timezone               string  `json:"timezone"`
	StartsAt               string  `json:"startsAt"`
	NextDueAt              string  `json:"nextDueAt"`
	DeadlineMinutes        int     `json:"deadlineMinutes"`
	ReminderOffsetsMinutes []int   `json:"reminderOffsetsMinutes"`
	Status                 string  `json:"status"`
	Version                int     `json:"version"`
}

type ScheduleConnection struct {
	Nodes    []*Schedule `json:"nodes"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type SchedulePayload struct {
	Schedule         *Schedule    `json:"schedule,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type Scope struct {
	Kind       string `json:"kind"`
	ResourceID string `json:"resourceId"`
}

type ScopeAssignmentInput struct {
	Kind       string `json:"kind"`
	ResourceID string `json:"resourceId"`
}

type SegmentDefinition struct {
	ID              string  `json:"id"`
	Key             string  `json:"key"`
	Name            string  `json:"name"`
	ActiveVersionID *string `json:"activeVersionId,omitempty"`
	Version         int     `json:"version"`
}

type SegmentDefinitionConnection struct {
	Nodes    []*SegmentDefinition `json:"nodes"`
	PageInfo *PageInfo            `json:"pageInfo"`
}

type SegmentDefinitionPayload struct {
	Definition       *SegmentDefinition        `json:"definition,omitempty"`
	Version          *SegmentDefinitionVersion `json:"version,omitempty"`
	UserErrors       []*UserError              `json:"userErrors"`
	ClientMutationID string                    `json:"clientMutationId"`
}

type SegmentDefinitionVersion struct {
	ID              string         `json:"id"`
	DefinitionID    string         `json:"definitionId"`
	VersionNumber   int            `json:"versionNumber"`
	SchemaVersion   int            `json:"schemaVersion"`
	Schema          map[string]any `json:"schema"`
	UISchema        map[string]any `json:"uiSchema"`
	CanonicalDigest string         `json:"canonicalDigest"`
	Status          string         `json:"status"`
	PublishedAt     string         `json:"publishedAt"`
}

type SensitiveFalsePositiveInput struct {
	MediaID          string `json:"mediaId"`
	Reason           string `json:"reason"`
	ClientMutationID string `json:"clientMutationId"`
}

type SetDeliveryChannelsInput struct {
	ParticipantID    string   `json:"participantId"`
	ContactIds       []string `json:"contactIds"`
	ExpectedVersion  int      `json:"expectedVersion"`
	ClientMutationID string   `json:"clientMutationId"`
}

type SkipProjectStageInput struct {
	ProjectID        string `json:"projectId"`
	StageID          string `json:"stageId"`
	ExpectedVersion  int    `json:"expectedVersion"`
	Reason           string `json:"reason"`
	ClientMutationID string `json:"clientMutationId"`
}

type StageTransition struct {
	ID         string  `json:"id"`
	StageID    *string `json:"stageId,omitempty"`
	FromState  *string `json:"fromState,omitempty"`
	ToState    string  `json:"toState"`
	Reason     *string `json:"reason,omitempty"`
	OccurredAt string  `json:"occurredAt"`
}

type StartProjectStageInput struct {
	ProjectID              string   `json:"projectId"`
	StageID                string   `json:"stageId"`
	ExpectedProjectVersion int      `json:"expectedProjectVersion"`
	ExpectedStageVersion   int      `json:"expectedStageVersion"`
	ReferenceVersionID     *string  `json:"referenceVersionId,omitempty"`
	DueAt                  string   `json:"dueAt"`
	DeadlineAt             string   `json:"deadlineAt"`
	ReminderInstants       []string `json:"reminderInstants"`
	ClientMutationID       string   `json:"clientMutationId"`
}

type Submission struct {
	ID                string `json:"id"`
	Complete          bool   `json:"complete"`
	RequiresAttention bool   `json:"requiresAttention"`
	SubmittedAt       string `json:"submittedAt"`
}

type SubmissionPayload struct {
	Submission       *Submission  `json:"submission,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type SubmitCaptureInput struct {
	ConfirmIncomplete bool   `json:"confirmIncomplete"`
	ClientMutationID  string `json:"clientMutationId"`
}

type SubmitRecaptureInput struct {
	RequestID         string `json:"requestId"`
	ConfirmIncomplete bool   `json:"confirmIncomplete"`
	ClientMutationID  string `json:"clientMutationId"`
}

type Template struct {
	ID               string  `json:"id"`
	Key              string  `json:"key"`
	Name             string  `json:"name"`
	SegmentVersionID string  `json:"segmentVersionId"`
	ActiveVersionID  *string `json:"activeVersionId,omitempty"`
	Version          int     `json:"version"`
}

type TemplateConnection struct {
	Nodes    []*Template `json:"nodes"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TemplatePayload struct {
	Template         *Template        `json:"template,omitempty"`
	Version          *TemplateVersion `json:"version,omitempty"`
	UserErrors       []*UserError     `json:"userErrors"`
	ClientMutationID string           `json:"clientMutationId"`
}

type TemplateVersion struct {
	ID              string         `json:"id"`
	TemplateID      string         `json:"templateId"`
	VersionNumber   int            `json:"versionNumber"`
	SchemaVersion   int            `json:"schemaVersion"`
	Definition      map[string]any `json:"definition"`
	CanonicalDigest string         `json:"canonicalDigest"`
	Status          string         `json:"status"`
	PublishedAt     string         `json:"publishedAt"`
}

type Tenant struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Language        string `json:"language"`
	DefaultTimezone string `json:"defaultTimezone"`
	Status          string `json:"status"`
	Version         int    `json:"version"`
}

type TenantPayload struct {
	Tenant           *Tenant      `json:"tenant,omitempty"`
	UserErrors       []*UserError `json:"userErrors"`
	ClientMutationID string       `json:"clientMutationId"`
}

type TriageInspection struct {
	InspectionID   string  `json:"inspectionId"`
	ProjectID      *string `json:"projectId,omitempty"`
	AssetID        *string `json:"assetId,omitempty"`
	Classification string  `json:"classification"`
	Status         string  `json:"status"`
	UpdatedAt      string  `json:"updatedAt"`
}

type TriageInspectionConnection struct {
	Nodes    []*TriageInspection `json:"nodes"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type UpdateAssetInput struct {
	AssetID          string      `json:"assetId"`
	ExpectedVersion  int         `json:"expectedVersion"`
	Asset            *AssetInput `json:"asset"`
	ClientMutationID string      `json:"clientMutationId"`
}

type UpdateScheduleInput struct {
	ScheduleID             string `json:"scheduleId"`
	ExpectedVersion        int    `json:"expectedVersion"`
	Rrule                  string `json:"rrule"`
	Timezone               string `json:"timezone"`
	StartsAt               string `json:"startsAt"`
	DeadlineMinutes        int    `json:"deadlineMinutes"`
	ReminderOffsetsMinutes []int  `json:"reminderOffsetsMinutes"`
	ClientMutationID       string `json:"clientMutationId"`
}

type UpdateTenantInput struct {
	Name             string `json:"name"`
	Language         string `json:"language"`
	Timezone         string `json:"timezone"`
	ExpectedVersion  int    `json:"expectedVersion"`
	ClientMutationID string `json:"clientMutationId"`
}

type UpsertBusinessUnitInput struct {
	BusinessUnitID        *string `json:"businessUnitId,omitempty"`
	Code                  string  `json:"code"`
	Name                  string  `json:"name"`
	ExpectedVersion       *int    `json:"expectedVersion,omitempty"`
	ExpectedTenantVersion *int    `json:"expectedTenantVersion,omitempty"`
	ClientMutationID      string  `json:"clientMutationId"`
}

type UpsertParticipantInput struct {
	ParticipantID    *string         `json:"participantId,omitempty"`
	ExpectedVersion  *int            `json:"expectedVersion,omitempty"`
	BusinessUnitID   string          `json:"businessUnitId"`
	Name             string          `json:"name"`
	SegmentRole      string          `json:"segmentRole"`
	Contacts         []*ContactInput `json:"contacts"`
	ClientMutationID string          `json:"clientMutationId"`
}

type UsageSummary struct {
	From         string  `json:"from"`
	To           string  `json:"to"`
	Requests     int     `json:"requests"`
	InputTokens  int     `json:"inputTokens"`
	OutputTokens int     `json:"outputTokens"`
	Cost         float64 `json:"cost"`
}

type UserError struct {
	Code          string  `json:"code"`
	Field         *string `json:"field,omitempty"`
	Message       string  `json:"message"`
	CorrelationID string  `json:"correlationId"`
}

type VerifyContactInput struct {
	ContactID        string `json:"contactId"`
	Verified         bool   `json:"verified"`
	ClientMutationID string `json:"clientMutationId"`
}

type VerifyInvitationOtpInput struct {
	LinkToken        string `json:"linkToken"`
	Code             string `json:"code"`
	ClientMutationID string `json:"clientMutationId"`
}

type EvidenceMode string

const (
	EvidenceModeSimple   EvidenceMode = "SIMPLE"
	EvidenceModeAdvanced EvidenceMode = "ADVANCED"
)

var AllEvidenceMode = []EvidenceMode{
	EvidenceModeSimple,
	EvidenceModeAdvanced,
}

func (e EvidenceMode) IsValid() bool {
	switch e {
	case EvidenceModeSimple, EvidenceModeAdvanced:
		return true
	}
	return false
}

func (e EvidenceMode) String() string {
	return string(e)
}

func (e *EvidenceMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EvidenceMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EvidenceMode", str)
	}
	return nil
}

func (e EvidenceMode) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EvidenceMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EvidenceMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
